import type { Fact } from "@/types";

export const facts: Fact[] = [
  {
    id: 1,
    fact: "A single strand of spaghetti is called a 'spaghetto'.",
    category: "Culture",
    funLevel: 4,
    source: "Britannica",
    tags: ["food", "language", "italy"],
    isVerified: true,
  },
  {
    id: 2,
    fact: "The Eiffel Tower can be 15 cm taller during the summer due to thermal expansion.",
    category: "Science",
    funLevel: 4,
    source: "Discovery",
    tags: ["physics", "engineering", "paris"],
    isVerified: true,
  },
  {
    id: 3,
    fact: "Wombat poop is cube-shaped.",
    category: "Animals",
    funLevel: 5,
    source: "National Geographic",
    tags: ["biology", "mammals", "weird"],
    isVerified: true,
  },
  {
    id: 4,
    fact: "Venus rotates clockwise, the opposite direction of most planets.",
    category: "Space",
    funLevel: 4,
    source: "NASA",
    tags: ["astronomy", "planets", "solar system"],
    isVerified: true,
  },
  {
    id: 5,
    fact: "The shortest war in history lasted only 38 minutes (Anglo-Zanzibar War).",
    category: "History",
    funLevel: 5,
    source: "History Channel",
    tags: ["war", "records", "africa"],
    isVerified: true,
  },
  {
    id: 6,
    fact: "The first computer mouse was made of wood.",
    category: "Technology",
    funLevel: 3,
    source: "Smithsonian",
    tags: ["computing", "inventions", "history"],
    isVerified: true,
  },
  {
    id: 7,
    fact: "Bananas are berries, but strawberries are not.",
    category: "Nature",
    funLevel: 4,
    source: "Britannica",
    tags: ["fruit", "botany", "food"],
    isVerified: true,
  },
  {
    id: 8,
    fact: "Cleopatra lived closer in time to the first moon landing than to the building of the Great Pyramid.",
    category: "History",
    funLevel: 5,
    source: "Smithsonian",
    tags: ["time", "egypt", "perspective"],
    isVerified: true,
  },
  {
    id: 9,
    fact: "A day on Venus is longer than a year on Venus.",
    category: "Space",
    funLevel: 5,
    source: "NASA",
    tags: ["venus", "planets", "time"],
    isVerified: true,
  },
  {
    id: 10,
    fact: "Octopuses have three hearts and blue blood.",
    category: "Animals",
    funLevel: 4,
    source: "National Geographic",
    tags: ["marine life", "biology", "ocean"],
    isVerified: true,
  },
  {
    id: 11,
    fact: "Honey never spoils.",
    category: "Nature",
    funLevel: 4,
    source: "Smithsonian",
    tags: ["food", "science", "chemistry"],
    isVerified: true,
  },
  {
    id: 12,
    fact: "Humans share 50% of their DNA with bananas.",
    category: "Science",
    funLevel: 4,
    source: "Scientific American",
    tags: ["genetics", "biology", "humans"],
    isVerified: true,
  },
  {
    id: 13,
    fact: "The state of Kentucky has more bourbon barrels than people.",
    category: "Culture",
    funLevel: 3,
    source: "Discovery",
    tags: ["usa", "alcohol", "statistics"],
    isVerified: true,
  },
  {
    id: 14,
    fact: "The Twitter bird's official name is Larry.",
    category: "Technology",
    funLevel: 3,
    source: "BBC",
    tags: ["social media", "branding", "names"],
    isVerified: true,
  },
  {
    id: 15,
    fact: "In Switzerland, it is illegal to own just one guinea pig.",
    category: "Culture",
    funLevel: 4,
    source: "BBC",
    tags: ["law", "animals", "switzerland"],
    isVerified: true,
  },
  {
    id: 16,
    fact: "A crocodile cannot stick its tongue out.",
    category: "Animals",
    funLevel: 3,
    source: "National Geographic",
    tags: ["reptiles", "biology", "anatomy"],
    isVerified: true,
  },
  {
    id: 17,
    fact: "The unicorn is the national animal of Scotland.",
    category: "Culture",
    funLevel: 5,
    source: "National Geographic",
    tags: ["scotland", "mythology", "symbols"],
    isVerified: true,
  },
  {
    id: 18,
    fact: "Australia is wider than the moon.",
    category: "Space",
    funLevel: 4,
    source: "NASA",
    tags: ["geography", "moon", "scale"],
    isVerified: true,
  },
  {
    id: 19,
    fact: "There are more trees on Earth than stars in the Milky Way galaxy.",
    category: "Nature",
    funLevel: 4,
    source: "Scientific American",
    tags: ["trees", "space", "statistics"],
    isVerified: true,
  },
  {
    id: 20,
    fact: "Chainsaws were originally invented for childbirth.",
    category: "History",
    funLevel: 5,
    source: "Smithsonian",
    tags: ["inventions", "medicine", "weird"],
    isVerified: true,
  },
  {
    id: 21,
    fact: "The chemical element 'Helium' was first detected on the Sun.",
    category: "Science",
    funLevel: 3,
    source: "Britannica",
    tags: ["chemistry", "astronomy", "sun"],
    isVerified: true,
  },
  {
    id: 22,
    fact: "The 'Q' in 'Q-tip' stands for 'Quality'.",
    category: "Culture",
    funLevel: 2,
    source: "Discovery",
    tags: ["branding", "products", "language"],
    isVerified: true,
  },
  {
    id: 23,
    fact: "A group of flamingos is called a 'flamboyance'.",
    category: "Animals",
    funLevel: 4,
    source: "Smithsonian",
    tags: ["birds", "language", "groups"],
    isVerified: true,
  },
  {
    id: 24,
    fact: "The first item sold on eBay was a broken laser pointer.",
    category: "Technology",
    funLevel: 3,
    source: "BBC",
    tags: ["internet", "ecommerce", "history"],
    isVerified: true,
  },
  {
    id: 25,
    fact: "Oxford University is older than the Aztec Empire.",
    category: "History",
    funLevel: 4,
    source: "Smithsonian",
    tags: ["education", "time", "comparison"],
    isVerified: true,
  },
  {
    id: 26,
    fact: "The footprints left on the Moon will likely stay there for 100 million years.",
    category: "Space",
    funLevel: 4,
    source: "NASA",
    tags: ["moon", "apollo", "erosion"],
    isVerified: true,
  },
  {
    id: 27,
    fact: "There is a species of jellyfish that is considered immortal.",
    category: "Nature",
    funLevel: 5,
    source: "National Geographic",
    tags: ["biology", "ocean", "immortality"],
    isVerified: true,
  },
  {
    id: 28,
    fact: "Sound cannot travel in a vacuum.",
    category: "Science",
    funLevel: 2,
    source: "Scientific American",
    tags: ["physics", "sound", "space"],
    isVerified: true,
  },
  {
    id: 29,
    fact: "Sea otters hold hands while sleeping so they don't drift apart.",
    category: "Animals",
    funLevel: 5,
    source: "National Geographic",
    tags: ["mammals", "behavior", "cute"],
    isVerified: true,
  },
  {
    id: 30,
    fact: "The 'M's' in 'M&Ms' stand for 'Mars' and 'Murrie'.",
    category: "Culture",
    funLevel: 3,
    source: "History Channel",
    tags: ["food", "candy", "names"],
    isVerified: true,
  },
  {
    id: 31,
    fact: "The original name for the search engine Google was 'Backrub'.",
    category: "Technology",
    funLevel: 3,
    source: "Britannica",
    tags: ["internet", "google", "history"],
    isVerified: true,
  },
  {
    id: 32,
    fact: "Ketchup was sold as medicine in the 1830s.",
    category: "History",
    funLevel: 4,
    source: "History Channel",
    tags: ["food", "medicine", "usa"],
    isVerified: true,
  },
  {
    id: 33,
    fact: "The planet Uranus was originally named 'George's Star'.",
    category: "Space",
    funLevel: 4,
    source: "NASA",
    tags: ["uranus", "astronomy", "names"],
    isVerified: true,
  },
  {
    id: 34,
    fact: "A bolt of lightning is five times hotter than the surface of the sun.",
    category: "Nature",
    funLevel: 4,
    source: "National Geographic",
    tags: ["weather", "physics", "temperature"],
    isVerified: true,
  },
  {
    id: 35,
    fact: "The human nose can detect over 1 trillion different scents.",
    category: "Science",
    funLevel: 3,
    source: "Scientific American",
    tags: ["biology", "senses", "humans"],
    isVerified: true,
  },
  {
    id: 36,
    fact: "A shrimp's heart is located in its head.",
    category: "Animals",
    funLevel: 4,
    source: "Discovery",
    tags: ["marine life", "anatomy", "crustaceans"],
    isVerified: true,
  },
  {
    id: 37,
    fact: "Nintendo was founded in 1889 as a playing card company.",
    category: "Technology",
    funLevel: 4,
    source: "Britannica",
    tags: ["gaming", "history", "japan"],
    isVerified: true,
  },
  {
    id: 38,
    fact: "The word 'avocado' comes from an Aztec word for 'testicle'.",
    category: "Culture",
    funLevel: 4,
    source: "Britannica",
    tags: ["language", "etymology", "food"],
    isVerified: true,
  },
  {
    id: 39,
    fact: "There is a volcano on Mars three times the size of Mount Everest.",
    category: "Space",
    funLevel: 4,
    source: "NASA",
    tags: ["mars", "volcanoes", "solar system"],
    isVerified: true,
  },
  {
    id: 40,
    fact: "Pineapples grow on bushes, not trees.",
    category: "Nature",
    funLevel: 3,
    source: "Britannica",
    tags: ["plants", "fruit", "gardening"],
    isVerified: true,
  },
  {
    id: 41,
    fact: "In ancient Rome, 'vomitoriums' were pathways to exit stadiums, not rooms for purging.",
    category: "History",
    funLevel: 4,
    source: "History Channel",
    tags: ["rome", "language", "architecture"],
    isVerified: true,
  },
  {
    id: 42,
    fact: "A teaspoonful of neutron star material would weigh 6 billion tons.",
    category: "Space",
    funLevel: 5,
    source: "NASA",
    tags: ["stars", "physics", "density"],
    isVerified: true,
  },
  {
    id: 43,
    fact: "Cows have best friends and get stressed when separated from them.",
    category: "Animals",
    funLevel: 4,
    source: "BBC",
    tags: ["mammals", "behavior", "farming"],
    isVerified: true,
  },
  {
    id: 44,
    fact: "The average cloud weighs around 1.1 million pounds (500,000 kg).",
    category: "Science",
    funLevel: 4,
    source: "Scientific American",
    tags: ["weather", "physics", "meteorology"],
    isVerified: true,
  },
  {
    id: 45,
    fact: "Samsung tests its phone durability using a robot butt.",
    category: "Technology",
    funLevel: 4,
    source: "Discovery",
    tags: ["phones", "testing", "robots"],
    isVerified: true,
  },
  {
    id: 46,
    fact: "Stop signs were originally yellow, not red.",
    category: "History",
    funLevel: 3,
    source: "History Channel",
    tags: ["transportation", "design", "safety"],
    isVerified: true,
  },
  {
    id: 47,
    fact: "The longest living animal is the ocean quahog, which can live over 500 years.",
    category: "Animals",
    funLevel: 4,
    source: "National Geographic",
    tags: ["longevity", "ocean", "mollusks"],
    isVerified: true,
  },
  {
    id: 48,
    fact: "The 'sixth sick sheik's sixth sheep's sick' is considered the toughest tongue twister in English.",
    category: "Culture",
    funLevel: 3,
    source: "Guinness World Records",
    tags: ["language", "english", "records"],
    isVerified: true,
  },
  {
    id: 49,
    fact: "There are more possible iterations of a game of chess than there are atoms in the known universe.",
    category: "Science",
    funLevel: 4,
    source: "Britannica",
    tags: ["chess", "math", "games"],
    isVerified: true,
  },
  {
    id: 50,
    fact: "It rains diamonds on Saturn and Jupiter.",
    category: "Space",
    funLevel: 5,
    source: "NASA",
    tags: ["planets", "weather", "atmosphere"],
    isVerified: true,
  },
  {
    id: 51,
    fact: "The mushroom is genetically closer to humans than to plants.",
    category: "Nature",
    funLevel: 4,
    source: "Scientific American",
    tags: ["fungi", "genetics", "biology"],
    isVerified: true,
  },
  {
    id: 52,
    fact: "The original 'Star Wars' movie was released in 1977 without the 'Episode IV' title.",
    category: "Culture",
    funLevel: 2,
    source: "Smithsonian",
    tags: ["movies", "film", "star wars"],
    isVerified: true,
  },
  {
    id: 53,
    fact: "A computer 'bug' was named after a real moth found trapped in a computer in 1947.",
    category: "Technology",
    funLevel: 4,
    source: "Smithsonian",
    tags: ["computing", "history", "language"],
    isVerified: true,
  },
  {
    id: 54,
    fact: "Napoleon Bonaparte was once attacked by a horde of rabbits.",
    category: "History",
    funLevel: 5,
    source: "History Channel",
    tags: ["napoleon", "animals", "france"],
    isVerified: true,
  },
  {
    id: 55,
    fact: "The heart of a blue whale is the size of a small car.",
    category: "Animals",
    funLevel: 4,
    source: "National Geographic",
    tags: ["mammals", "ocean", "anatomy"],
    isVerified: true,
  },
  {
    id: 56,
    fact: "If you drilled a tunnel straight through Earth, it would take 42 minutes to fall to the other side.",
    category: "Science",
    funLevel: 4,
    source: "Scientific American",
    tags: ["physics", "gravity", "thought experiment"],
    isVerified: true,
  },
  {
    id: 57,
    fact: "The Sun makes up 99.86% of the mass in our solar system.",
    category: "Space",
    funLevel: 3,
    source: "NASA",
    tags: ["sun", "solar system", "mass"],
    isVerified: true,
  },
  {
    id: 58,
    fact: "Armadillos almost always give birth to identical quadruplets.",
    category: "Animals",
    funLevel: 4,
    source: "Discovery",
    tags: ["mammals", "reproduction", "genetics"],
    isVerified: true,
  },
  {
    id: 59,
    fact: "The national anthem of Spain has no official lyrics.",
    category: "Culture",
    funLevel: 3,
    source: "Britannica",
    tags: ["music", "spain", "symbols"],
    isVerified: true,
  },
  {
    id: 60,
    fact: "The Hawaiian alphabet only has 13 letters.",
    category: "Culture",
    funLevel: 3,
    source: "Britannica",
    tags: ["language", "hawaii", "alphabet"],
    isVerified: true,
  },
  {
    id: 61,
    fact: "The Great Wall of China is not visible from the Moon with the naked eye.",
    category: "Space",
    funLevel: 3,
    source: "NASA",
    tags: ["myth", "moon", "china"],
    isVerified: true,
  },
  {
    id: 62,
    fact: "In 1903, the Wright brothers' first successful flight lasted 12 seconds.",
    category: "History",
    funLevel: 3,
    source: "Smithsonian",
    tags: ["aviation", "inventions", "transportation"],
    isVerified: true,
  },
  {
    id: 63,
    fact: "There is a 'water' reservoir in space that holds 140 trillion times the water in Earth's oceans.",
    category: "Space",
    funLevel: 5,
    source: "NASA",
    tags: ["water", "quasar", "astronomy"],
    isVerified: true,
  },
  {
    id: 64,
    fact: "The largest desert in the world is Antarctica.",
    category: "Nature",
    funLevel: 4,
    source: "National Geographic",
    tags: ["geography", "desert", "antarctica"],
    isVerified: true,
  },
  {
    id: 65,
    fact: "The first vending machine was invented in Ancient Greece and dispensed holy water.",
    category: "Technology",
    funLevel: 4,
    source: "History Channel",
    tags: ["inventions", "history", "greece"],
    isVerified: true,
  },
  {
    id: 66,
    fact: "A cockroach can live for weeks without its head.",
    category: "Animals",
    funLevel: 5,
    source: "Scientific American",
    tags: ["insects", "biology", "survival"],
    isVerified: true,
  },
  {
    id: 67,
    fact: "Humans are the only animals known to blush.",
    category: "Science",
    funLevel: 3,
    source: "BBC",
    tags: ["biology", "psychology", "emotions"],
    isVerified: true,
  },
  {
    id: 68,
    fact: "The word 'nerd' was first coined by Dr. Seuss in 'If I Ran the Zoo'.",
    category: "Culture",
    funLevel: 3,
    source: "Britannica",
    tags: ["language", "books", "etymology"],
    isVerified: true,
  },
  {
    id: 69,
    fact: "Vikings used the bones of their enemies to make their weapons stronger.",
    category: "History",
    funLevel: 4,
    source: "History Channel",
    tags: ["vikings", "war", "ritual"],
    isVerified: true,
  },
  {
    id: 70,
    fact: "A group of pugs is called a 'grumble'.",
    category: "Animals",
    funLevel: 4,
    source: "Discovery",
    tags: ["dogs", "language", "groups"],
    isVerified: true,
  },
  {
    id: 71,
    fact: "The human brain operates on about 20 watts of power.",
    category: "Science",
    funLevel: 3,
    source: "Scientific American",
    tags: ["biology", "brain", "energy"],
    isVerified: true,
  },
  {
    id: 72,
    fact: "The world's oldest known recipe is for beer.",
    category: "History",
    funLevel: 4,
    source: "Smithsonian",
    tags: ["food", "beer", "sumer"],
    isVerified: true,
  },
  {
    id: 73,
    fact: "There are more fake flamingos in the world than real ones.",
    category: "Nature",
    funLevel: 3,
    source: "BBC",
    tags: ["birds", "statistics", "culture"],
    isVerified: true,
  },
  {
    id: 74,
    fact: "The quietest room in the world, an anechoic chamber, has a background noise level of -9.4 decibels.",
    category: "Technology",
    funLevel: 4,
    source: "Guinness World Records",
    tags: ["sound", "physics", "records"],
    isVerified: true,
  },
  {
    id: 75,
    fact: "The smell of freshly cut grass is actually a plant distress call.",
    category: "Nature",
    funLevel: 4,
    source: "Scientific American",
    tags: ["plants", "chemistry", "scent"],
    isVerified: true,
  },
  {
    id: 76,
    fact: "The color 'orange' was named after the fruit, not the other way around.",
    category: "Culture",
    funLevel: 3,
    source: "Britannica",
    tags: ["language", "color", "food"],
    isVerified: true,
  },
  {
    id: 77,
    fact: "An adult human is made up of approximately 7 octillion atoms.",
    category: "Science",
    funLevel: 3,
    source: "Discovery",
    tags: ["chemistry", "biology", "numbers"],
    isVerified: true,
  },
  {
    id: 78,
    fact: "The 'tin can' opener was invented 48 years after the tin can.",
    category: "History",
    funLevel: 4,
    source: "History Channel",
    tags: ["inventions", "food", "technology"],
    isVerified: true,
  },
  {
    id: 79,
    fact: "A hummingbird's heart beats over 1,200 times per minute.",
    category: "Animals",
    funLevel: 4,
    source: "National Geographic",
    tags: ["birds", "biology", "anatomy"],
    isVerified: true,
  },
  {
    id: 80,
    fact: "The total weight of all ants on Earth is estimated to be equal to or greater than the total weight of all humans.",
    category: "Animals",
    funLevel: 4,
    source: "BBC",
    tags: ["insects", "statistics", "biology"],
    isVerified: true,
  },
  {
    id: 81,
    fact: "Space smells like seared steak, hot metal, and welding fumes.",
    category: "Space",
    funLevel: 4,
    source: "NASA",
    tags: ["astronauts", "scent", "space station"],
    isVerified: true,
  },
  {
    id: 82,
    fact: "The 'D' in 'D-Day' simply stands for 'Day'.",
    category: "History",
    funLevel: 2,
    source: "History Channel",
    tags: ["wwii", "language", "military"],
    isVerified: true,
  },
  {
    id: 83,
    fact: "The first floppy disk was invented in 1971 and could hold 80 KB of data.",
    category: "Technology",
    funLevel: 2,
    source: "Britannica",
    tags: ["computing", "storage", "history"],
    isVerified: true,
  },
  {
    id: 84,
    fact: "Russia has a larger surface area than the planet Pluto.",
    category: "Space",
    funLevel: 4,
    source: "NASA",
    tags: ["geography", "pluto", "scale"],
    isVerified: true,
  },
  {
    id: 85,
    fact: "Carrots were originally purple, not orange.",
    category: "Nature",
    funLevel: 3,
    source: "BBC",
    tags: ["food", "history", "plants"],
    isVerified: true,
  },
  {
    id: 86,
    fact: "Some cats are allergic to humans.",
    category: "Animals",
    funLevel: 4,
    source: "Scientific American",
    tags: ["cats", "allergies", "pets"],
    isVerified: true,
  },
  {
    id: 87,
    fact: "It's impossible to hum while holding your nose closed.",
    category: "Science",
    funLevel: 3,
    source: "Discovery",
    tags: ["biology", "humans", "sound"],
    isVerified: true,
  },
  {
    id: 88,
    fact: "The longest place name in the world has 85 letters (in New Zealand).",
    category: "Culture",
    funLevel: 4,
    source: "Guinness World Records",
    tags: ["geography", "language", "records"],
    isVerified: true,
  },
  {
    id: 89,
    fact: "The word 'goodbye' is a contraction of 'God be with ye'.",
    category: "Culture",
    funLevel: 3,
    source: "Britannica",
    tags: ["language", "etymology", "history"],
    isVerified: true,
  },
  {
    id: 90,
    fact: "The dot over the letter 'i' and 'j' is called a 'tittle'.",
    category: "Culture",
    funLevel: 4,
    source: "Britannica",
    tags: ["language", "writing", "Word Power"],
    isVerified: true,
  },
  {
    id: 91,
    fact: "In 1997, Netflix was a DVD-by-mail rental service.",
    category: "Technology",
    funLevel: 2,
    source: "Smithsonian",
    tags: ["internet", "streaming", "history"],
    isVerified: true,
  },
  {
    id: 92,
    fact: "A jiffy is an actual unit of time, equal to 1/100th of a second.",
    category: "Science",
    funLevel: 3,
    source: "Britannica",
    tags: ["measurement", "time", "physics"],
    isVerified: true,
  },
  {
    id: 93,
    fact: "There is a town in Norway simply named 'A'.",
    category: "Culture",
    funLevel: 3,
    source: "National Geographic",
    tags: ["geography", "norway", "names"],
    isVerified: true,
  },
  {
    id: 94,
    fact: "A polar bear's skin is black.",
    category: "Animals",
    funLevel: 4,
    source: "National Geographic",
    tags: ["mammals", "arctic", "biology"],
    isVerified: true,
  },
  {
    id: 95,
    fact: "Hippo milk is pink.",
    category: "Animals",
    funLevel: 5,
    source: "Discovery",
    tags: ["mammals", "africa", "biology"],
    isVerified: true,
  },
  {
    id: 96,
    fact: "Australia's 'dingo fence' is longer than the Great Wall of China.",
    category: "Nature",
    funLevel: 3,
    source: "National Geographic",
    tags: ["australia", "construction", "animals"],
    isVerified: true,
  },
  {
    id: 97,
    fact: "Tug of war was an Olympic sport from 1900 to 1920.",
    category: "History",
    funLevel: 3,
    source: "Smithsonian",
    tags: ["sports", "olympics", "history"],
    isVerified: true,
  },
  {
    id: 98,
    fact: "The 'P' in the 'pH' scale stands for 'power' or 'potential' of hydrogen.",
    category: "Science",
    funLevel: 2,
    source: "Scientific American",
    tags: ["chemistry", "language", "measurement"],
    isVerified: true,
  },
  {
    id: 99,
    fact: "The first video uploaded to YouTube was 'Me at the zoo' in 2005.",
    category: "Technology",
    funLevel: 2,
    source: "BBC",
    tags: ["internet", "video", "history"],
    isVerified: true,
  },
  {
    id: 100,
    fact: "The Great Red Spot on Jupiter is a storm that has been raging for at least 350 years.",
    category: "Space",
    funLevel: 4,
    source: "NASA",
    tags: ["jupiter", "weather", "astronomy"],
    isVerified: true,
  },
  {
    id: 101,
    fact: "If you could fold a piece of paper 42 times, it would reach the Moon.",
    category: "Science",
    funLevel: 4,
    source: "Discovery",
    tags: ["math", "physics", "exponential"],
    isVerified: true,
  },
  {
    id: 102,
    fact: "The word 'lethargy' comes from the mythical Greek river 'Lethe', which caused forgetfulness.",
    category: "Culture",
    funLevel: 3,
    source: "Britannica",
    tags: ["language", "mythology", "greece"],
    isVerified: true,
  },
  {
    id: 103,
    fact: "A group of owls is called a 'parliament'.",
    category: "Animals",
    funLevel: 4,
    source: "Smithsonian",
    tags: ["birds", "language", "groups"],
    isVerified: true,
  },
  {
    id: 104,
    fact: "During World War II, the Academy Awards (Oscars) were made of painted plaster.",
    category: "History",
    funLevel: 3,
    source: "History Channel",
    tags: ["wwii", "movies", "awards"],
    isVerified: true,
  },
  {
    id: 105,
    fact: "Cashews grow on the outside of a fruit, called a cashew apple.",
    category: "Nature",
    funLevel: 4,
    source: "Britannica",
    tags: ["food", "plants", "nuts"],
    isVerified: true,
  },
  {
    id: 106,
    fact: "The Apollo astronauts' footprints on the Moon could last for millions of years.",
    category: "Space",
    funLevel: 4,
    source: "NASA",
    tags: ["moon", "apollo", "space exploration"],
    isVerified: true,
  },
  {
    id: 107,
    fact: "A duck's quack does not echo.",
    category: "Animals",
    funLevel: 4,
    source: "Discovery",
    tags: ["birds", "sound", "physics"],
    isVerified: false,
  },
  {
    id: 108,
    fact: "The first public 'selfie' was taken in 1839 by Robert Cornelius.",
    category: "Technology",
    funLevel: 3,
    source: "Smithsonian",
    tags: ["photography", "history", "selfie"],
    isVerified: true,
  },
  {
    id: 109,
    fact: "The human stomach can dissolve razor blades.",
    category: "Science",
    funLevel: 4,
    source: "Scientific American",
    tags: ["biology", "chemistry", "acid"],
    isVerified: true,
  },
  {
    id: 110,
    fact: "The national animal of Wales is the dragon.",
    category: "Culture",
    funLevel: 4,
    source: "BBC",
    tags: ["wales", "mythology", "symbols"],
    isVerified: true,
  },
  {
    id: 111,
    fact: "The Colosseum in Rome once held mock sea battles.",
    category: "History",
    funLevel: 4,
    source: "History Channel",
    tags: ["rome", "architecture", "entertainment"],
    isVerified: true,
  },
  {
    id: 112,
    fact: "A mantis shrimp can punch with the force of a .22 caliber bullet.",
    category: "Animals",
    funLevel: 5,
    source: "National Geographic",
    tags: ["ocean", "biology", "physics"],
    isVerified: true,
  },
  {
    id: 113,
    fact: "The shortest commercial flight in the world lasts 90 seconds (in Scotland).",
    category: "Technology",
    funLevel: 3,
    source: "Guinness World Records",
    tags: ["aviation", "transportation", "records"],
    isVerified: true,
  },
  {
    id: 114,
    fact: "Mount Everest is not the tallest mountain in the world from base to peak (Mauna Kea is).",
    category: "Nature",
    funLevel: 4,
    source: "National Geographic",
    tags: ["geography", "mountains", "ocean"],
    isVerified: true,
  },
  {
    id: 115,
    fact: "The Sun is actually white, but appears yellow due to Earth's atmosphere.",
    category: "Space",
    funLevel: 3,
    source: "NASA",
    tags: ["sun", "atmosphere", "color"],
    isVerified: true,
  },
  {
    id: 116,
    fact: "The first alarm clock could only ring at 4 AM.",
    category: "History",
    funLevel: 3,
    source: "Smithsonian",
    tags: ["inventions", "time", "technology"],
    isVerified: true,
  },
  {
    id: 117,
    fact: "Bees can recognize human faces.",
    category: "Animals",
    funLevel: 4,
    source: "BBC",
    tags: ["insects", "intelligence", "biology"],
    isVerified: true,
  },
  {
    id: 118,
    fact: "The speed of light is not constant; it can be slowed down.",
    category: "Science",
    funLevel: 4,
    source: "Scientific American",
    tags: ["physics", "light", "quantum"],
    isVerified: true,
  },
  {
    id: 119,
    fact: "High-heeled shoes were originally worn by male soldiers in Persia.",
    category: "History",
    funLevel: 4,
    source: "History Channel",
    tags: ["fashion", "military", "history"],
    isVerified: true,
  },
  {
    id: 120,
    fact: "The 'five-second rule' for dropped food is a myth.",
    category: "Science",
    funLevel: 2,
    source: "Discovery",
    tags: ["food", "myth", "bacteria"],
    isVerified: true,
  },
  {
    id: 121,
    fact: "The hashtag symbol (#) is technically called an 'octothorpe'.",
    category: "Technology",
    funLevel: 4,
    source: "Britannica",
    tags: ["language", "symbols", "internet"],
    isVerified: true,
  },
  {
    id: 122,
    fact: "A group of porcupines is called a 'prickle'.",
    category: "Animals",
    funLevel: 5,
    source: "Discovery",
    tags: ["mammals", "language", "groups"],
    isVerified: true,
  },
  {
    id: 123,
    fact: "The longest traffic jam in history lasted for 12 days.",
    category: "Culture",
    funLevel: 3,
    source: "Guinness World Records",
    tags: ["transportation", "china", "records"],
    isVerified: true,
  },
  {
    id: 124,
    fact: "The largest volcano in the solar system is Olympus Mons on Mars.",
    category: "Space",
    funLevel: 3,
    source: "NASA",
    tags: ["mars", "volcanoes", "geology"],
    isVerified: true,
  },
  {
    id: 125,
    fact: "Dragonflies have six legs but cannot walk.",
    category: "Animals",
    funLevel: 3,
    source: "Smithsonian",
    tags: ["insects", "biology", "evolution"],
    isVerified: true,
  },
  {
    id: 126,
    fact: "In 1889, the Queen of Italy, Margherita, ordered the first pizza delivery.",
    category: "History",
    funLevel: 4,
    source: "History Channel",
    tags: ["food", "italy", "royalty"],
    isVerified: true,
  },
  {
    id: 127,
    fact: "There is a planet made almost entirely of diamond.",
    category: "Space",
    funLevel: 5,
    source: "NASA",
    tags: ["exoplanets", "astronomy", "planets"],
    isVerified: true,
  },
  {
    id: 128,
    fact: "The 'blood' in a 'blood orange' is due to antioxidants called anthocyanins.",
    category: "Nature",
    funLevel: 2,
    source: "Britannica",
    tags: ["fruit", "chemistry", "food"],
    isVerified: true,
  },
  {
    id: 129,
    fact: "The world's largest pyramid is not in Egypt, but in Mexico.",
    category: "History",
    funLevel: 4,
    source: "Smithsonian",
    tags: ["archaeology", "mexico", "architecture"],
    isVerified: true,
  },
  {
    id: 130,
    fact: "A 'baker's dozen' is 13, historically to avoid fines for shortchanging.",
    category: "Culture",
    funLevel: 3,
    source: "History Channel",
    tags: ["food", "history", "language"],
    isVerified: true,
  },
  {
    id: 131,
    fact: "The word 'disaster' means 'bad star' in Greek, referring to astrology.",
    category: "Culture",
    funLevel: 3,
    source: "Britannica",
    tags: ["language", "etymology", "astrology"],
    isVerified: true,
  },
  {
    id: 132,
    fact: "The average person walks the equivalent of three times around the world in their lifetime.",
    category: "Science",
    funLevel: 3,
    source: "BBC",
    tags: ["health", "statistics", "humans"],
    isVerified: true,
  },
  {
    id: 133,
    fact: "Turkeys can blush when they are excited or agitated.",
    category: "Animals",
    funLevel: 3,
    source: "Discovery",
    tags: ["birds", "biology", "emotions"],
    isVerified: true,
  },
  {
    id: 134,
    fact: "The first airbags in cars were designed to be deployed in 1/40th of a second.",
    category: "Technology",
    funLevel: 2,
    source: "History Channel",
    tags: ["cars", "safety", "engineering"],
    isVerified: true,
  },
  {
    id: 135,
    fact: "The 'click' sound you hear when you turn on a light switch is the sound of a tiny electrical arc.",
    category: "Science",
    funLevel: 3,
    source: "Scientific American",
    tags: ["physics", "electricity", "sound"],
    isVerified: true,
  },
  {
    id: 136,
    fact: "The human body contains enough carbon to make 9,000 pencils.",
    category: "Science",
    funLevel: 3,
    source: "Discovery",
    tags: ["biology", "chemistry", "humans"],
    isVerified: true,
  },
  {
    id: 137,
    fact: "The loudest sound ever recorded was the 1883 eruption of Krakatoa.",
    category: "Nature",
    funLevel: 4,
    source: "Scientific American",
    tags: ["volcanoes", "sound", "history"],
    isVerified: true,
  },
  {
    id: 138,
    fact: "The state of Oregon has a two-sided state flag, the only one in the U.S.",
    category: "Culture",
    funLevel: 3,
    source: "Britannica",
    tags: ["usa", "flags", "geography"],
    isVerified: true,
  },
  {
    id: 139,
    fact: "The world's oldest functional prosthetic limb is a 3,000-year-old wooden toe from Egypt.",
    category: "History",
    funLevel: 4,
    source: "Smithsonian",
    tags: ["archaeology", "egypt", "medicine"],
    isVerified: true,
  },
  {
    id: 140,
    fact: "The 'T-shirt' got its name from its 'T' shape.",
    category: "Culture",
    funLevel: 1,
    source: "Britannica",
    tags: ["fashion", "language", "history"],
    isVerified: true,
  },
  {
    id: 141,
    fact: "The 'butterfly' stroke in swimming was invented in the 1930s as a variation of the breaststroke.",
    category: "Culture",
    funLevel: 2,
    source: "Britannica",
    tags: ["sports", "swimming", "history"],
    isVerified: true,
  },
  {
    id: 142,
    fact: "The Great Smog of London in 1952 killed an estimated 12,000 people.",
    category: "History",
    funLevel: 3,
    source: "History Channel",
    tags: ["london", "environment", "disaster"],
    isVerified: true,
  },
  {
    id: 143,
    fact: "A group of crows is called a 'murder'.",
    category: "Animals",
    funLevel: 4,
    source: "Smithsonian",
    tags: ["birds", "language", "groups"],
    isVerified: true,
  },
  {
    id: 144,
    fact: "The original 'Monopoly' game board was circular.",
    category: "Culture",
    funLevel: 2,
    source: "Smithsonian",
    tags: ["games", "history", "design"],
    isVerified: true,
  },
  {
    id: 145,
    fact: "The Voyager 1 probe, launched in 1977, is the most distant human-made object from Earth.",
    category: "Space",
    funLevel: 4,
    source: "NASA",
    tags: ["space exploration", "technology", "records"],
    isVerified: true,
  },
  {
    id: 146,
    fact: "The 'brain freeze' sensation is scientifically called 'sphenopalatine ganglioneuralgia'.",
    category: "Science",
    funLevel: 4,
    source: "Scientific American",
    tags: ["biology", "pain", "terminology"],
    isVerified: true,
  },
  {
    id: 147,
    fact: "The first video game console was the Magnavox Odyssey, released in 1972.",
    category: "Technology",
    funLevel: 2,
    source: "Smithsonian",
    tags: ["gaming", "history", "electronics"],
    isVerified: true,
  },
  {
    id: 148,
    fact: "A 'sonic boom' is the sound of an object breaking the sound barrier.",
    category: "Science",
    funLevel: 2,
    source: "NASA",
    tags: ["physics", "sound", "aviation"],
    isVerified: true,
  },
  {
    id: 149,
    fact: "The largest known star, UY Scuti, is so large that 5 billion 'Suns' could fit inside it.",
    category: "Space",
    funLevel: 5,
    source: "Discovery",
    tags: ["stars", "astronomy", "scale"],
    isVerified: true,
  },
  {
    id: 150,
    fact: "The '@' symbol was chosen for email addresses by Ray Tomlinson in 1971 to separate the user from the host.",
    category: "Technology",
    funLevel: 3,
    source: "Britannica",
    tags: ["email", "internet", "history"],
    isVerified: true,
  },
  {
    id: 151,
    fact: "Opossums have 50 teeth, more than any other North American mammal.",
    category: "Animals",
    funLevel: 3,
    source: "National Geographic",
    tags: ["mammals", "anatomy", "teeth"],
    isVerified: true,
  },
  {
    id: 152,
    fact: "The 'S' in 'Harry S. Truman' doesn't stand for anything.",
    category: "History",
    funLevel: 3,
    source: "Smithsonian",
    tags: ["usa", "presidents", "names"],
    isVerified: true,
  },
  {
    id: 153,
    fact: "The bubbles in a glass of Guinness beer sink rather than rise.",
    category: "Science",
    funLevel: 4,
    source: "Scientific American",
    tags: ["physics", "fluid dynamics", "beer"],
    isVerified: true,
  },
  {
    id: 154,
    fact: "The word 'mortgage' comes from a French term meaning 'death pledge'.",
    category: "Culture",
    funLevel: 4,
    source: "Britannica",
    tags: ["language", "etymology", "finance"],
    isVerified: true,
  },
  {
    id: 155,
    fact: "Aplatypus is one of the few mammals that lay eggs.",
    category: "Animals",
    funLevel: 3,
    source: "National Geographic",
    tags: ["mammals", "australia", "evolution"],
    isVerified: true,
  },
  {
    id: 156,
    fact: "The metal loop for your belt on a pair of jeans is called a 'belt loop'.",
    category: "Culture",
    funLevel: 1,
    source: "Britannica",
    tags: ["fashion", "clothing", "language"],
    isVerified: true,
  },
  {
    id: 157,
    fact: "The Amazon rainforest produces 20% of the world's oxygen.",
    category: "Nature",
    funLevel: 3,
    source: "National Geographic",
    tags: ["environment", "trees", "amazon"],
    isVerified: true,
  },
  {
    id: 158,
    fact: "The first text message ever sent (in 1992) said 'Merry Christmas'.",
    category: "Technology",
    funLevel: 3,
    source: "BBC",
    tags: ["phones", "communication", "history"],
    isVerified: true,
  },
  {
    id: 159,
    fact: "A 'parsec' is a unit of distance used in astronomy, equal to 3.26 light-years.",
    category: "Space",
    funLevel: 2,
    source: "NASA",
    tags: ["measurement", "astronomy", "star wars"],
    isVerified: true,
  },
  {
    id: 160,
    fact: "In 1961, the Soviet Union sent a 'dummy' astronaut into space before Yuri Gagarin, complete with a tape recording.",
    category: "Space",
    funLevel: 4,
    source: "Smithsonian",
    tags: ["space race", "history", "ussr"],
    isVerified: true,
  },
  {
    id: 161,
    fact: "Sloths can swim three times faster than they can move on land.",
    category: "Animals",
    funLevel: 4,
    source: "National Geographic",
    tags: ["mammals", "sloth", "swimming"],
    isVerified: true,
  },
  {
    id: 162,
    fact: "The country of Finland has the most heavy metal bands per capita.",
    category: "Culture",
    funLevel: 3,
    source: "BBC",
    tags: ["music", "finland", "statistics"],
    isVerified: true,
  },
  {
    id: 163,
    fact: "The 'New Car Smell' is the scent of volatile organic compounds (VOCs) off-gassing.",
    category: "Science",
    funLevel: 2,
    source: "Scientific American",
    tags: ["chemistry", "cars", "scent"],
    isVerified: true,
  },
  {
    id: 164,
    fact: "The word 'robot' comes from the Czech word 'robota', meaning 'forced labor'.",
    category: "Technology",
    funLevel: 3,
    source: "Britannica",
    tags: ["robots", "language", "etymology"],
    isVerified: true,
  },
  {
    id: 165,
    fact: "In 17th century Netherlands, 'Tulip Mania' caused tulip bulbs to be worth more than houses.",
    category: "History",
    funLevel: 4,
    source: "History Channel",
    tags: ["economics", "flowers", "history"],
    isVerified: true,
  },
  {
    id: 166,
    fact: "The electric chair was invented by a dentist.",
    category: "History",
    funLevel: 4,
    source: "History Channel",
    tags: ["inventions", "death", "usa"],
    isVerified: true,
  },
  {
    id: 167,
    fact: "A woodpecker's tongue wraps around its brain to protect it while pecking.",
    category: "Animals",
    funLevel: 5,
    source: "National Geographic",
    tags: ["birds", "anatomy", "evolution"],
    isVerified: true,
  },
  {
    id: 168,
    fact: "The metallic taste you get when you touch metal is not the metal, but your own skin oils reacting.",
    category: "Science",
    funLevel: 3,
    source: "Scientific American",
    tags: ["chemistry", "senses", "biology"],
    isVerified: true,
  },
  {
    id: 169,
    fact: "The 'Windy City' nickname for Chicago originally referred to its politicians, not the weather.",
    category: "Culture",
    funLevel: 3,
    source: "History Channel",
    tags: ["usa", "chicago", "language"],
    isVerified: true,
  },
  {
    id: 170,
    fact: "The LEGO company is the world's largest manufacturer of tires.",
    category: "Technology",
    funLevel: 4,
    source: "Guinness World Records",
    tags: ["toys", "lego", "manufacturing"],
    isVerified: true,
  },
  {
    id: 171,
    fact: "Snails can sleep for up to three years.",
    category: "Animals",
    funLevel: 4,
    source: "Discovery",
    tags: ["mollusks", "biology", "sleep"],
    isVerified: true,
  },
  {
    id: 172,
    fact: "The Mariana Trench is so deep that if Mount Everest were placed in it, its peak would be over a mile underwater.",
    category: "Nature",
    funLevel: 4,
    source: "National Geographic",
    tags: ["ocean", "geography", "scale"],
    isVerified: true,
  },
  {
    id: 173,
    fact: "The 'Big Bang' theory was first proposed by a Catholic priest, Georges Lemaître.",
    category: "Science",
    funLevel: 3,
    source: "NASA",
    tags: ["physics", "cosmology", "history"],
    isVerified: true,
  },
  {
    id: 174,
    fact: "The state of California has an official state dinosaur.",
    category: "Culture",
    funLevel: 3,
    source: "Discovery",
    tags: ["usa", "california", "dinosaurs"],
    isVerified: true,
  },
  {
    id: 175,
    fact: "Australia was once home to 'mega-wombats' the size of a rhinoceros.",
    category: "History",
    funLevel: 4,
    source: "Smithsonian",
    tags: ["paleontology", "australia", "animals"],
    isVerified: true,
  },
  {
    id: 176,
    fact: "You cannot taste food until it is mixed with saliva.",
    category: "Science",
    funLevel: 3,
    source: "BBC",
    tags: ["biology", "senses", "food"],
    isVerified: true,
  },
  {
    id: 177,
    fact: "The 'pound' key (#) on a phone is also called an 'octothorpe'.",
    category: "Technology",
    funLevel: 4,
    source: "Britannica",
    tags: ["phones", "language", "symbols"],
    isVerified: true,
  },
  {
    id: 178,
    fact: "A cat's 'meow' is a behavior developed almost exclusively to communicate with humans.",
    category: "Animals",
    funLevel: 4,
    source: "Smithsonian",
    tags: ["cats", "behavior", "communication"],
    isVerified: true,
  },
  {
    id: 179,
    fact: "The word 'clue' comes from 'clew', a ball of thread, which Theseus used to escape the labyrinth.",
    category: "Culture",
    funLevel: 4,
    source: "Britannica",
    tags: ["language", "etymology", "mythology"],
    isVerified: true,
  },
  {
    id: 180,
    fact: "The International Space Station (ISS) travels at 17,000 mph (27,000 km/h).",
    category: "Space",
    funLevel: 3,
    source: "NASA",
    tags: ["iss", "space exploration", "speed"],
    isVerified: true,
  },
  {
    id: 181,
    fact: "The 'Pacific' Ocean is named for being 'peaceful', which Ferdinand Magellan found it to be.",
    category: "History",
    funLevel: 2,
    source: "Britannica",
    tags: ["geography", "exploration", "language"],
    isVerified: true,
  },
  {
    id: 182,
    fact: "There is a 1,600-year-old 'Lycurgus Cup' that changes color (red/green) depending on the light.",
    category: "History",
    funLevel: 5,
    source: "Smithsonian",
    tags: ["rome", "nanotechnology", "art"],
    isVerified: true,
  },
  {
    id: 183,
    fact: "A 20-second hug releases oxytocin, which helps you trust the person you are hugging.",
    category: "Science",
    funLevel: 3,
    source: "BBC",
    tags: ["biology", "psychology", "hormones"],
    isVerified: true,
  },
  {
    id: 184,
    fact: "The cornea is the only part of the human body with no blood supply; it gets oxygen directly from the air.",
    category: "Science",
    funLevel: 4,
    source: "Scientific American",
    tags: ["biology", "anatomy", "eyes"],
    isVerified: true,
  },
  {
    id: 185,
    fact: "Elephants are the only animals that cannot jump.",
    category: "Animals",
    funLevel: 3,
    source: "Discovery",
    tags: ["mammals", "elephants", "biology"],
    isVerified: true,
  },
  {
    id: 186,
    fact: "The first 'webcam' was invented at Cambridge University to monitor a coffee pot.",
    category: "Technology",
    funLevel: 4,
    source: "BBC",
    tags: ["inventions", "internet", "computing"],
    isVerified: true,
  },
  {
    id: 187,
    fact: "Sharks existed before trees.",
    category: "Nature",
    funLevel: 5,
    source: "Discovery",
    tags: ["evolution", "paleontology", "time"],
    isVerified: true,
  },
  {
    id: 188,
    fact: "The 'SMS' in 'SMS text message' stands for 'Short Message Service'.",
    category: "Technology",
    funLevel: 1,
    source: "Britannica",
    tags: ["phones", "language", "acronyms"],
    isVerified: true,
  },
  {
    id: 189,
    fact: "Finland has a 'National Sleepy Head Day' where the last person in a family to wake up is thrown into water.",
    category: "Culture",
    funLevel: 4,
    source: "BBC",
    tags: ["finland", "tradition", "holidays"],
    isVerified: true,
  },
  {
    id: 190,
    fact: "The Andromeda Galaxy is approaching the Milky Way at 250,000 mph (110 km/s).",
    category: "Space",
    funLevel: 3,
    source: "NASA",
    tags: ["galaxy", "astronomy", "physics"],
    isVerified: true,
  },
  {
    id: 191,
    fact: "The 'Caesar' salad is not named after Julius Caesar, but after its inventor, Caesar Cardini.",
    category: "Culture",
    funLevel: 3,
    source: "History Channel",
    tags: ["food", "history", "names"],
    isVerified: true,
  },
  {
    id: 192,
    fact: "A tarantula can shoot its barbed hairs at attackers.",
    category: "Animals",
    funLevel: 4,
    source: "National Geographic",
    tags: ["spiders", "defense", "biology"],
    isVerified: true,
  },
  {
    id: 193,
    fact: "Before the 19th century, dentures were commonly made from the teeth of dead soldiers.",
    category: "History",
    funLevel: 5,
    source: "Smithsonian",
    tags: ["medicine", "history", "war"],
    isVerified: true,
  },
  {
    id: 194,
    fact: "The 'save' icon in most software is a picture of a floppy disk, which many users have never seen.",
    category: "Technology",
    funLevel: 3,
    source: "Smithsonian",
    tags: ["design", "ui", "history"],
    isVerified: true,
  },
  {
    id: 195,
    fact: "Bubble wrap was originally invented as a form of textured 3D wallpaper.",
    category: "Technology",
    funLevel: 4,
    source: "Smithsonian",
    tags: ["inventions", "design", "history"],
    isVerified: true,
  },
  {
    id: 196,
    fact: "The inventor of the Pringles can had his ashes buried in one.",
    category: "Culture",
    funLevel: 5,
    source: "History Channel",
    tags: ["food", "death", "weird"],
    isVerified: true,
  },
  {
    id: 197,
    fact: "The 'E' in 'e-mail' stands for 'electronic'.",
    category: "Technology",
    funLevel: 1,
    source: "Britannica",
    tags: ["email", "language", "internet"],
    isVerified: true,
  },
  {
    id: 198,
    fact: "The 'Bluetooth' wireless technology is named after a 10th-century Viking king, Harald Bluetooth.",
    category: "Technology",
    funLevel: 4,
    source: "BBC",
    tags: ["naming", "history", "vikings"],
    isVerified: true,
  },
  {
    id: 199,
    fact: "There is an 'earthquake-proof' table designed to protect students during an earthquake.",
    category: "Technology",
    funLevel: 3,
    source: "Discovery",
    tags: ["safety", "engineering", "inventions"],
    isVerified: true,
  },
  {
    id: 200,
    fact: "The average human body contains enough iron to make a 3-inch (7.6 cm) nail.",
    category: "Science",
    funLevel: 3,
    source: "Scientific American",
    tags: ["biology", "chemistry", "humans"],
    isVerified: true,
  },
];
