import type { Quote } from "@/types";

export const quotes: Quote[] = [
  {
    id: 1,
    content: "The secret of getting ahead is getting started.",
    author: "Mark Twain",
    category: "Motivation",
    tags: ["action", "beginnings"],
    popularity: 4.8,
  },
  {
    id: 2,
    content: "The only true wisdom is in knowing you know nothing.",
    author: "Socrates",
    category: "Wisdom",
    tags: ["humility", "knowledge"],
    popularity: 4.9,
  },
  {
    id: 3,
    content: "The purpose of our lives is to be happy.",
    author: "Dalai Lama",
    category: "Life",
    tags: ["happiness", "purpose"],
    popularity: 4.7,
  },
  {
    id: 4,
    content:
      "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
    category: "Success",
    tags: ["resilience", "perseverance"],
    popularity: 5.0,
  },
  {
    id: 5,
    content: "The best thing to hold onto in life is each other.",
    author: "Audrey Hepburn",
    category: "Love",
    tags: ["relationships", "connection"],
    popularity: 4.8,
  },
  {
    id: 6,
    content: "It takes courage to grow up and become who you really are.",
    author: "E.E. Cummings",
    category: "Courage",
    tags: ["identity", "growth"],
    popularity: 4.6,
  },
  {
    id: 7,
    content: "Imagination is more important than knowledge.",
    author: "Albert Einstein",
    category: "Imagination",
    tags: ["creativity", "intellect"],
    popularity: 5.0,
  },
  {
    id: 8,
    content: "An investment in knowledge pays the best interest.",
    author: "Benjamin Franklin",
    category: "Knowledge",
    tags: ["education", "learning"],
    popularity: 4.9,
  },
  {
    id: 9,
    content:
      "For every minute you are angry you lose sixty seconds of happiness.",
    author: "Ralph Waldo Emerson",
    category: "Happiness",
    tags: ["mindfulness", "emotions"],
    popularity: 4.7,
  },
  {
    id: 10,
    content: "It does not matter how slowly you go as long as you do not stop.",
    author: "Confucius",
    category: "Perseverance",
    tags: ["patience", "consistency"],
    popularity: 4.9,
  },
  {
    id: 11,
    content: "Don't watch the clock; do what it does. Keep going.",
    author: "Sam Levenson",
    category: "Motivation",
    tags: ["persistence", "focus"],
    popularity: 4.5,
  },
  {
    id: 12,
    content: "The journey of a thousand miles begins with a single step.",
    author: "Lao Tzu",
    category: "Wisdom",
    tags: ["beginnings", "action"],
    popularity: 5.0,
  },
  {
    id: 13,
    content: "Life is what happens when you're busy making other plans.",
    author: "John Lennon",
    category: "Life",
    tags: ["reality", "planning"],
    popularity: 4.9,
  },
  {
    id: 14,
    content:
      "The road to success and the road to failure are almost exactly the same.",
    author: "Colin R. Davis",
    category: "Success",
    tags: ["journey", "risk"],
    popularity: 4.6,
  },
  {
    id: 15,
    content: "To love and be loved is to feel the sun from both sides.",
    author: "David Viscott",
    category: "Love",
    tags: ["reciprocity", "joy"],
    popularity: 4.7,
  },
  {
    id: 16,
    content:
      "Courage is resistance to fear, mastery of fear - not absence of fear.",
    author: "Mark Twain",
    category: "Courage",
    tags: ["fear", "strength"],
    popularity: 4.9,
  },
  {
    id: 17,
    content:
      "Logic will get you from A to B. Imagination will take you everywhere.",
    author: "Albert Einstein",
    category: "Imagination",
    tags: ["creativity", "possibility"],
    popularity: 4.9,
  },
  {
    id: 18,
    content: "The only source of knowledge is experience.",
    author: "Albert Einstein",
    category: "Knowledge",
    tags: ["learning", "practice"],
    popularity: 4.8,
  },
  {
    id: 19,
    content:
      "Happiness is not something ready made. It comes from your own actions.",
    author: "Dalai Lama",
    category: "Happiness",
    tags: ["action", "choice"],
    popularity: 4.8,
  },
  {
    id: 20,
    content: "Perseverance is failing 19 times and succeeding the 20th.",
    author: "Julie Andrews",
    category: "Perseverance",
    tags: ["resilience", "failure"],
    popularity: 4.7,
  },
  {
    id: 21,
    content: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Motivation",
    tags: ["passion", "work"],
    popularity: 5.0,
  },
  {
    id: 22,
    content:
      "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.",
    author: "Rumi",
    category: "Wisdom",
    tags: ["self-improvement", "perspective"],
    popularity: 5.0,
  },
  {
    id: 23,
    content: "Get busy living or get busy dying.",
    author: "Stephen King",
    category: "Life",
    tags: ["action", "purpose"],
    popularity: 4.7,
  },
  {
    id: 24,
    content: "I have not failed. I've just found 10,000 ways that won't work.",
    author: "Thomas A. Edison",
    category: "Success",
    tags: ["failure", "perspective"],
    popularity: 4.9,
  },
  {
    id: 25,
    content: "Love is composed of a single soul inhabiting two bodies.",
    author: "Aristotle",
    category: "Love",
    tags: ["soulmates", "unity"],
    popularity: 4.8,
  },
  {
    id: 26,
    content:
      "All our dreams can come true, if we have the courage to pursue them.",
    author: "Walt Disney",
    category: "Courage",
    tags: ["dreams", "ambition"],
    popularity: 4.9,
  },
  {
    id: 27,
    content: "Imagination is the beginning of creation.",
    author: "George Bernard Shaw",
    category: "Imagination",
    tags: ["creation", "ideas"],
    popularity: 4.7,
  },
  {
    id: 28,
    content: "Knowledge is power.",
    author: "Francis Bacon",
    category: "Knowledge",
    tags: ["power", "information"],
    popularity: 5.0,
  },
  {
    id: 29,
    content: "Happiness depends upon ourselves.",
    author: "Aristotle",
    category: "Happiness",
    tags: ["responsibility", "mindset"],
    popularity: 4.6,
  },
  {
    id: 30,
    content:
      "A river cuts through rock, not because of its power, but because of its persistence.",
    author: "Jim Watkins",
    category: "Perseverance",
    tags: ["persistence", "strength"],
    popularity: 4.9,
  },
  {
    id: 31,
    content: "Believe you can and you're halfway there.",
    author: "Theodore Roosevelt",
    category: "Motivation",
    tags: ["belief", "confidence"],
    popularity: 4.9,
  },
  {
    id: 32,
    content: "Knowing yourself is the beginning of all wisdom.",
    author: "Aristotle",
    category: "Wisdom",
    tags: ["self-awareness", "introspection"],
    popularity: 4.8,
  },
  {
    id: 33,
    content: "You only live once, but if you do it right, once is enough.",
    author: "Mae West",
    category: "Life",
    tags: ["living-fully", "opportunity"],
    popularity: 4.8,
  },
  {
    id: 34,
    content:
      "Success usually comes to those who are too busy to be looking for it.",
    author: "Henry David Thoreau",
    category: "Success",
    tags: ["work-ethic", "focus"],
    popularity: 4.7,
  },
  {
    id: 35,
    content:
      "You know you're in love when you can't fall asleep because reality is finally better than your dreams.",
    author: "Dr. Seuss",
    category: "Love",
    tags: ["dreams", "reality"],
    popularity: 5.0,
  },
  {
    id: 36,
    content:
      "Courage is what it takes to stand up and speak; courage is also what it takes to sit down and listen.",
    author: "Winston Churchill",
    category: "Courage",
    tags: ["communication", "humility"],
    popularity: 4.8,
  },
  {
    id: 37,
    content: "Everything you can imagine is real.",
    author: "Pablo Picasso",
    category: "Imagination",
    tags: ["art", "reality"],
    popularity: 4.8,
  },
  {
    id: 38,
    content: "Real knowledge is to know the extent of one's ignorance.",
    author: "Confucius",
    category: "Knowledge",
    tags: ["humility", "awareness"],
    popularity: 4.9,
  },
  {
    id: 39,
    content:
      "The most important thing is to enjoy your life—to be happy—it's all that matters.",
    author: "Audrey Hepburn",
    category: "Happiness",
    tags: ["joy", "priorities"],
    popularity: 4.7,
  },
  {
    id: 40,
    content: "Fall seven times, stand up eight.",
    author: "Japanese Proverb",
    category: "Perseverance",
    tags: ["resilience", "determination"],
    popularity: 5.0,
  },
  {
    id: 41,
    content: "Act as if what you do makes a difference. It does.",
    author: "William James",
    category: "Motivation",
    tags: ["impact", "action"],
    popularity: 4.6,
  },
  {
    id: 42,
    content: "The wise man is one who knows what he does not know.",
    author: "Lao Tzu",
    category: "Wisdom",
    tags: ["self-awareness", "humility"],
    popularity: 4.7,
  },
  {
    id: 43,
    content: "Life is 10% what happens to us and 90% how we react to it.",
    author: "Charles R. Swindoll",
    category: "Life",
    tags: ["perspective", "attitude"],
    popularity: 4.9,
  },
  {
    id: 44,
    content: "Don't be afraid to give up the good to go for the great.",
    author: "John D. Rockefeller",
    category: "Success",
    tags: ["ambition", "risk"],
    popularity: 4.7,
  },
  {
    id: 45,
    content: "We are most alive when we're in love.",
    author: "John Updike",
    category: "Love",
    tags: ["vitality", "passion"],
    popularity: 4.5,
  },
  {
    id: 46,
    content:
      "He who is not courageous enough to take risks will accomplish nothing in life.",
    author: "Muhammad Ali",
    category: "Courage",
    tags: ["risk", "achievement"],
    popularity: 4.8,
  },
  {
    id: 47,
    content: "The man who has no imagination has no wings.",
    author: "Muhammad Ali",
    category: "Imagination",
    tags: ["potential", "limitation"],
    popularity: 4.6,
  },
  {
    id: 48,
    content: "Beware of false knowledge; it is more dangerous than ignorance.",
    author: "George Bernard Shaw",
    category: "Knowledge",
    tags: ["truth", "danger"],
    popularity: 4.7,
  },
  {
    id: 49,
    content: "If you want to be happy, be.",
    author: "Leo Tolstoy",
    category: "Happiness",
    tags: ["simplicity", "choice"],
    popularity: 4.8,
  },
  {
    id: 50,
    content:
      "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.",
    author: "Thomas A. Edison",
    category: "Perseverance",
    tags: ["determination", "success"],
    popularity: 4.9,
  },
  {
    id: 51,
    content:
      "The future belongs to those who believe in the beauty of their dreams.",
    author: "Eleanor Roosevelt",
    category: "Motivation",
    tags: ["dreams", "hope"],
    popularity: 4.9,
  },
  {
    id: 52,
    content:
      "It is the mark of an educated mind to be able to entertain a thought without accepting it.",
    author: "Aristotle",
    category: "Wisdom",
    tags: ["open-mindedness", "critical-thinking"],
    popularity: 5.0,
  },
  {
    id: 53,
    content:
      "In three words I can sum up everything I've learned about life: it goes on.",
    author: "Robert Frost",
    category: "Life",
    tags: ["resilience", "acceptance"],
    popularity: 4.8,
  },
  {
    id: 54,
    content:
      "Success is the sum of small efforts, repeated day-in and day-out.",
    author: "Robert Collier",
    category: "Success",
    tags: ["consistency", "habits"],
    popularity: 4.8,
  },
  {
    id: 55,
    content:
      "Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.",
    author: "Lao Tzu",
    category: "Love",
    tags: ["strength", "courage"],
    popularity: 4.9,
  },
  {
    id: 56,
    content: "Life shrinks or expands in proportion to one's courage.",
    author: "Anais Nin",
    category: "Courage",
    tags: ["growth", "fear"],
    popularity: 4.8,
  },
  {
    id: 57,
    content: "The world is but a canvas to our imagination.",
    author: "Henry David Thoreau",
    category: "Imagination",
    tags: ["perspective", "creation"],
    popularity: 4.7,
  },
  {
    id: 58,
    content:
      "The beautiful thing about learning is that no one can take it away from you.",
    author: "B.B. King",
    category: "Knowledge",
    tags: ["education", "empowerment"],
    popularity: 4.7,
  },
  {
    id: 59,
    content:
      "Folks are usually about as happy as they make their minds up to be.",
    author: "Abraham Lincoln",
    category: "Happiness",
    tags: ["mindset", "choice"],
    popularity: 4.6,
  },
  {
    id: 60,
    content: "Great works are performed not by strength but by perseverance.",
    author: "Samuel Johnson",
    category: "Perseverance",
    tags: ["effort", "achievement"],
    popularity: 4.6,
  },
  {
    id: 61,
    content: "Your time is limited, don't waste it living someone else's life.",
    author: "Steve Jobs",
    category: "Motivation",
    tags: ["authenticity", "purpose"],
    popularity: 4.9,
  },
  {
    id: 62,
    content:
      "The invariable mark of wisdom is to see the miraculous in the common.",
    author: "Ralph Waldo Emerson",
    category: "Wisdom",
    tags: ["wonder", "perspective"],
    popularity: 4.7,
  },
  {
    id: 63,
    content: "Life is really simple, but we insist on making it complicated.",
    author: "Confucius",
    category: "Life",
    tags: ["simplicity", "philosophy"],
    popularity: 4.8,
  },
  {
    id: 64,
    content:
      "The only place where success comes before work is in the dictionary.",
    author: "Vidal Sassoon",
    category: "Success",
    tags: ["work-ethic", "reality"],
    popularity: 4.8,
  },
  {
    id: 65,
    content: "Where there is love there is life.",
    author: "Mahatma Gandhi",
    category: "Love",
    tags: ["life", "essence"],
    popularity: 4.9,
  },
  {
    id: 66,
    content:
      "Courage doesn't always roar. Sometimes it's the quiet voice at the end of the day saying 'I will try again tomorrow.'",
    author: "Mary Anne Radmacher",
    category: "Courage",
    tags: ["resilience", "hope"],
    popularity: 5.0,
  },
  {
    id: 67,
    content:
      "Imagination will often carry us to worlds that never were. But without it, we go nowhere.",
    author: "Carl Sagan",
    category: "Imagination",
    tags: ["exploration", "progress"],
    popularity: 4.9,
  },
  {
    id: 68,
    content: "If you have knowledge, let others light their candles in it.",
    author: "Margaret Fuller",
    category: "Knowledge",
    tags: ["sharing", "teaching"],
    popularity: 4.7,
  },
  {
    id: 69,
    content:
      "The art of being happy lies in the power of extracting happiness from common things.",
    author: "Henry Ward Beecher",
    category: "Happiness",
    tags: ["gratitude", "perspective"],
    popularity: 4.6,
  },
  {
    id: 70,
    content: "I am a slow walker, but I never walk back.",
    author: "Abraham Lincoln",
    category: "Perseverance",
    tags: ["progress", "determination"],
    popularity: 4.8,
  },
  {
    id: 71,
    content: "It’s not whether you get knocked down, it’s whether you get up.",
    author: "Vince Lombardi",
    category: "Motivation",
    tags: ["resilience", "strength"],
    popularity: 4.9,
  },
  {
    id: 72,
    content: "Turn your wounds into wisdom.",
    author: "Oprah Winfrey",
    category: "Wisdom",
    tags: ["growth", "healing"],
    popularity: 4.7,
  },
  {
    id: 73,
    content:
      "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    author: "Nelson Mandela",
    category: "Life",
    tags: ["resilience", "strength"],
    popularity: 5.0,
  },
  {
    id: 74,
    content:
      "Try not to become a man of success. Rather become a man of value.",
    author: "Albert Einstein",
    category: "Success",
    tags: ["value", "character"],
    popularity: 4.9,
  },
  {
    id: 75,
    content: "There is only one happiness in this life, to love and be loved.",
    author: "George Sand",
    category: "Love",
    tags: ["happiness", "connection"],
    popularity: 4.8,
  },
  {
    id: 76,
    content:
      "The secret to happiness is freedom... And the secret to freedom is courage.",
    author: "Thucydides",
    category: "Courage",
    tags: ["freedom", "happiness"],
    popularity: 4.7,
  },
  {
    id: 77,
    content:
      "Laughter is timeless, imagination has no age, and dreams are forever.",
    author: "Walt Disney",
    category: "Imagination",
    tags: ["joy", "dreams"],
    popularity: 4.8,
  },
  {
    id: 78,
    content: "Knowledge is of no value unless you put it into practice.",
    author: "Anton Chekhov",
    category: "Knowledge",
    tags: ["action", "application"],
    popularity: 4.6,
  },
  {
    id: 79,
    content:
      "Happiness is when what you think, what you say, and what you do are in harmony.",
    author: "Mahatma Gandhi",
    category: "Happiness",
    tags: ["integrity", "harmony"],
    popularity: 4.9,
  },
  {
    id: 80,
    content:
      "Let me tell you the secret that has led me to my goal. My strength lies solely in my tenacity.",
    author: "Louis Pasteur",
    category: "Perseverance",
    tags: ["tenacity", "strength"],
    popularity: 4.7,
  },
  {
    id: 81,
    content: "The way to get started is to quit talking and begin doing.",
    author: "Walt Disney",
    category: "Motivation",
    tags: ["action", "procrastination"],
    popularity: 4.8,
  },
  {
    id: 82,
    content: "The quieter you become, the more you are able to hear.",
    author: "Rumi",
    category: "Wisdom",
    tags: ["mindfulness", "listening"],
    popularity: 4.9,
  },
  {
    id: 83,
    content:
      "Life is like riding a bicycle. To keep your balance, you must keep moving.",
    author: "Albert Einstein",
    category: "Life",
    tags: ["balance", "progress"],
    popularity: 5.0,
  },
  {
    id: 84,
    content:
      "Success is liking yourself, liking what you do, and liking how you do it.",
    author: "Maya Angelou",
    category: "Success",
    tags: ["self-love", "fulfillment"],
    popularity: 4.8,
  },
  {
    id: 85,
    content: "Love is a friendship set to music.",
    author: "Joseph Campbell",
    category: "Love",
    tags: ["friendship", "harmony"],
    popularity: 4.6,
  },
  {
    id: 86,
    content: "Courage is knowing what not to fear.",
    author: "Plato",
    category: "Courage",
    tags: ["fear", "wisdom"],
    popularity: 4.7,
  },
  {
    id: 87,
    content: "To invent, you need a good imagination and a pile of junk.",
    author: "Thomas A. Edison",
    category: "Imagination",
    tags: ["invention", "resourcefulness"],
    popularity: 4.6,
  },
  {
    id: 88,
    content: "The love of knowledge is a kind of madness.",
    author: "C.S. Lewis",
    category: "Knowledge",
    tags: ["passion", "learning"],
    popularity: 4.4,
  },
  {
    id: 89,
    content: "There is no path to happiness: happiness is the path.",
    author: "Buddha",
    category: "Happiness",
    tags: ["journey", "mindfulness"],
    popularity: 4.9,
  },
  {
    id: 90,
    content:
      "Many of life's failures are people who did not realize how close they were to success when they gave up.",
    author: "Thomas A. Edison",
    category: "Perseverance",
    tags: ["failure", "opportunity"],
    popularity: 4.9,
  },
  {
    id: 91,
    content:
      "I am not a product of my circumstances. I am a product of my my decisions.",
    author: "Stephen Covey",
    category: "Motivation",
    tags: ["choice", "responsibility"],
    popularity: 4.8,
  },
  {
    id: 92,
    content:
      "A fool thinks himself to be wise, but a wise man knows himself to be a fool.",
    author: "William Shakespeare",
    category: "Wisdom",
    tags: ["humility", "self-awareness"],
    popularity: 4.9,
  },
  {
    id: 93,
    content: "Life is either a daring adventure or nothing at all.",
    author: "Helen Keller",
    category: "Life",
    tags: ["adventure", "risk"],
    popularity: 4.9,
  },
  {
    id: 94,
    content:
      "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack of will.",
    author: "Vince Lombardi",
    category: "Success",
    tags: ["willpower", "determination"],
    popularity: 4.8,
  },
  {
    id: 95,
    content: "The giving of love is an education in itself.",
    author: "Eleanor Roosevelt",
    category: "Love",
    tags: ["giving", "learning"],
    popularity: 4.5,
  },
  {
    id: 96,
    content:
      "Without courage, we cannot practice any other virtue with consistency.",
    author: "Maya Angelou",
    category: "Courage",
    tags: ["virtue", "strength"],
    popularity: 4.8,
  },
  {
    id: 97,
    content: "Imagination is the only weapon in the war against reality.",
    author: "Lewis Carroll",
    category: "Imagination",
    tags: ["reality", "escapism"],
    popularity: 4.7,
  },
  {
    id: 98,
    content:
      "For the things we have to learn before we can do them, we learn by doing them.",
    author: "Aristotle",
    category: "Knowledge",
    tags: ["practice", "experience"],
    popularity: 4.7,
  },
  {
    id: 99,
    content:
      "The secret of happiness is not in doing what one likes, but in liking what one does.",
    author: "J.M. Barrie",
    category: "Happiness",
    tags: ["fulfillment", "attitude"],
    popularity: 4.6,
  },
  {
    id: 100,
    content:
      "Permanence, perseverance and persistence in spite of all obstacles, discouragements, and impossibilities: It is this that in all things distinguishes the strong soul from the weak.",
    author: "Thomas Carlyle",
    category: "Perseverance",
    tags: ["strength", "mindset"],
    popularity: 4.7,
  },
  {
    id: 101,
    content:
      "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    author: "Zig Ziglar",
    category: "Motivation",
    tags: ["growth", "journey"],
    popularity: 4.7,
  },
  {
    id: 102,
    content: "Be happy for this moment. This moment is your life.",
    author: "Omar Khayyam",
    category: "Wisdom",
    tags: ["mindfulness", "presence"],
    popularity: 4.6,
  },
  {
    id: 103,
    content:
      "You will face many defeats in life, but never let yourself be defeated.",
    author: "Maya Angelou",
    category: "Life",
    tags: ["resilience", "strength"],
    popularity: 4.9,
  },
  {
    id: 104,
    content:
      "Ambition is the path to success. Persistence is the vehicle you arrive in.",
    author: "Bill Bradley",
    category: "Success",
    tags: ["ambition", "persistence"],
    popularity: 4.6,
  },
  {
    id: 105,
    content: "Love does not dominate; it cultivates.",
    author: "Johann Wolfgang von Goethe",
    category: "Love",
    tags: ["growth", "respect"],
    popularity: 4.5,
  },
  {
    id: 106,
    content: "Fear is a reaction. Courage is a decision.",
    author: "Winston Churchill",
    category: "Courage",
    tags: ["choice", "mindset"],
    popularity: 4.8,
  },
  {
    id: 107,
    content: "The power of imagination makes us infinite.",
    author: "John Muir",
    category: "Imagination",
    tags: ["potential", "creativity"],
    popularity: 4.7,
  },
  {
    id: 108,
    content:
      "The goal of education is the advancement of knowledge and the dissemination of truth.",
    author: "John F. Kennedy",
    category: "Knowledge",
    tags: ["education", "truth"],
    popularity: 4.6,
  },
  {
    id: 109,
    content:
      "We tend to forget that happiness doesn't come as a result of getting something we don't have, but rather of recognizing and appreciating what we do have.",
    author: "Frederick Keonig",
    category: "Happiness",
    tags: ["gratitude", "perspective"],
    popularity: 4.7,
  },
  {
    id: 110,
    content:
      "It's not that I'm so smart, it's just that I stay with problems longer.",
    author: "Albert Einstein",
    category: "Perseverance",
    tags: ["problem-solving", "patience"],
    popularity: 4.9,
  },
  {
    id: 111,
    content:
      "The only limit to our realization of tomorrow will be our doubts of today.",
    author: "Franklin D. Roosevelt",
    category: "Motivation",
    tags: ["doubt", "potential"],
    popularity: 4.8,
  },
  {
    id: 112,
    content:
      "We can't solve problems by using the same kind of thinking we used when we created them.",
    author: "Albert Einstein",
    category: "Wisdom",
    tags: ["innovation", "problem-solving"],
    popularity: 5.0,
  },
  {
    id: 113,
    content:
      "To live is the rarest thing in the world. Most people exist, that is all.",
    author: "Oscar Wilde",
    category: "Life",
    tags: ["living-fully", "existence"],
    popularity: 4.9,
  },
  {
    id: 114,
    content:
      "Success is getting what you want, happiness is wanting what you get.",
    author: "W. P. Kinsella",
    category: "Success",
    tags: ["happiness", "fulfillment"],
    popularity: 4.7,
  },
  {
    id: 115,
    content: "Love isn't something you find. Love is something that finds you.",
    author: "Loretta Young",
    category: "Love",
    tags: ["fate", "destiny"],
    popularity: 4.6,
  },
  {
    id: 116,
    content: "Courage is grace under pressure.",
    author: "Ernest Hemingway",
    category: "Courage",
    tags: ["composure", "strength"],
    popularity: 4.8,
  },
  {
    id: 117,
    content: "Imagination governs the world.",
    author: "Napoleon Bonaparte",
    category: "Imagination",
    tags: ["power", "influence"],
    popularity: 4.6,
  },
  {
    id: 118,
    content:
      "The beginning of knowledge is the discovery of something we do not understand.",
    author: "Frank Herbert",
    category: "Knowledge",
    tags: ["curiosity", "discovery"],
    popularity: 4.5,
  },
  {
    id: 119,
    content: "Happiness is a direction, not a place.",
    author: "Sydney J. Harris",
    category: "Happiness",
    tags: ["journey", "process"],
    popularity: 4.5,
  },
  {
    id: 120,
    content: "Energy and persistence conquer all things.",
    author: "Benjamin Franklin",
    category: "Perseverance",
    tags: ["energy", "persistence"],
    popularity: 4.7,
  },
  {
    id: 121,
    content: "Great things never come from comfort zones.",
    author: "Anonymous",
    category: "Motivation",
    tags: ["challenge", "growth"],
    popularity: 4.7,
  },
  {
    id: 122,
    content: "The past has no power over the present moment.",
    author: "Eckhart Tolle",
    category: "Wisdom",
    tags: ["mindfulness", "letting-go"],
    popularity: 4.8,
  },
  {
    id: 123,
    content: "The unexamined life is not worth living.",
    author: "Socrates",
    category: "Life",
    tags: ["introspection", "philosophy"],
    popularity: 5.0,
  },
  {
    id: 124,
    content: "I find that the harder I work, the more luck I seem to have.",
    author: "Thomas Jefferson",
    category: "Success",
    tags: ["work-ethic", "luck"],
    popularity: 4.8,
  },
  {
    id: 125,
    content: "Life is the flower for which love is the honey.",
    author: "Victor Hugo",
    category: "Love",
    tags: ["metaphor", "sweetness"],
    popularity: 4.6,
  },
  {
    id: 126,
    content:
      "You cannot swim for new horizons until you have courage to lose sight of the shore.",
    author: "William Faulkner",
    category: "Courage",
    tags: ["risk", "exploration"],
    popularity: 4.8,
  },
  {
    id: 127,
    content: "What is now proved was once only imagined.",
    author: "William Blake",
    category: "Imagination",
    tags: ["progress", "vision"],
    popularity: 4.7,
  },
  {
    id: 128,
    content: "Zeal without knowledge is fire without light.",
    author: "Thomas Fuller",
    category: "Knowledge",
    tags: ["wisdom", "passion"],
    popularity: 4.4,
  },
  {
    id: 129,
    content:
      "There is only one way to happiness and that is to cease worrying about things which are beyond the power of our will.",
    author: "Epictetus",
    category: "Happiness",
    tags: ["stoicism", "acceptance"],
    popularity: 4.8,
  },
  {
    id: 130,
    content:
      "Never give up on a dream just because of the time it will take to accomplish it. The time will pass anyway.",
    author: "Earl Nightingale",
    category: "Perseverance",
    tags: ["dreams", "time"],
    popularity: 4.9,
  },
  {
    id: 131,
    content: "Success doesn't just find you. You have to go out and get it.",
    author: "Anonymous",
    category: "Motivation",
    tags: ["action", "hustle"],
    popularity: 4.6,
  },
  {
    id: 132,
    content:
      "Wisdom is not a product of schooling but of the lifelong attempt to acquire it.",
    author: "Albert Einstein",
    category: "Wisdom",
    tags: ["lifelong-learning", "experience"],
    popularity: 4.8,
  },
  {
    id: 133,
    content:
      "Life is not a problem to be solved, but a reality to be experienced.",
    author: "Soren Kierkegaard",
    category: "Life",
    tags: ["experience", "philosophy"],
    popularity: 4.7,
  },
  {
    id: 134,
    content:
      "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.",
    author: "Colin Powell",
    category: "Success",
    tags: ["preparation", "hard-work"],
    popularity: 4.8,
  },
  {
    id: 135,
    content:
      "The greatest happiness of life is the conviction that we are loved; loved for ourselves, or rather, loved in spite of ourselves.",
    author: "Victor Hugo",
    category: "Love",
    tags: ["acceptance", "self-love"],
    popularity: 4.7,
  },
  {
    id: 136,
    content:
      "A man with outward courage dares to die; a man with inner courage dares to live.",
    author: "Lao Tzu",
    category: "Courage",
    tags: ["strength", "life"],
    popularity: 4.7,
  },
  {
    id: 137,
    content: "I am enough of an artist to draw freely upon my imagination.",
    author: "Albert Einstein",
    category: "Imagination",
    tags: ["artistry", "freedom"],
    popularity: 4.5,
  },
  {
    id: 138,
    content:
      "Human behavior flows from three main sources: desire, emotion, and knowledge.",
    author: "Plato",
    category: "Knowledge",
    tags: ["psychology", "philosophy"],
    popularity: 4.6,
  },
  {
    id: 139,
    content: "Joy is a net of love by which you can catch souls.",
    author: "Mother Teresa",
    category: "Happiness",
    tags: ["joy", "love"],
    popularity: 4.6,
  },
  {
    id: 140,
    content:
      "Patience and perseverance have a magical effect before which difficulties disappear and obstacles vanish.",
    author: "John Quincy Adams",
    category: "Perseverance",
    tags: ["patience", "obstacles"],
    popularity: 4.7,
  },
  {
    id: 141,
    content:
      "Build your own dreams, or someone else will hire you to build theirs.",
    author: "Farrah Gray",
    category: "Motivation",
    tags: ["ambition", "entrepreneurship"],
    popularity: 4.8,
  },
  {
    id: 142,
    content: "Angry people are not always wise.",
    author: "Jane Austen",
    category: "Wisdom",
    tags: ["emotion", "judgment"],
    popularity: 4.4,
  },
  {
    id: 143,
    content:
      "Life is a succession of lessons which must be lived to be understood.",
    author: "Helen Keller",
    category: "Life",
    tags: ["learning", "experience"],
    popularity: 4.7,
  },
  {
    id: 144,
    content:
      "To be successful, you must accept all challenges that come your way. You can't just accept the ones you like.",
    author: "Mike Gafka",
    category: "Success",
    tags: ["challenge", "acceptance"],
    popularity: 4.5,
  },
  {
    id: 145,
    content: "We love the things we love for what they are.",
    author: "Robert Frost",
    category: "Love",
    tags: ["acceptance", "simplicity"],
    popularity: 4.5,
  },
  {
    id: 146,
    content:
      "Courage is not having the strength to go on; it is going on when you don't have the strength.",
    author: "Theodore Roosevelt",
    category: "Courage",
    tags: ["endurance", "strength"],
    popularity: 5.0,
  },
  {
    id: 147,
    content: "The true sign of intelligence is not knowledge but imagination.",
    author: "Albert Einstein",
    category: "Imagination",
    tags: ["intelligence", "creativity"],
    popularity: 4.9,
  },
  {
    id: 148,
    content: "Sharing knowledge is the most fundamental act of friendship.",
    author: "Richard Stallman",
    category: "Knowledge",
    tags: ["friendship", "sharing"],
    popularity: 4.4,
  },
  {
    id: 149,
    content:
      "Even if happiness forgets you a little bit, never completely forget about it.",
    author: "Jacques Prévert",
    category: "Happiness",
    tags: ["hope", "resilience"],
    popularity: 4.5,
  },
  {
    id: 150,
    content:
      "Success seems to be largely a matter of hanging on after others have let go.",
    author: "William Feather",
    category: "Perseverance",
    tags: ["tenacity", "endurance"],
    popularity: 4.6,
  },
  {
    id: 151,
    content: "Push yourself, because no one else is going to do it for you.",
    author: "Anonymous",
    category: "Motivation",
    tags: ["self-reliance", "discipline"],
    popularity: 4.6,
  },
  {
    id: 152,
    content:
      "It is not that I'm so smart. But I stay with the questions much longer.",
    author: "Albert Einstein",
    category: "Wisdom",
    tags: ["curiosity", "patience"],
    popularity: 4.8,
  },
  {
    id: 153,
    content:
      "Do not take life too seriously. You will never get out of it alive.",
    author: "Elbert Hubbard",
    category: "Life",
    tags: ["humor", "perspective"],
    popularity: 4.7,
  },
  {
    id: 154,
    content:
      "The price of success is hard work, dedication to the job at hand, and determination.",
    author: "Vince Lombardi",
    category: "Success",
    tags: ["dedication", "hard-work"],
    popularity: 4.7,
  },
  {
    id: 155,
    content: "Love is an irresistible desire to be irresistibly desired.",
    author: "Robert Frost",
    category: "Love",
    tags: ["desire", "attraction"],
    popularity: 4.6,
  },
  {
    id: 156,
    content:
      "Courage is the first of human qualities because it is the quality which guarantees the others.",
    author: "Aristotle",
    category: "Courage",
    tags: ["virtue", "foundation"],
    popularity: 4.7,
  },
  {
    id: 157,
    content: "Reality can be beaten with enough imagination.",
    author: "Mark Twain",
    category: "Imagination",
    tags: ["possibility", "mindset"],
    popularity: 4.6,
  },
  {
    id: 158,
    content: "Knowledge comes, but wisdom lingers.",
    author: "Alfred Lord Tennyson",
    category: "Knowledge",
    tags: ["wisdom", "time"],
    popularity: 4.7,
  },
  {
    id: 159,
    content: "Happiness is a warm puppy.",
    author: "Charles M. Schulz",
    category: "Happiness",
    tags: ["simplicity", "joy"],
    popularity: 4.8,
  },
  {
    id: 160,
    content:
      "Diamonds are nothing more than chunks of coal that stuck to their jobs.",
    author: "Malcolm Forbes",
    category: "Perseverance",
    tags: ["transformation", "pressure"],
    popularity: 4.8,
  },
  {
    id: 161,
    content: "Opportunities don't happen, you create them.",
    author: "Chris Grosser",
    category: "Motivation",
    tags: ["initiative", "creation"],
    popularity: 4.7,
  },
  {
    id: 162,
    content:
      "Count your age by friends, not years. Count your life by smiles, not tears.",
    author: "John Lennon",
    category: "Wisdom",
    tags: ["friendship", "happiness"],
    popularity: 4.8,
  },
  {
    id: 163,
    content:
      "Keep smiling, because life is a beautiful thing and there's so much to smile about.",
    author: "Marilyn Monroe",
    category: "Life",
    tags: ["positivity", "beauty"],
    popularity: 4.7,
  },
  {
    id: 164,
    content: "If you want to achieve greatness stop asking for permission.",
    author: "Anonymous",
    category: "Success",
    tags: ["initiative", "boldness"],
    popularity: 4.6,
  },
  {
    id: 165,
    content:
      "The only thing we never get enough of is love; and the only thing we never give enough of is love.",
    author: "Henry Miller",
    category: "Love",
    tags: ["generosity", "desire"],
    popularity: 4.7,
  },
  {
    id: 166,
    content:
      "Bravery is the capacity to perform properly even when scared half to death.",
    author: "Omar N. Bradley",
    category: "Courage",
    tags: ["bravery", "fear"],
    popularity: 4.5,
  },
  {
    id: 167,
    content:
      "We are what we pretend to be, so we must be careful about what we pretend to be.",
    author: "Kurt Vonnegut",
    category: "Imagination",
    tags: ["identity", "choice"],
    popularity: 4.7,
  },
  {
    id: 168,
    content:
      "The learning and knowledge that we have is, at the most, but little compared with that of which we are ignorant.",
    author: "Plato",
    category: "Knowledge",
    tags: ["humility", "ignorance"],
    popularity: 4.6,
  },
  {
    id: 169,
    content: "Sanity and happiness are an impossible combination.",
    author: "Mark Twain",
    category: "Happiness",
    tags: ["humor", "reality"],
    popularity: 4.6,
  },
  {
    id: 170,
    content:
      "Perseverance is not a long race; it is many short races one after the other.",
    author: "Walter Elliot",
    category: "Perseverance",
    tags: ["consistency", "effort"],
    popularity: 4.6,
  },
  {
    id: 171,
    content:
      "The harder you work for something, the greater you'll feel when you achieve it.",
    author: "Anonymous",
    category: "Motivation",
    tags: ["effort", "reward"],
    popularity: 4.5,
  },
  {
    id: 172,
    content:
      "Never mistake knowledge for wisdom. One helps you make a living; the other helps you make a life.",
    author: "Sandra Carey",
    category: "Wisdom",
    tags: ["knowledge", "life"],
    popularity: 4.7,
  },
  {
    id: 173,
    content:
      "The big lesson in life, baby, is never be scared of anyone or anything.",
    author: "Frank Sinatra",
    category: "Life",
    tags: ["confidence", "fearlessness"],
    popularity: 4.6,
  },
  {
    id: 174,
    content:
      "Success is not how high you have climbed, but how you make a positive difference to the world.",
    author: "Roy T. Bennett",
    category: "Success",
    tags: ["impact", "purpose"],
    popularity: 4.7,
  },
  {
    id: 175,
    content:
      "To be brave is to love someone unconditionally, without expecting anything in return.",
    author: "Madonna",
    category: "Love",
    tags: ["unconditional", "bravery"],
    popularity: 4.5,
  },
  {
    id: 176,
    content:
      "It is curious that physical courage should be so common in the world and moral courage so rare.",
    author: "Mark Twain",
    category: "Courage",
    tags: ["integrity", "morality"],
    popularity: 4.7,
  },
  {
    id: 177,
    content: "Imagination creates reality.",
    author: "Richard Wagner",
    category: "Imagination",
    tags: ["creation", "mindset"],
    popularity: 4.4,
  },
  {
    id: 178,
    content: "The great aim of education is not knowledge but action.",
    author: "Herbert Spencer",
    category: "Knowledge",
    tags: ["action", "education"],
    popularity: 4.5,
  },
  {
    id: 179,
    content: "Happiness is a state of activity.",
    author: "Aristotle",
    category: "Happiness",
    tags: ["action", "engagement"],
    popularity: 4.4,
  },
  {
    id: 180,
    content:
      "Through perseverance many people win success out of what seemed destined to be certain failure.",
    author: "Benjamin Disraeli",
    category: "Perseverance",
    tags: ["success", "failure"],
    popularity: 4.6,
  },
  {
    id: 181,
    content:
      "Do not wait to strike till the iron is hot; but make it hot by striking.",
    author: "William Butler Yeats",
    category: "Motivation",
    tags: ["initiative", "action"],
    popularity: 4.7,
  },
  {
    id: 182,
    content:
      "To know what you know and what you do not know, that is true knowledge.",
    author: "Confucius",
    category: "Wisdom",
    tags: ["self-awareness", "humility"],
    popularity: 4.8,
  },
  {
    id: 183,
    content: "Life itself is the most wonderful fairy tale.",
    author: "Hans Christian Andersen",
    category: "Life",
    tags: ["wonder", "beauty"],
    popularity: 4.5,
  },
  {
    id: 184,
    content: "The secret to success is to know something nobody else knows.",
    author: "Aristotle Onassis",
    category: "Success",
    tags: ["knowledge", "advantage"],
    popularity: 4.5,
  },
  {
    id: 185,
    content: "If I know what love is, it is because of you.",
    author: "Hermann Hesse",
    category: "Love",
    tags: ["gratitude", "relationships"],
    popularity: 4.7,
  },
  {
    id: 186,
    content:
      "One isn't born with courage. One develops it by doing small courageous things.",
    author: "Maya Angelou",
    category: "Courage",
    tags: ["practice", "growth"],
    popularity: 4.8,
  },
  {
    id: 187,
    content:
      "A rock pile ceases to be a rock pile the moment a single man contemplates it, bearing within him the image of a cathedral.",
    author: "Antoine de Saint-Exupery",
    category: "Imagination",
    tags: ["vision", "potential"],
    popularity: 4.8,
  },
  {
    id: 188,
    content: "Knowledge has a beginning but no end.",
    author: "Geeta Iyengar",
    category: "Knowledge",
    tags: ["lifelong-learning", "journey"],
    popularity: 4.3,
  },
  {
    id: 189,
    content:
      "The moments of happiness we enjoy take us by surprise. It is not that we seize them, but that they seize us.",
    author: "Ashley Montagu",
    category: "Happiness",
    tags: ["serendipity", "joy"],
    popularity: 4.5,
  },
  {
    id: 190,
    content:
      "Grit is that 'extra something' that separates the most successful people from the rest.",
    author: "Angela Duckworth",
    category: "Perseverance",
    tags: ["grit", "success"],
    popularity: 4.7,
  },
  {
    id: 191,
    content: "The dreamers are the saviors of the world.",
    author: "James Allen",
    category: "Motivation",
    tags: ["dreams", "vision"],
    popularity: 4.6,
  },
  {
    id: 192,
    content: "The only thing that interferes with my learning is my education.",
    author: "Albert Einstein",
    category: "Wisdom",
    tags: ["learning", "education"],
    popularity: 4.8,
  },
  {
    id: 193,
    content: "Not all those who wander are lost.",
    author: "J.R.R. Tolkien",
    category: "Life",
    tags: ["exploration", "journey"],
    popularity: 5.0,
  },
  {
    id: 194,
    content: "You miss 100% of the shots you don't take.",
    author: "Wayne Gretzky",
    category: "Success",
    tags: ["opportunity", "risk"],
    popularity: 5.0,
  },
  {
    id: 195,
    content: "To love at all is to be vulnerable.",
    author: "C.S. Lewis",
    category: "Love",
    tags: ["vulnerability", "risk"],
    popularity: 4.7,
  },
  {
    id: 196,
    content: "Fortune favors the bold.",
    author: "Virgil",
    category: "Courage",
    tags: ["boldness", "risk"],
    popularity: 4.9,
  },
  {
    id: 197,
    content:
      "You can't use up creativity. The more you use, the more you have.",
    author: "Maya Angelou",
    category: "Imagination",
    tags: ["creativity", "abundance"],
    popularity: 4.8,
  },
  {
    id: 198,
    content:
      "The man who asks a question is a fool for a minute, the man who does not ask is a fool for life.",
    author: "Confucius",
    category: "Knowledge",
    tags: ["curiosity", "questions"],
    popularity: 4.9,
  },
  {
    id: 199,
    content:
      "The greatest happiness you can have is knowing that you do not necessarily require happiness.",
    author: "William Saroyan",
    category: "Happiness",
    tags: ["contentment", "detachment"],
    popularity: 4.6,
  },
  {
    id: 200,
    content:
      "The key to success is to focus our conscious mind on things we desire not things we fear.",
    author: "Brian Tracy",
    category: "Perseverance",
    tags: ["focus", "mindset"],
    popularity: 4.6,
  },
];
