const quizzes = [
  {
    id: 1,
    subject: "Mathematics",
    question: "What is 15 plus 4?",
    options: { A: "18", B: "19", C: "20", D: "11" },
    correctAnswer: "B",
    explanation: "15 + 4 = 19.",
  },
  {
    id: 2,
    subject: "English",
    question: "Select the doing word: The boy runs fast.",
    options: { A: "Boy", B: "The", C: "Runs", D: "Fast" },
    correctAnswer: "C",
    explanation: "'Runs' is the verb or action word.",
  },
  {
    id: 3,
    subject: "Kiswahili",
    question: "Jaza pengo: Huyu ___ baba yangu.",
    options: { A: "ni", B: "na", C: "wa", D: "ya" },
    correctAnswer: "A",
    explanation: "Huyu ni baba yangu (This is my father).",
  },
  {
    id: 4,
    subject: "Environmental Activities",
    question: "Which animal gives us wool?",
    options: { A: "Cow", B: "Sheep", C: "Goat", D: "Dog" },
    correctAnswer: "B",
    explanation: "Sheep have wool which is shorn to make clothes.",
  },
  {
    id: 5,
    subject: "Hygiene and Nutrition",
    question: "We brush our teeth to remove ___.",
    options: { A: "Water", B: "Food particles", C: "Tongue", D: "Gums" },
    correctAnswer: "B",
    explanation: "Brushing removes food particles to prevent decay.",
  },
  {
    id: 6,
    subject: "Religious Education",
    question: "God created the world in ___ days.",
    options: { A: "5", B: "6", C: "7", D: "10" },
    correctAnswer: "B",
    explanation: "Creation took 6 days, and He rested on the 7th.",
  },
  {
    id: 7,
    subject: "Creative Arts",
    question: "Which one is a primary color?",
    options: { A: "Green", B: "Red", C: "Purple", D: "Orange" },
    correctAnswer: "B",
    explanation: "Red, Blue, and Yellow are primary colors.",
  },
  {
    id: 8,
    subject: "Mathematics",
    question: "Which shape has three sides?",
    options: { A: "Square", B: "Rectangle", C: "Triangle", D: "Circle" },
    correctAnswer: "C",
    explanation: "A triangle has three sides.",
  },
  {
    id: 9,
    subject: "English",
    question: "What is the plural of 'Child'?",
    options: { A: "Childs", B: "Children", C: "Childrens", D: "Baby" },
    correctAnswer: "B",
    explanation: "The plural form of child is children.",
  },
  {
    id: 10,
    subject: "Kiswahili",
    question: "Wingi wa neno 'Mtu' ni ___.",
    options: { A: "Watu", B: "Mitu", C: "Vitu", D: "Jitu" },
    correctAnswer: "A",
    explanation: "Mtu mmoja, Watu wengi.",
  },
  {
    id: 11,
    subject: "Environmental Activities",
    question: "When it is raining, we carry an ___.",
    options: { A: "Umbrella", B: "Axe", C: "Plate", D: "Chair" },
    correctAnswer: "A",
    explanation: "An umbrella protects us from rain.",
  },
  {
    id: 12,
    subject: "Hygiene and Nutrition",
    question: "Which food is good for strong teeth?",
    options: { A: "Sweets", B: "Biscuits", C: "Milk", D: "Soda" },
    correctAnswer: "C",
    explanation: "Milk has calcium which is good for teeth.",
  },
  {
    id: 13,
    subject: "Movement Activities",
    question: "We use our ___ to kick a ball.",
    options: { A: "Hands", B: "Head", C: "Feet", D: "Knees" },
    correctAnswer: "C",
    explanation: "Football involves kicking with feet.",
  },
  {
    id: 14,
    subject: "Mathematics",
    question: "What is the value of 5 tens?",
    options: { A: "5", B: "15", C: "50", D: "500" },
    correctAnswer: "C",
    explanation: "5 tens means 5 groups of 10, which is 50.",
  },
  {
    id: 15,
    subject: "English",
    question: "The opposite of 'Big' is ___.",
    options: { A: "Large", B: "Huge", C: "Small", D: "Fat" },
    correctAnswer: "C",
    explanation: "Small is the opposite of big.",
  },
  {
    id: 16,
    subject: "Kiswahili",
    question: "Chagua jibu sahihi: Sisi ___ wanafunzi.",
    options: { A: "ni", B: "tuna", C: "tuko", D: "tumo" },
    correctAnswer: "A",
    explanation: "Sisi ni wanafunzi (We are students).",
  },
  {
    id: 17,
    subject: "Environmental Activities",
    question: "A safe place to cross the road is at the ___.",
    options: { A: "Corner", B: "Zebra crossing", C: "Roundabout", D: "Middle" },
    correctAnswer: "B",
    explanation: "Zebra crossings are marked for pedestrians.",
  },
  {
    id: 18,
    subject: "Religious Education",
    question: "The first man was called ___.",
    options: { A: "Eve", B: "Adam", C: "Moses", D: "Noah" },
    correctAnswer: "B",
    explanation: "Adam was the first man created.",
  },
  {
    id: 19,
    subject: "Creative Arts",
    question: "We use ___ to stick paper together.",
    options: { A: "Water", B: "Glue", C: "Sand", D: "Stone" },
    correctAnswer: "B",
    explanation: "Glue is an adhesive for paper.",
  },
  {
    id: 20,
    subject: "Mathematics",
    question: "Subtract: 20 - 5",
    options: { A: "10", B: "25", C: "15", D: "14" },
    correctAnswer: "C",
    explanation: "20 take away 5 is 15.",
  },
  {
    id: 21,
    subject: "English",
    question: "Choose the correct word: This is ___ apple.",
    options: { A: "a", B: "an", C: "the", D: "two" },
    correctAnswer: "B",
    explanation: "We use 'an' before words starting with a vowel sound like apple.",
  },
  {
    id: 22,
    subject: "Kiswahili",
    question: "Kinyume cha 'Keti' ni ___.",
    options: { A: "Lala", B: "Simama", C: "Tembea", D: "Kimbia" },
    correctAnswer: "B",
    explanation: "Kinyume cha keti (sit) ni simama (stand).",
  },
  {
    id: 23,
    subject: "Environmental Activities",
    question: "Soil used for modeling is ___ soil.",
    options: { A: "Sand", B: "Clay", C: "Loam", D: "Dust" },
    correctAnswer: "B",
    explanation: "Clay soil is sticky and good for modeling.",
  },
  {
    id: 24,
    subject: "Hygiene and Nutrition",
    question: "We wash our hands ___ visiting the toilet.",
    options: { A: "Before", B: "After", C: "While", D: "Never" },
    correctAnswer: "B",
    explanation: "Always wash hands after the toilet.",
  },
  {
    id: 25,
    subject: "Mathematics",
    question: "Which number is missing: 2, 4, 6, __, 10?",
    options: { A: "7", B: "8", C: "9", D: "5" },
    correctAnswer: "B",
    explanation: "We are skipping by 2s. After 6 comes 8.",
  },
  {
    id: 26,
    subject: "Movement Activities",
    question: "Running slowly is called ___.",
    options: { A: "Sprinting", B: "Jogging", C: "Walking", D: "Sleeping" },
    correctAnswer: "B",
    explanation: "Jogging is running at a gentle pace.",
  },
  {
    id: 27,
    subject: "English",
    question: "Which one is a domestic animal?",
    options: { A: "Lion", B: "Cow", C: "Elephant", D: "Snake" },
    correctAnswer: "B",
    explanation: "A cow is kept at home for milk.",
  },
  {
    id: 28,
    subject: "Kiswahili",
    question: "Mtoto wa ng'ombe anaitwa ___.",
    options: { A: "Ndama", B: "Kifaranga", C: "Mwana", D: "Kiboko" },
    correctAnswer: "A",
    explanation: "Ndama ni mtoto wa ng'ombe.",
  },
  {
    id: 29,
    subject: "Environmental Activities",
    question: "Which color is NOT on the Kenyan flag?",
    options: { A: "Black", B: "Red", C: "Green", D: "Blue" },
    correctAnswer: "D",
    explanation: "The Kenyan flag has Black, Red, Green, and White. Not Blue.",
  },
  {
    id: 30,
    subject: "Religious Education",
    question: "Christians go to church on ___.",
    options: { A: "Monday", B: "Friday", C: "Sunday", D: "Tuesday" },
    correctAnswer: "C",
    explanation: "Sunday is the day of worship for most Christians.",
  },
  {
    id: 31,
    subject: "Mathematics",
    question: "How many days are in a week?",
    options: { A: "5", B: "6", C: "7", D: "12" },
    correctAnswer: "C",
    explanation: "There are 7 days in a week.",
  },
  {
    id: 32,
    subject: "Creative Arts",
    question: "A shaker is a ___ instrument.",
    options: { A: "Wind", B: "String", C: "Percussion", D: "Electronic" },
    correctAnswer: "C",
    explanation: "Shakers are played by shaking (percussion).",
  },
  {
    id: 33,
    subject: "English",
    question: "Complete: A dog ___ in a kennel.",
    options: { A: "Lives", B: "Eats", C: "Flies", D: "Sings" },
    correctAnswer: "A",
    explanation: "A dog lives in a kennel.",
  },
  {
    id: 34,
    subject: "Kiswahili",
    question: "Tunasoma kwa kutumia ___.",
    options: { A: "Macho", B: "Pua", C: "Miguu", D: "Masikio" },
    correctAnswer: "A",
    explanation: "Tunatumia macho kusoma.",
  },
  {
    id: 35,
    subject: "Hygiene and Nutrition",
    question: "We should eat a ___ diet.",
    options: { A: "Sweet", B: "Balanced", C: "Large", D: "Small" },
    correctAnswer: "B",
    explanation: "A balanced diet keeps us healthy.",
  },
  {
    id: 36,
    subject: "Mathematics",
    question: "What is 3 multiplied by 3?",
    options: { A: "6", B: "9", C: "12", D: "33" },
    correctAnswer: "B",
    explanation: "3 times 3 equals 9.",
  },
  {
    id: 37,
    subject: "Environmental Activities",
    question: "We should keep our compound ___.",
    options: { A: "Dirty", B: "Clean", C: "Wet", D: "Bushy" },
    correctAnswer: "B",
    explanation: "A clean compound prevents diseases.",
  },
  {
    id: 38,
    subject: "Religious Education",
    question: "Who built the Ark?",
    options: { A: "David", B: "Noah", C: "Jesus", D: "Peter" },
    correctAnswer: "B",
    explanation: "Noah built the Ark to save animals from the flood.",
  },
  {
    id: 39,
    subject: "English",
    question: "A person who treats sick people is a ___.",
    options: { A: "Teacher", B: "Farmer", C: "Doctor", D: "Driver" },
    correctAnswer: "C",
    explanation: "Doctors treat sick patients.",
  },
  {
    id: 40,
    subject: "Kiswahili",
    question: "Andika kwa nambari: Kumi na tano.",
    options: { A: "10", B: "5", C: "15", D: "51" },
    correctAnswer: "C",
    explanation: "Kumi na tano ni 15.",
  },
  {
    id: 41,
    subject: "Creative Arts",
    question: "Weaving is done using ___.",
    options: { A: "Clay", B: "Banana fibers", C: "Stones", D: "Water" },
    correctAnswer: "B",
    explanation: "Fibers are used for weaving mats and baskets.",
  },
  {
    id: 42,
    subject: "Mathematics",
    question: "Which is heavier? A car or a feather?",
    options: { A: "A car", B: "A feather", C: "A book", D: "A pencil" },
    correctAnswer: "A",
    explanation: "A car has more mass than the other items.",
  },
  {
    id: 43,
    subject: "Hygiene and Nutrition",
    question: "Dirty fingernails keep ___.",
    options: { A: "Germs", B: "Food", C: "Soap", D: "Water" },
    correctAnswer: "A",
    explanation: "Germs hide under long, dirty nails.",
  },
  {
    id: 44,
    subject: "English",
    question: "Past tense of 'Go'.",
    options: { A: "Goed", B: "Going", C: "Went", D: "Gone" },
    correctAnswer: "C",
    explanation: "The past tense of go is went.",
  },
  {
    id: 45,
    subject: "Kiswahili",
    question: "Rangi ya majani ni ___.",
    options: { A: "Nyekundu", B: "Kijani", C: "Nyeusi", D: "Samawati" },
    correctAnswer: "B",
    explanation: "Majani huwa na rangi ya kijani.",
  },
  {
    id: 46,
    subject: "Environmental Activities",
    question: "During the day, the sky gives us ___.",
    options: { A: "Moon", B: "Stars", C: "Sun", D: "Darkness" },
    correctAnswer: "C",
    explanation: "The sun shines during the day.",
  },
  {
    id: 47,
    subject: "Movement Activities",
    question: "In swimming, we float on ___.",
    options: { A: "Sand", B: "Grass", C: "Water", D: "Air" },
    correctAnswer: "C",
    explanation: "Floating happens in water.",
  },
  {
    id: 48,
    subject: "Mathematics",
    question: "Write 'Forty-two' in numbers.",
    options: { A: "402", B: "24", C: "42", D: "412" },
    correctAnswer: "C",
    explanation: "The digits 4 and 2 make forty-two.",
  },
  {
    id: 49,
    subject: "Religious Education",
    question: "Muslims worship in a ___.",
    options: { A: "Church", B: "Temple", C: "Mosque", D: "School" },
    correctAnswer: "C",
    explanation: "A Mosque is the place of worship for Muslims.",
  },
  {
    id: 50,
    subject: "English",
    question: "Choose the polite word.",
    options: { A: "Shut up", B: "Get out", C: "Please", D: "Move" },
    correctAnswer: "C",
    explanation: "'Please' is a polite magic word.",
  },
  {
    id: 51,
    subject: "Kiswahili",
    question: "Mwalimu huandika kwenye ___.",
    options: { A: "Ubao", B: "Ukuta", C: "Mti", D: "Gari" },
    correctAnswer: "A",
    explanation: "Mwalimu hutumia ubao darasani.",
  },
  {
    id: 52,
    subject: "Environmental Activities",
    question: "A farmer grows crops in the ___.",
    options: { A: "House", B: "Garden/Shamba", C: "Road", D: "River" },
    correctAnswer: "B",
    explanation: "Crops are grown in the shamba.",
  },
  {
    id: 53,
    subject: "Hygiene and Nutrition",
    question: "We clean our ears using a ___.",
    options: { A: "Stick", B: "Pin", C: "Clean cloth/bud", D: "Pencil" },
    correctAnswer: "C",
    explanation: "Sharp objects damage ears. Use soft cloth or buds safely.",
  },
  {
    id: 54,
    subject: "Creative Arts",
    question: "The National Anthem of Kenya has ___ verses.",
    options: { A: "1", B: "2", C: "3", D: "4" },
    correctAnswer: "C",
    explanation: "It has three stanzas (verses).",
  },
  {
    id: 55,
    subject: "Mathematics",
    question: "How many 50 shilling coins make 100 shillings?",
    options: { A: "1", B: "2", C: "3", D: "4" },
    correctAnswer: "B",
    explanation: "50 + 50 = 100. So, two coins.",
  },
  {
    id: 56,
    subject: "English",
    question: "Kamau is reading ___ book.",
    options: { A: "his", B: "her", C: "she", D: "him" },
    correctAnswer: "A",
    explanation: "Kamau is a boy, so we use 'his'.",
  },
  {
    id: 57,
    subject: "Kiswahili",
    question: "Umoja wa 'Viatu' ni ___.",
    options: { A: "Kiatu", B: "Jiatu", C: "Mguu", D: "Vatu" },
    correctAnswer: "A",
    explanation: "Kiatu kimoja, viatu vingi.",
  },
  {
    id: 58,
    subject: "Religious Education",
    question: "David killed the giant ___.",
    options: { A: "Goliath", B: "Samson", C: "Saul", D: "Lion" },
    correctAnswer: "A",
    explanation: "David defeated Goliath.",
  },
  {
    id: 59,
    subject: "Environmental Activities",
    question: "Which one is a source of water?",
    options: { A: "Stone", B: "River", C: "Table", D: "Fire" },
    correctAnswer: "B",
    explanation: "Rivers provide water.",
  },
  {
    id: 60,
    subject: "Mathematics",
    question: "What fraction is shaded if 1 out of 4 parts is colored?",
    options: { A: "1/2", B: "1/4", C: "1/3", D: "3/4" },
    correctAnswer: "B",
    explanation: "One part out of four is a quarter (1/4).",
  },
  {
    id: 61,
    subject: "English",
    question: "Which word rhymes with 'Cat'?",
    options: { A: "Dog", B: "Mat", C: "Pen", D: "Cup" },
    correctAnswer: "B",
    explanation: "Cat and Mat end with the same sound.",
  },
  {
    id: 62,
    subject: "Movement Activities",
    question: "Skipping is done using a ___.",
    options: { A: "Ball", B: "Rope", C: "Bat", D: "Net" },
    correctAnswer: "B",
    explanation: "We use a skipping rope.",
  },
  {
    id: 63,
    subject: "Hygiene and Nutrition",
    question: "Fruits should be ___ before eating.",
    options: { A: "Cooked", B: "Washed", C: "Dried", D: "Painted" },
    correctAnswer: "B",
    explanation: "Wash fruits to remove dirt and chemicals.",
  },
  {
    id: 64,
    subject: "Kiswahili",
    question: "Mama ya baba yangu ni ___.",
    options: { A: "Shangazi", B: "Nyanya", C: "Dada", D: "Mama mdogo" },
    correctAnswer: "B",
    explanation: "Mama wa baba ni nyanya (Grandmother).",
  },
  {
    id: 65,
    subject: "Environmental Activities",
    question: "We should not share ___.",
    options: { A: "Books", B: "Balls", C: "Handkerchiefs", D: "Food" },
    correctAnswer: "C",
    explanation: "Sharing handkerchiefs spreads germs.",
  },
  {
    id: 66,
    subject: "Mathematics",
    question: "Which month comes after December?",
    options: { A: "November", B: "February", C: "January", D: "March" },
    correctAnswer: "C",
    explanation: "January is the first month of the new year.",
  },
  {
    id: 67,
    subject: "English",
    question: "A baby cat is called a ___.",
    options: { A: "Puppy", B: "Kitten", C: "Calf", D: "Chick" },
    correctAnswer: "B",
    explanation: "A kitten is a young cat.",
  },
  {
    id: 68,
    subject: "Creative Arts",
    question: "Drawing of a person is called a ___.",
    options: { A: "Landscape", B: "Portrait", C: "Pattern", D: "Map" },
    correctAnswer: "B",
    explanation: "A portrait shows a person.",
  },
  {
    id: 69,
    subject: "Kiswahili",
    question: "Chombo cha usafiri majini ni ___.",
    options: { A: "Gari", B: "Ndege", C: "Meli", D: "Baiskeli" },
    correctAnswer: "C",
    explanation: "Meli hutumika majini.",
  },
  {
    id: 70,
    subject: "Religious Education",
    question: "The Bible has ___ parts.",
    options: { A: "1", B: "2", C: "3", D: "4" },
    correctAnswer: "B",
    explanation: "Old Testament and New Testament.",
  },
  {
    id: 71,
    subject: "Mathematics",
    question: "500 + 20 + 9 =",
    options: { A: "529", B: "592", C: "925", D: "259" },
    correctAnswer: "A",
    explanation: "500 plus 20 plus 9 is 529.",
  },
  {
    id: 72,
    subject: "English",
    question: "We use our ears to ___.",
    options: { A: "See", B: "Smell", C: "Taste", D: "Hear" },
    correctAnswer: "D",
    explanation: "Ears are for hearing.",
  },
  {
    id: 73,
    subject: "Environmental Activities",
    question: "A cow lives in a ___.",
    options: { A: "Hutch", B: "Kennel", C: "Cowshed", D: "Nest" },
    correctAnswer: "C",
    explanation: "Cows sleep in a cowshed.",
  },
  {
    id: 74,
    subject: "Hygiene and Nutrition",
    question: "Personal items include ___.",
    options: { A: "Desk", B: "Toothbrush", C: "Ball", D: "Chair" },
    correctAnswer: "B",
    explanation: "A toothbrush is personal and not shared.",
  },
  {
    id: 75,
    subject: "Kiswahili",
    question: "Jina la taifa letu ni ___.",
    options: { A: "Uganda", B: "Nairobi", C: "Kenya", D: "Mombasa" },
    correctAnswer: "C",
    explanation: "Sisi tunaishi Kenya.",
  },
  {
    id: 76,
    subject: "Mathematics",
    question: "Share 12 sweets equally among 4 children.",
    options: { A: "2", B: "4", C: "3", D: "6" },
    correctAnswer: "C",
    explanation: "12 divided by 4 equals 3.",
  },
  {
    id: 77,
    subject: "Creative Arts",
    question: "Mixing Red and Yellow makes ___.",
    options: { A: "Green", B: "Orange", C: "Purple", D: "Blue" },
    correctAnswer: "B",
    explanation: "Red + Yellow = Orange.",
  },
  {
    id: 78,
    subject: "English",
    question: "Which one is a vegetable?",
    options: { A: "Mango", B: "Spinach", C: "Orange", D: "Banana" },
    correctAnswer: "B",
    explanation: "Spinach is a vegetable (sukuma wiki type).",
  },
  {
    id: 79,
    subject: "Religious Education",
    question: "Jesus was born in ___.",
    options: { A: "Nazareth", B: "Bethlehem", C: "Jerusalem", D: "Egypt" },
    correctAnswer: "B",
    explanation: "Jesus was born in Bethlehem.",
  },
  {
    id: 80,
    subject: "Environmental Activities",
    question: "Plants need water and ___ to grow.",
    options: { A: "Milk", B: "Sunlight", C: "Soda", D: "Darkness" },
    correctAnswer: "B",
    explanation: "Plants need sunlight to grow.",
  },
  {
    id: 81,
    subject: "Movement Activities",
    question: "The game of 'Hide and Seek' involves ___.",
    options: { A: "Sleeping", B: "Hiding", C: "Eating", D: "Writing" },
    correctAnswer: "B",
    explanation: "One person counts, others hide.",
  },
  {
    id: 82,
    subject: "Kiswahili",
    question: "Kuku hutupa nini?",
    options: { A: "Maziwa", B: "Mayai", C: "Pamba", D: "Ngozi" },
    correctAnswer: "B",
    explanation: "Kuku hutaga mayai.",
  },
  {
    id: 83,
    subject: "Mathematics",
    question: "What time is it when the long hand is on 12 and short hand on 3?",
    options: { A: "12 o'clock", B: "3 o'clock", C: "6 o'clock", D: "9 o'clock" },
    correctAnswer: "B",
    explanation: "It is 3 o'clock.",
  },
  {
    id: 84,
    subject: "English",
    question: "The sun rises in the ___.",
    options: { A: "West", B: "North", C: "East", D: "South" },
    correctAnswer: "C",
    explanation: "The sun always rises in the East.",
  },
  {
    id: 85,
    subject: "Hygiene and Nutrition",
    question: "Sleeping under a treated mosquito net prevents ___.",
    options: { A: "Cold", B: "Malaria", C: "Hunger", D: "Thirst" },
    correctAnswer: "B",
    explanation: "Mosquito nets protect against malaria mosquitoes.",
  },
  {
    id: 86,
    subject: "Environmental Activities",
    question: "Traffic lights have Red, Amber, and ___.",
    options: { A: "Blue", B: "Green", C: "Black", D: "White" },
    correctAnswer: "B",
    explanation: "Green means go.",
  },
  {
    id: 87,
    subject: "Kiswahili",
    question: "Siku ya kwanza ya wiki ni ___.",
    options: { A: "Jumatatu", B: "Jumanne", C: "Jumapili", D: "Ijumaa" },
    correctAnswer: "A",
    explanation: "Jumatatu ndiyo siku ya kuanza shule/kazi.",
  },
  {
    id: 88,
    subject: "Religious Education",
    question: "We talk to God through ___.",
    options: { A: "Sleeping", B: "Eating", C: "Prayer", D: "Running" },
    correctAnswer: "C",
    explanation: "Prayer is communicating with God.",
  },
  {
    id: 89,
    subject: "Creative Arts",
    question: "A song sung to a baby to sleep is a ___.",
    options: { A: "Anthem", B: "Lullaby", C: "Carol", D: "Hymn" },
    correctAnswer: "B",
    explanation: "Lullabies soothe babies to sleep.",
  },
  {
    id: 90,
    subject: "Mathematics",
    question: "How many centimeters make 1 meter?",
    options: { A: "10", B: "100", C: "1000", D: "50" },
    correctAnswer: "B",
    explanation: "100 centimeters equal 1 meter.",
  },
  {
    id: 91,
    subject: "English",
    question: "The plural of 'Ox' is ___.",
    options: { A: "Oxes", B: "Oxen", C: "Oxer", D: "Ox" },
    correctAnswer: "B",
    explanation: "Oxen is the irregular plural of ox.",
  },
  {
    id: 92,
    subject: "Environmental Activities",
    question: "Used paper should be put in the ___.",
    options: { A: "Floor", B: "Pocket", C: "Dustbin", D: "Desk" },
    correctAnswer: "C",
    explanation: "Waste goes in the dustbin.",
  },
  {
    id: 93,
    subject: "Kiswahili",
    question: "Jibu la salamu 'Shikamoo' ni ___.",
    options: { A: "Sijambo", B: "Marahaba", C: "Asante", D: "Hujambo" },
    correctAnswer: "B",
    explanation: "Ukiamkiwa Shikamoo, unajibu Marahaba.",
  },
  {
    id: 94,
    subject: "Hygiene and Nutrition",
    question: "We taste food using our ___.",
    options: { A: "Teeth", B: "Lips", C: "Tongue", D: "Nose" },
    correctAnswer: "C",
    explanation: "The tongue has taste buds.",
  },
  {
    id: 95,
    subject: "Movement Activities",
    question: "Doing exercise makes the body ___.",
    options: { A: "Weak", B: "Sick", C: "Fit and Strong", D: "Lazy" },
    correctAnswer: "C",
    explanation: "Exercise improves fitness.",
  },
  {
    id: 96,
    subject: "Mathematics",
    question: "What is half of 20?",
    options: { A: "5", B: "15", C: "10", D: "2" },
    correctAnswer: "C",
    explanation: "20 shared between 2 is 10.",
  },
  {
    id: 97,
    subject: "English",
    question: "Choose the correct preposition: The cup is ___ the table.",
    options: { A: "in", B: "on", C: "at", D: "to" },
    correctAnswer: "B",
    explanation: "Objects sit 'on' a surface.",
  },
  {
    id: 98,
    subject: "Environmental Activities",
    question: "Wild animals live in the ___.",
    options: { A: "Forest", B: "Home", C: "Class", D: "Church" },
    correctAnswer: "A",
    explanation: "Wild animals live in forests or parks.",
  },
  {
    id: 99,
    subject: "Religious Education",
    question: "Who was swallowed by a big fish?",
    options: { A: "Jonah", B: "Daniel", C: "Paul", D: "Job" },
    correctAnswer: "A",
    explanation: "Jonah was swallowed by a whale/big fish.",
  },
  {
    id: 100,
    subject: "Creative Arts",
    question: "Pottery involves making items from ___.",
    options: { A: "Wood", B: "Clay", C: "Paper", D: "Cloth" },
    correctAnswer: "B",
    explanation: "Pottery is the art of using clay.",
  },
  {
    id: 101,
    subject: "Mathematics",
    question: "Which geometric shape looks like a ball?",
    options: { A: "Cube", B: "Sphere", C: "Triangle", D: "Square" },
    correctAnswer: "B",
    explanation: "A sphere is round like a ball.",
  },
  {
    id: 102,
    subject: "Kiswahili",
    question: "Kinyume cha 'Lia' ni ___.",
    options: { A: "Imba", B: "Cheka", C: "Nyamaza", D: "Lala" },
    correctAnswer: "B",
    explanation: "Kinyume cha kulia (cry) ni kucheka (laugh).",
  },
  {
    id: 103,
    subject: "Hygiene and Nutrition",
    question: "Tobacco is bad for our ___.",
    options: { A: "Lungs", B: "Hair", C: "Shoes", D: "Clothes" },
    correctAnswer: "A",
    explanation: "Smoking damages the lungs.",
  },
  {
    id: 104,
    subject: "English",
    question: "As brave as a ___.",
    options: { A: "Lion", B: "Mouse", C: "Chicken", D: "Fish" },
    correctAnswer: "A",
    explanation: "This is a common simile.",
  },
  {
    id: 105,
    subject: "Environmental Activities",
    question: "Which one is a natural source of light?",
    options: { A: "Torch", B: "Sun", C: "Candle", D: "Bulb" },
    correctAnswer: "B",
    explanation: "The Sun provides natural light.",
  },
  {
    id: 106,
    subject: "Mathematics",
    question: "Multiply: 5 x 5",
    options: { A: "10", B: "20", C: "25", D: "30" },
    correctAnswer: "C",
    explanation: "5 groups of 5 make 25.",
  },
  {
    id: 107,
    subject: "Kiswahili",
    question: "Kitendawili: Nyumba yangu haina mlango.",
    options: { A: "Yai", B: "Chungwa", C: "Mawe", D: "Mti" },
    correctAnswer: "A",
    explanation: "Yai (egg) halina mlango.",
  },
  {
    id: 108,
    subject: "Hygiene and Nutrition",
    question: "Boiled water is safe for ___.",
    options: { A: "Washing", B: "Drinking", C: "Ironing", D: "Playing" },
    correctAnswer: "B",
    explanation: "Boiling kills germs making water safe to drink.",
  },
  {
    id: 109,
    subject: "English",
    question: "What is the opposite of 'Beautiful'?",
    options: { A: "Pretty", B: "Good", C: "Ugly", D: "Smart" },
    correctAnswer: "C",
    explanation: "Ugly is the antonym of beautiful.",
  },
  {
    id: 110,
    subject: "Movement Activities",
    question: "In football, only the ___ can touch the ball with hands.",
    options: { A: "Striker", B: "Goalkeeper", C: "Referee", D: "Coach" },
    correctAnswer: "B",
    explanation: "The goalkeeper protects the goal using hands.",
  },
  {
    id: 111,
    subject: "Mathematics",
    question: "Which of these is used to measure length?",
    options: { A: "Scale/Ruler", B: "Cup", C: "Clock", D: "Spoon" },
    correctAnswer: "A",
    explanation: "We use a ruler or tape measure for length.",
  },
  {
    id: 112,
    subject: "Religious Education",
    question: "Who was the mother of Jesus?",
    options: { A: "Elizabeth", B: "Mary", C: "Eve", D: "Sarah" },
    correctAnswer: "B",
    explanation: "Mary gave birth to Jesus.",
  },
  {
    id: 113,
    subject: "Environmental Activities",
    question: "We wear heavy clothes when the weather is ___.",
    options: { A: "Hot", B: "Cold", C: "Sunny", D: "Calm" },
    correctAnswer: "B",
    explanation: "Heavy clothes keep us warm.",
  },
  {
    id: 114,
    subject: "English",
    question: "A group of sheep is called a ___.",
    options: { A: "Herd", B: "Flock", C: "School", D: "Gang" },
    correctAnswer: "B",
    explanation: "A flock of sheep.",
  },
  {
    id: 115,
    subject: "Kiswahili",
    question: "Jaza pengo: ___ anafunza wanafunzi.",
    options: { A: "Daktari", B: "Mwalimu", C: "Mpishi", D: "Dereva" },
    correctAnswer: "B",
    explanation: "Mwalimu ndiye hufunza shuleni.",
  },
  {
    id: 116,
    subject: "Creative Arts",
    question: "We use a ___ to color our drawings.",
    options: { A: "Needle", B: "Crayon", C: "Spoon", D: "Stick" },
    correctAnswer: "B",
    explanation: "Crayons add color to art.",
  },
  {
    id: 117,
    subject: "Mathematics",
    question: "What is the place value of 3 in the number 345?",
    options: { A: "Ones", B: "Tens", C: "Hundreds", D: "Thousands" },
    correctAnswer: "C",
    explanation: "3 is in the hundreds position.",
  },
  {
    id: 118,
    subject: "Hygiene and Nutrition",
    question: "Utensils are dried on a ___.",
    options: { A: "Floor", B: "Rack", C: "Bed", D: "Roof" },
    correctAnswer: "B",
    explanation: "A dish rack allows utensils to dry clean.",
  },
  {
    id: 119,
    subject: "Environmental Activities",
    question: "A donkey is used to ___.",
    options: {
      A: "Lay eggs",
      B: "Carry heavy loads",
      C: "Give milk",
      D: "Catch mice",
    },
    correctAnswer: "B",
    explanation: "Donkeys are beasts of burden.",
  },
  {
    id: 120,
    subject: "English",
    question: "Which word is spelled correctly?",
    options: { A: "Schol", B: "School", C: "Skool", D: "Scool" },
    correctAnswer: "B",
    explanation: "School is the correct spelling.",
  },
  {
    id: 121,
    subject: "Kiswahili",
    question: "Wingi wa 'Jicho' ni ___.",
    options: { A: "Majicho", B: "Macho", C: "Vicho", D: "Jicho" },
    correctAnswer: "B",
    explanation: "Jicho moja, Macho mawili.",
  },
  {
    id: 122,
    subject: "Mathematics",
    question: "If you have 50 shillings and buy a sweet for 10 shillings, how much is left?",
    options: {
      A: "30 shillings",
      B: "60 shillings",
      C: "40 shillings",
      D: "10 shillings",
    },
    correctAnswer: "C",
    explanation: "50 minus 10 equals 40.",
  },
  {
    id: 123,
    subject: "Religious Education",
    question: "The story of creation is found in the book of ___.",
    options: { A: "Matthew", B: "Genesis", C: "Exodus", D: "Mark" },
    correctAnswer: "B",
    explanation: "Genesis is the book of beginnings.",
  },
  {
    id: 124,
    subject: "Creative Arts",
    question: "A drum is played by ___.",
    options: { A: "Blowing", B: "Hitting/Beating", C: "Plucking", D: "Shaking" },
    correctAnswer: "B",
    explanation: "Drums are percussion instruments.",
  },
  {
    id: 125,
    subject: "English",
    question: "A person who flies an aeroplane is a ___.",
    options: { A: "Driver", B: "Captain", C: "Pilot", D: "Cyclist" },
    correctAnswer: "C",
    explanation: "Pilots fly planes.",
  },
  {
    id: 126,
    subject: "Hygiene and Nutrition",
    question: "Uncooked food is called ___ food.",
    options: { A: "Raw", B: "Fried", C: "Boiled", D: "Hot" },
    correctAnswer: "A",
    explanation: "Raw food is not cooked yet.",
  },
  {
    id: 127,
    subject: "Environmental Activities",
    question: "The green color on the traffic light means ___.",
    options: { A: "Stop", B: "Get Ready", C: "Go", D: "Wait" },
    correctAnswer: "C",
    explanation: "Green means Go.",
  },
  {
    id: 128,
    subject: "Mathematics",
    question: "Which number is even?",
    options: { A: "3", B: "7", C: "8", D: "11" },
    correctAnswer: "C",
    explanation: "Even numbers can be divided by 2. 8 is even.",
  },
  {
    id: 129,
    subject: "Kiswahili",
    question: "Bendera ya Kenya ina rangi ngapi?",
    options: { A: "Tatu", B: "Nne", C: "Tano", D: "Mbili" },
    correctAnswer: "B",
    explanation: "Nne: Nyeusi, Nyekundu, Kijani, na Nyeupe.",
  },
  {
    id: 130,
    subject: "Movement Activities",
    question: "Before playing, we should ___.",
    options: { A: "Sleep", B: "Warm up", C: "Eat heavily", D: "Bathe" },
    correctAnswer: "B",
    explanation: "Warm ups prevent injury.",
  },
  {
    id: 131,
    subject: "English",
    question: "Yesterday, I ___ to the market.",
    options: { A: "Walk", B: "Walked", C: "Walking", D: "Walks" },
    correctAnswer: "B",
    explanation: "Past tense of walk is walked.",
  },
  {
    id: 132,
    subject: "Environmental Activities",
    question: "Which soil is best for growing crops?",
    options: { A: "Clay", B: "Sand", C: "Loam", D: "Stones" },
    correctAnswer: "C",
    explanation: "Loam soil has nutrients for plants.",
  },
  {
    id: 133,
    subject: "Hygiene and Nutrition",
    question: "We should bathe ___.",
    options: {
      A: "Once a year",
      B: "Every day",
      C: "On Sundays only",
      D: "Never",
    },
    correctAnswer: "B",
    explanation: "Daily bathing keeps the body clean.",
  },
  {
    id: 134,
    subject: "Mathematics",
    question: "1000 grams is equal to ___.",
    options: { A: "1 Kilogram (kg)", B: "1 Gram (g)", C: "1 Meter", D: "1 Liter" },
    correctAnswer: "A",
    explanation: "1kg is made of 1000g.",
  },
  {
    id: 135,
    subject: "Religious Education",
    question: "Muslims fast during the month of ___.",
    options: { A: "December", B: "Ramadhan", C: "Easter", D: "June" },
    correctAnswer: "B",
    explanation: "Ramadhan is the holy month of fasting.",
  },
  {
    id: 136,
    subject: "Creative Arts",
    question: "Banana fibers are used for ___.",
    options: { A: "Drawing", B: "Weaving", C: "Cooking", D: "Painting" },
    correctAnswer: "B",
    explanation: "Weaving baskets or ropes.",
  },
  {
    id: 137,
    subject: "Kiswahili",
    question: "Andika kwa nambari: Thelathini.",
    options: { A: "13", B: "30", C: "3", D: "33" },
    correctAnswer: "B",
    explanation: "Thelathini ni 30.",
  },
  {
    id: 138,
    subject: "English",
    question: "Identify the adjective: The tall man.",
    options: { A: "The", B: "Tall", C: "Man", D: "Is" },
    correctAnswer: "B",
    explanation: "Tall describes the noun (man).",
  },
  {
    id: 139,
    subject: "Mathematics",
    question: "What fraction is smaller?",
    options: { A: "1/2", B: "1/4", C: "1/8", D: "1/1" },
    correctAnswer: "C",
    explanation: "1/8 is the smallest part among the options.",
  },
  {
    id: 140,
    subject: "Environmental Activities",
    question: "Fish live in ___.",
    options: { A: "Trees", B: "Soil", C: "Water", D: "Air" },
    correctAnswer: "C",
    explanation: "Fish can only survive in water.",
  },
  {
    id: 141,
    subject: "Hygiene and Nutrition",
    question: "We use a ___ to trim our fingernails.",
    options: { A: "Razor blade", B: "Nail cutter", C: "Knife", D: "Teeth" },
    correctAnswer: "B",
    explanation: "Nail cutters are safe for trimming nails.",
  },
  {
    id: 142,
    subject: "English",
    question: "A young dog is called a ___.",
    options: { A: "Kitten", B: "Cub", C: "Puppy", D: "Kid" },
    correctAnswer: "C",
    explanation: "Puppy is a baby dog.",
  },
  {
    id: 143,
    subject: "Kiswahili",
    question: "Kaka wa mama yangu anaitwa ___.",
    options: { A: "Mjomba", B: "Shangazi", C: "Babu", D: "Baba" },
    correctAnswer: "A",
    explanation: "Kaka wa mama ni mjomba (Uncle).",
  },
  {
    id: 144,
    subject: "Creative Arts",
    question: "Which one is a wind instrument?",
    options: { A: "Drum", B: "Flute", C: "Guitar", D: "Shaker" },
    correctAnswer: "B",
    explanation: "A flute is played by blowing air.",
  },
  {
    id: 145,
    subject: "Mathematics",
    question: "How many months are in a year?",
    options: { A: "10", B: "11", C: "12", D: "13" },
    correctAnswer: "C",
    explanation: "There are 12 months from January to December.",
  },
  {
    id: 146,
    subject: "Religious Education",
    question: "Who led the Israelites out of Egypt?",
    options: { A: "Noah", B: "Moses", C: "David", D: "Abraham" },
    correctAnswer: "B",
    explanation: "Moses led the Exodus.",
  },
  {
    id: 147,
    subject: "Environmental Activities",
    question: "We should cross the road when the pedestrian light is ___.",
    options: { A: "Red", B: "Green", C: "Off", D: "Yellow" },
    correctAnswer: "B",
    explanation: "Green man means it is safe to cross.",
  },
  {
    id: 148,
    subject: "Movement Activities",
    question: "A race where we pass a stick is called ___.",
    options: {
      A: "Sack race",
      B: "Relay race",
      C: "Egg race",
      D: "Marathon",
    },
    correctAnswer: "B",
    explanation: "Relay involves passing a baton.",
  },
  {
    id: 149,
    subject: "English",
    question: "I have ___ umbrella.",
    options: { A: "a", B: "an", C: "the", D: "at" },
    correctAnswer: "B",
    explanation: "Umbrella starts with a vowel sound.",
  },
  {
    id: 150,
    subject: "Kiswahili",
    question: "Chakula cha asubuhi kinaitwa ___.",
    options: { A: "Chajio", B: "Kiamsha kinywa", C: "Chamu", D: "Chana" },
    correctAnswer: "B",
    explanation: "Chakula cha asubuhi ni kiamsha kinywa.",
  },
  {
    id: 151,
    subject: "Hygiene and Nutrition",
    question: "Which of these is an energy-giving food?",
    options: { A: "Spinach", B: "Ugali", C: "Water", D: "Salt" },
    correctAnswer: "B",
    explanation: "Ugali (Maize) gives energy.",
  },
  {
    id: 152,
    subject: "Mathematics",
    question: "78 + 10 =",
    options: { A: "7810", B: "88", C: "68", D: "98" },
    correctAnswer: "B",
    explanation: "Adding 10 increases the tens digit by 1.",
  },
  {
    id: 153,
    subject: "Creative Arts",
    question: "Making pictures using cut-out paper is called ___.",
    options: { A: "Painting", B: "Collage", C: "Drawing", D: "Modeling" },
    correctAnswer: "B",
    explanation: "Collage is pasting materials together.",
  },
  {
    id: 154,
    subject: "Environmental Activities",
    question: "Which of these is a wild animal?",
    options: { A: "Goat", B: "Leopard", C: "Dog", D: "Chicken" },
    correctAnswer: "B",
    explanation: "Leopards live in the wild.",
  },
  {
    id: 155,
    subject: "English",
    question: "He likes bread ___ butter.",
    options: { A: "but", B: "or", C: "and", D: "so" },
    correctAnswer: "C",
    explanation: "We use 'and' to join similar items.",
  },
  {
    id: 156,
    subject: "Religious Education",
    question: "Jesus healed the ___.",
    options: { A: "Healthy", B: "Sick", C: "Strong", D: "Trees" },
    correctAnswer: "B",
    explanation: "Jesus performed miracles healing the sick.",
  },
  {
    id: 157,
    subject: "Kiswahili",
    question: "Kamilisha methali: Haraka haraka haina ___.",
    options: { A: "Baraka", B: "Hasara", C: "Faida", D: "Mwisho" },
    correctAnswer: "A",
    explanation: "Haraka haraka haina baraka.",
  },
  {
    id: 158,
    subject: "Mathematics",
    question: "What comes next: 10, 20, 30, ___?",
    options: { A: "31", B: "50", C: "40", D: "35" },
    correctAnswer: "C",
    explanation: "Counting by tens.",
  },
  {
    id: 159,
    subject: "Hygiene and Nutrition",
    question: "We should keep the toilet ___.",
    options: { A: "Wet", B: "Clean", C: "Open", D: "Smelly" },
    correctAnswer: "B",
    explanation: "Toilets must be clean to prevent disease.",
  },
  {
    id: 160,
    subject: "Movement Activities",
    question: "We play Netball with our ___.",
    options: { A: "Feet", B: "Hands", C: "Head", D: "Knees" },
    correctAnswer: "B",
    explanation: "Netball is a hand game.",
  },
  {
    id: 161,
    subject: "Environmental Activities",
    question: "The National Anthem is sung when standing at ___.",
    options: { A: "Ease", B: "Attention", C: "Sitting", D: "Walking" },
    correctAnswer: "B",
    explanation: "We stand at attention to show respect.",
  },
  {
    id: 162,
    subject: "English",
    question: "Which is a proper noun?",
    options: { A: "city", B: "Nairobi", C: "boy", D: "car" },
    correctAnswer: "B",
    explanation: "Nairobi is a specific name of a place.",
  },
  {
    id: 163,
    subject: "Kiswahili",
    question: "Tunasikia kwa kutumia ___.",
    options: { A: "Pua", B: "Masikio", C: "Mdomo", D: "Macho" },
    correctAnswer: "B",
    explanation: "Masikio ni ya kusikia.",
  },
  {
    id: 164,
    subject: "Mathematics",
    question: "Which coin has the highest value in Kenya?",
    options: {
      A: "1 Shilling",
      B: "10 Shillings",
      C: "20 Shillings",
      D: "40 Shillings",
    },
    correctAnswer: "C",
    explanation:
      "Among these coins, 20 shillings is the highest. (Note: 40 shilling coin does not exist).",
  },
  {
    id: 165,
    subject: "Creative Arts",
    question: "Smooth textures feel ___.",
    options: { A: "Rough", B: "Soft/Slippery", C: "Hard", D: "Sharp" },
    correctAnswer: "B",
    explanation: "Glass or silk feels smooth.",
  },
  {
    id: 166,
    subject: "Religious Education",
    question: "The first disciples of Jesus were ___.",
    options: { A: "Farmers", B: "Fishermen", C: "Doctors", D: "Teachers" },
    correctAnswer: "B",
    explanation: "Peter and Andrew were fishermen.",
  },
  {
    id: 167,
    subject: "Environmental Activities",
    question: "Water can be made safe for drinking by ___.",
    options: { A: "Cooling", B: "Boiling", C: "Shaking", D: "Coloring" },
    correctAnswer: "B",
    explanation: "Boiling kills germs.",
  },
  {
    id: 168,
    subject: "English",
    question: "The feminine of 'Bull' is ___.",
    options: { A: "Cow", B: "Heifer", C: "Lioness", D: "Mare" },
    correctAnswer: "A",
    explanation: "Cow is the female counterpart to Bull.",
  },
  {
    id: 169,
    subject: "Hygiene and Nutrition",
    question: "Sharing a comb can spread ___.",
    options: { A: "Malaria", B: "Lice/Ringworms", C: "Flu", D: "Stomach ache" },
    correctAnswer: "B",
    explanation: "Head lice and skin diseases spread via combs.",
  },
  {
    id: 170,
    subject: "Kiswahili",
    question: "Neno lipi ni sahihi?",
    options: { A: "Bulo", B: "Puluu", C: "Bluu", D: "Blue" },
    correctAnswer: "C",
    explanation: "Bluu (Blue) ndiyo tahajia sahihi ya Kiswahili.",
  },
  {
    id: 171,
    subject: "Mathematics",
    question: "Division: 15 ÷ 3",
    options: { A: "3", B: "4", C: "5", D: "6" },
    correctAnswer: "C",
    explanation: "15 shared into 3 groups is 5.",
  },
  {
    id: 172,
    subject: "Environmental Activities",
    question: "Shadows are shortest at ___.",
    options: { A: "Morning", B: "Noon", C: "Evening", D: "Night" },
    correctAnswer: "B",
    explanation: "At noon the sun is directly overhead.",
  },
  {
    id: 173,
    subject: "Creative Arts",
    question: "We use ___ to cut paper.",
    options: { A: "Glue", B: "Scissors", C: "Pencil", D: "Ruler" },
    correctAnswer: "B",
    explanation: "Scissors are for cutting.",
  },
  {
    id: 174,
    subject: "Religious Education",
    question: "We should ___ our parents.",
    options: { A: "Disobey", B: "Obey", C: "Beat", D: "Insult" },
    correctAnswer: "B",
    explanation: "Children are taught to obey parents.",
  },
  {
    id: 175,
    subject: "English",
    question: "We saw a ___ of bees.",
    options: { A: "Swarm", B: "Herd", C: "Pack", D: "Bunch" },
    correctAnswer: "A",
    explanation: "A swarm of bees.",
  },
  {
    id: 176,
    subject: "Hygiene and Nutrition",
    question: "A clean handkerchief is used to ___.",
    options: { A: "Wipe shoes", B: "Clean the nose", C: "Clean the desk", D: "Wrap food" },
    correctAnswer: "B",
    explanation: "It is for personal hygiene (nose).",
  },
  {
    id: 177,
    subject: "Kiswahili",
    question: "Mnyama gani ana shingo ndefu?",
    options: { A: "Simba", B: "Twiga", C: "Tembo", D: "Paka" },
    correctAnswer: "B",
    explanation: "Twiga ana shingo ndefu.",
  },
  {
    id: 178,
    subject: "Movement Activities",
    question: "When swimming, we wear a ___.",
    options: {
      A: "Suit",
      B: "Swimming costume",
      C: "Jacket",
      D: "Uniform",
    },
    correctAnswer: "B",
    explanation: "Proper attire for swimming.",
  },
  {
    id: 179,
    subject: "Environmental Activities",
    question: "Which part of the plant is found underground?",
    options: { A: "Flower", B: "Leaves", C: "Roots", D: "Stem" },
    correctAnswer: "C",
    explanation: "Roots grow in the soil.",
  },
  {
    id: 180,
    subject: "Mathematics",
    question: "25 - 10 =",
    options: { A: "10", B: "15", C: "35", D: "5" },
    correctAnswer: "B",
    explanation: "25 minus 10 is 15.",
  },
  {
    id: 181,
    subject: "English",
    question: "The plural of 'Foot' is ___.",
    options: { A: "Foots", B: "Feets", C: "Feet", D: "Foot" },
    correctAnswer: "C",
    explanation: "Feet is the plural of foot.",
  },
  {
    id: 182,
    subject: "Religious Education",
    question: "Zacchaeus climbed a ___ tree to see Jesus.",
    options: { A: "Mango", B: "Sycamore", C: "Pine", D: "Acacia" },
    correctAnswer: "B",
    explanation: "He climbed a Sycamore tree.",
  },
  {
    id: 183,
    subject: "Hygiene and Nutrition",
    question: "Which disease is caused by drinking dirty water?",
    options: { A: "Malaria", B: "Cholera", C: "Flu", D: "Measles" },
    correctAnswer: "B",
    explanation: "Cholera and Typhoid are waterborne.",
  },
  {
    id: 184,
    subject: "Kiswahili",
    question: "Jana ilikuwa Jumatatu, leo ni ___.",
    options: { A: "Jumapili", B: "Jumanne", C: "Jumatano", D: "Ijumaa" },
    correctAnswer: "B",
    explanation: "Baada ya Jumatatu ni Jumanne.",
  },
  {
    id: 185,
    subject: "Creative Arts",
    question: "Traditional dancers wear ___.",
    options: { A: "School uniform", B: "Costumes", C: "Pajamas", D: "Suits" },
    correctAnswer: "B",
    explanation: "Cultural dances use specific costumes.",
  },
  {
    id: 186,
    subject: "Environmental Activities",
    question: "We make furniture from ___.",
    options: { A: "Water", B: "Wood", C: "Sand", D: "Leaves" },
    correctAnswer: "B",
    explanation: "Wood from trees is used for chairs and tables.",
  },
  {
    id: 187,
    subject: "Mathematics",
    question: "How many liters are in 2 half-liters?",
    options: { A: "1", B: "2", C: "3", D: "4" },
    correctAnswer: "A",
    explanation: "Two halves make one whole.",
  },
  {
    id: 188,
    subject: "English",
    question: "A dog says ___.",
    options: { A: "Meow", B: "Moo", C: "Woof", D: "Quack" },
    correctAnswer: "C",
    explanation: "Dogs bark 'Woof'.",
  },
  {
    id: 189,
    subject: "Religious Education",
    question: "The Holy Book for Christians is the ___.",
    options: { A: "Quran", B: "Bible", C: "Storybook", D: "Newspaper" },
    correctAnswer: "B",
    explanation: "The Bible is the Christian holy book.",
  },
  {
    id: 190,
    subject: "Hygiene and Nutrition",
    question: "We wear ___ on our feet to protect them.",
    options: { A: "Gloves", B: "Shoes", C: "Hat", D: "Belt" },
    correctAnswer: "B",
    explanation: "Shoes protect feet from injury and germs.",
  },
  {
    id: 191,
    subject: "Kiswahili",
    question: "Umoja wa 'Meza' ni ___.",
    options: { A: "Memeza", B: "Jimeza", C: "Meza", D: "Kimeza" },
    correctAnswer: "C",
    explanation: "Meza haibadiliki (Meza moja, Meza mbili).",
  },
  {
    id: 192,
    subject: "Environmental Activities",
    question: "A train moves on ___.",
    options: { A: "Water", B: "Tarmac", C: "Rails", D: "Air" },
    correctAnswer: "C",
    explanation: "Trains run on railway lines.",
  },
  {
    id: 193,
    subject: "Creative Arts",
    question: "Modeling clay is found in ___ areas.",
    options: { A: "Sandy", B: "Swampy/Wet", C: "Rocky", D: "Dry" },
    correctAnswer: "B",
    explanation: "Clay soil is found in wet areas or river banks.",
  },
  {
    id: 194,
    subject: "Mathematics",
    question: "Add: 100 + 200",
    options: { A: "200", B: "300", C: "400", D: "120" },
    correctAnswer: "B",
    explanation: "100 + 200 = 300.",
  },
  {
    id: 195,
    subject: "English",
    question: "The past tense of 'Eat' is ___.",
    options: { A: "Eated", B: "Ate", C: "Eating", D: "Eats" },
    correctAnswer: "B",
    explanation: "Ate is the past tense of Eat.",
  },
  {
    id: 196,
    subject: "Hygiene and Nutrition",
    question: "Exercise makes our muscles ___.",
    options: { A: "Weak", B: "Strong", C: "Soft", D: "Small" },
    correctAnswer: "B",
    explanation: "Physical activity builds strength.",
  },
  {
    id: 197,
    subject: "Religious Education",
    question: "Christmas is celebrated on ___.",
    options: { A: "25th December", B: "1st June", C: "20th October", D: "12th December" },
    correctAnswer: "A",
    explanation: "The birth of Jesus is marked on Dec 25th.",
  },
  {
    id: 198,
    subject: "Environmental Activities",
    question: "Too much rain causes ___.",
    options: { A: "Drought", B: "Floods", C: "Dust", D: "Fire" },
    correctAnswer: "B",
    explanation: "Floods happen when there is excess rain.",
  },
  {
    id: 199,
    subject: "Movement Activities",
    question: "Hopping is done on ___ leg(s).",
    options: { A: "Two", B: "One", C: "Four", D: "Zero" },
    correctAnswer: "B",
    explanation: "Hopping is jumping on one foot.",
  },
  {
    id: 200,
    subject: "Kiswahili",
    question: "Mtoto wa kuku anaitwa ___.",
    options: { A: "Kifaranga", B: "Ndama", C: "Mwana", D: "Kiboko" },
    correctAnswer: "A",
    explanation: "Kifaranga ni mtoto wa kuku.",
  },
];


export default quizzes