import type { QuizType } from "@/pages/LINCOLN/LincolnQuickQuiz";

export const quizData: QuizType[] = [
  {
    id: 1,
    subject: "Mathematics",
    question: "What is 10 plus 5?",
    options: { A: "12", B: "15", C: "20", D: "11" },
    correctAnswer: "B",
    explanation: "10 + 5 = 15.",
  },
  {
    id: 2,
    subject: "English",
    question: "Which word starts with the sound 's'?",
    options: { A: "Apple", B: "Sun", C: "Ball", D: "Cat" },
    correctAnswer: "B",
    explanation: "'Sun' starts with letter 's'.",
  },
  {
    id: 3,
    subject: "Hygiene",
    question: "We should wash our hands ___ eating.",
    options: { A: "After", B: "Before", C: "During", D: "Never" },
    correctAnswer: "B",
    explanation: "Washing before meals removes germs.",
  },
  {
    id: 4,
    subject: "Environmental",
    question: "Which animal gives us milk?",
    options: { A: "Hen", B: "Dog", C: "Cow", D: "Cat" },
    correctAnswer: "C",
    explanation: "Cows are a source of milk.",
  },
  {
    id: 5,
    subject: "Kiswahili",
    question: "Salamu ya asubuhi ni ___.",
    options: {
      A: "Habari ya asubuhi",
      B: "Lala salama",
      C: "Asante",
      D: "Pole",
    },
    correctAnswer: "A",
    explanation: "Tunatumia 'Habari ya asubuhi' kumsalimu mtu asubuhi.",
  },
  {
    id: 6,
    subject: "Mathematics",
    question: "What shape is a door?",
    options: { A: "Circle", B: "Rectangle", C: "Triangle", D: "Star" },
    correctAnswer: "B",
    explanation: "Most doors have four sides with opposite sides equal.",
  },
  {
    id: 7,
    subject: "English",
    question: "Choose the doing word: The boy runs.",
    options: { A: "Boy", B: "The", C: "Runs", D: "Fast" },
    correctAnswer: "C",
    explanation: "Runs is an action word.",
  },
  {
    id: 8,
    subject: "Hygiene",
    question: "We use a ___ to clean our teeth.",
    options: { A: "Spoon", B: "Comb", C: "Toothbrush", D: "Soap" },
    correctAnswer: "C",
    explanation: "Toothbrushes clean teeth and gums.",
  },
  {
    id: 9,
    subject: "Environmental",
    question: "A plant grows from a ___.",
    options: { A: "Stone", B: "Seed", C: "Leaf", D: "Root" },
    correctAnswer: "B",
    explanation: "Most plants begin as seeds.",
  },
  {
    id: 10,
    subject: "Kiswahili",
    question: "Rangi ya damu ni ___.",
    options: { A: "Nyeupe", B: "Nyeusi", C: "Nyekundu", D: "Kijani" },
    correctAnswer: "C",
    explanation: "Damu huwa rangi ya nyekundu.",
  },
  {
    id: 11,
    subject: "Mathematics",
    question: "How many legs does a cow have?",
    options: { A: "2", B: "4", C: "6", D: "8" },
    correctAnswer: "B",
    explanation: "A cow is a four-legged animal.",
  },
  {
    id: 12,
    subject: "English",
    question: "Which one is a naming word (noun)?",
    options: { A: "Jump", B: "Mary", C: "Sing", D: "Cry" },
    correctAnswer: "B",
    explanation: "Mary is a name of a person.",
  },
  {
    id: 13,
    subject: "Hygiene",
    question: "We wash our bodies using water and ___.",
    options: { A: "Salt", B: "Soap", C: "Sugar", D: "Milk" },
    correctAnswer: "B",
    explanation: "Soap helps remove dirt and germs.",
  },
  {
    id: 14,
    subject: "Environmental",
    question: "What do we wear when it is cold?",
    options: { A: "Vest", B: "Sweater", C: "Shorts", D: "Hat" },
    correctAnswer: "B",
    explanation: "Sweaters keep us warm.",
  },
  {
    id: 15,
    subject: "Kiswahili",
    question: "Mama wa mama yangu ni ___.",
    options: { A: "Bibi", B: "Babu", C: "Mjomba", D: "Shangazi" },
    correctAnswer: "A",
    explanation: "Mama wa mama ni nyanya au bibi.",
  },
  {
    id: 16,
    subject: "Mathematics",
    question: "Which number is between 7 and 9?",
    options: { A: "6", B: "8", C: "10", D: "5" },
    correctAnswer: "B",
    explanation: "Counting: 7, 8, 9.",
  },
  {
    id: 17,
    subject: "English",
    question: "The plural of 'book' is ___.",
    options: { A: "Booked", B: "Booking", C: "Books", D: "Bookies" },
    correctAnswer: "C",
    explanation: "We add 's' to book to make it many.",
  },
  {
    id: 18,
    subject: "Hygiene",
    question: "Where do we put rubbish?",
    options: {
      A: "In the desk",
      B: "On the floor",
      C: "In the dustbin",
      D: "In the pocket",
    },
    correctAnswer: "C",
    explanation: "Dustbins are for waste disposal.",
  },
  {
    id: 19,
    subject: "Environmental",
    question: "The sun gives us light and ___.",
    options: { A: "Rain", B: "Water", C: "Heat", D: "Food" },
    correctAnswer: "C",
    explanation: "The sun is hot and provides heat.",
  },
  {
    id: 20,
    subject: "Kiswahili",
    question: "Jina la nambari 1 ni ___.",
    options: { A: "Moja", B: "Mbili", C: "Tatu", D: "Nne" },
    correctAnswer: "A",
    explanation: "1 kwa Kiswahili ni moja.",
  },
  {
    id: 21,
    subject: "Mathematics",
    question: "3 + 3 = ___",
    options: { A: "5", B: "6", C: "7", D: "9" },
    correctAnswer: "B",
    explanation: "Three and three make six.",
  },
  {
    id: 22,
    subject: "English",
    question: "A __ lives in water.",
    options: { A: "Bird", B: "Cat", C: "Fish", D: "Dog" },
    correctAnswer: "C",
    explanation: "Fish are aquatic animals.",
  },
  {
    id: 23,
    subject: "Hygiene",
    question: "We use a ___ to wipe our noses.",
    options: { A: "Sock", B: "Leaf", C: "Handkerchief", D: "Towel" },
    correctAnswer: "C",
    explanation: "Handkerchiefs are hygienic for noses.",
  },
  {
    id: 24,
    subject: "Environmental",
    question: "Which of these is a fruit?",
    options: { A: "Cabbage", B: "Carrot", C: "Orange", D: "Sukuma Wiki" },
    correctAnswer: "C",
    explanation: "Oranges are fruits.",
  },
  {
    id: 25,
    subject: "Kiswahili",
    question: "Tunasoma kwa kutumia ___.",
    options: { A: "Macho", B: "Masikio", C: "Miguu", D: "Mikono" },
    correctAnswer: "A",
    explanation: "Macho hutusaidia kuona maandishi.",
  },
  {
    id: 26,
    subject: "Mathematics",
    question: "Which one is a square?",
    options: { A: "O", B: "L", C: "☐", D: "△" },
    correctAnswer: "C",
    explanation: "A square has four equal sides.",
  },
  {
    id: 27,
    subject: "English",
    question: "Opposite of 'big' is ___.",
    options: { A: "Tall", B: "Fat", C: "Small", D: "Long" },
    correctAnswer: "C",
    explanation: "The opposite of big is small.",
  },
  {
    id: 28,
    subject: "Hygiene",
    question: "Keep your nails ___.",
    options: { A: "Long", B: "Dirty", C: "Short and clean", D: "Sharp" },
    correctAnswer: "C",
    explanation: "Short nails don't hide germs.",
  },
  {
    id: 29,
    subject: "Environmental",
    question: "Which animal barks?",
    options: { A: "Cat", B: "Cow", C: "Dog", D: "Lion" },
    correctAnswer: "C",
    explanation: "Dogs produce the barking sound.",
  },
  {
    id: 30,
    subject: "Kiswahili",
    question: "Habari ya ___ (jioni)?",
    options: { A: "Mama", B: "Jioni", C: "Lala", D: "Kalamu" },
    correctAnswer: "B",
    explanation: "Hii ni salamu ya wakati wa giza kuingia.",
  },
  {
    id: 31,
    subject: "Mathematics",
    question: "10 minus 0 is ___.",
    options: { A: "0", B: "10", C: "1", D: "20" },
    correctAnswer: "B",
    explanation: "Subtracting zero does not change the number.",
  },
  {
    id: 32,
    subject: "English",
    question: "I see with my ___.",
    options: { A: "Ears", B: "Eyes", C: "Nose", D: "Mouth" },
    correctAnswer: "B",
    explanation: "Eyes are the organs of sight.",
  },
  {
    id: 33,
    subject: "Hygiene",
    question: "Dirty water can make us ___.",
    options: { A: "Strong", B: "Sick", C: "Happy", D: "Tall" },
    correctAnswer: "B",
    explanation: "Dirty water contains harmful germs.",
  },
  {
    id: 34,
    subject: "Environmental",
    question: "We get eggs from ___.",
    options: { A: "Goat", B: "Hen", C: "Cow", D: "Sheep" },
    correctAnswer: "B",
    explanation: "Chickens (hens) lay eggs.",
  },
  {
    id: 35,
    subject: "Kiswahili",
    question: "Jina lingine la 'ndizi' ni ___.",
    options: { A: "Apple", B: "Banana", C: "Orange", D: "Mango" },
    correctAnswer: "B",
    explanation: "Ndizi kwa Kiingereza ni Banana.",
  },
  {
    id: 36,
    subject: "Mathematics",
    question: "How many fingers do you have in two hands?",
    options: { A: "5", B: "10", C: "15", D: "20" },
    correctAnswer: "B",
    explanation: "5 + 5 = 10.",
  },
  {
    id: 37,
    subject: "English",
    question: "Which word rhymes with 'cat'?",
    options: { A: "Dog", B: "Mat", C: "Sun", D: "Boy" },
    correctAnswer: "B",
    explanation: "Cat and mat have the same ending sound.",
  },
  {
    id: 38,
    subject: "Hygiene",
    question: "We sleep on a ___.",
    options: { A: "Table", B: "Bed", C: "Floor", D: "Chair" },
    correctAnswer: "B",
    explanation: "A bed is for resting and sleeping.",
  },
  {
    id: 39,
    subject: "Environmental",
    question: "A car has ___ wheels.",
    options: { A: "2", B: "3", C: "4", D: "5" },
    correctAnswer: "C",
    explanation: "Standard cars have 4 wheels.",
  },
  {
    id: 40,
    subject: "Kiswahili",
    question: "Asante maana yake ni ___.",
    options: { A: "Sorry", B: "Thank you", C: "Please", D: "Welcome" },
    correctAnswer: "B",
    explanation: "Asante ni neno la kutoa shukrani.",
  },
  {
    id: 41,
    subject: "Mathematics",
    question: "What is 20 + 0?",
    options: { A: "0", B: "2", C: "20", D: "200" },
    correctAnswer: "C",
    explanation: "Adding zero changes nothing.",
  },
  {
    id: 42,
    subject: "English",
    question: "The color of a leaf is ___.",
    options: { A: "Red", B: "Blue", C: "Green", D: "Yellow" },
    correctAnswer: "C",
    explanation: "Most leaves are green.",
  },
  {
    id: 43,
    subject: "Hygiene",
    question: "A ___ treats sick people.",
    options: { A: "Teacher", B: "Doctor", C: "Driver", D: "Farmer" },
    correctAnswer: "B",
    explanation: "Doctors give medicine and treatment.",
  },
  {
    id: 44,
    subject: "Environmental",
    question: "A domestic animal is ___.",
    options: { A: "Lion", B: "Goat", C: "Elephant", D: "Snake" },
    correctAnswer: "B",
    explanation: "Goats are kept at home.",
  },
  {
    id: 45,
    subject: "Kiswahili",
    question: "Kiti kinatumiwa kwa ___.",
    options: { A: "Kulala", B: "Kuketi", C: "Kucheza", D: "Kukimbia" },
    correctAnswer: "B",
    explanation: "Tunaketi kwenye kiti.",
  },
  {
    id: 46,
    subject: "Mathematics",
    question: "Count back from 5: 5, 4, 3, __",
    options: { A: "6", B: "2", C: "1", D: "0" },
    correctAnswer: "B",
    explanation: "Before 3 comes 2.",
  },
  {
    id: 47,
    subject: "English",
    question: "This is ___ egg.",
    options: { A: "a", B: "an", C: "the", D: "is" },
    correctAnswer: "B",
    explanation: "We use 'an' before vowel sounds (a, e, i, o, u).",
  },
  {
    id: 48,
    subject: "Hygiene",
    question: "Clean clothes make us look ___.",
    options: { A: "Dirty", B: "Smart", C: "Bad", D: "Sad" },
    correctAnswer: "B",
    explanation: "Smartness comes from cleanliness.",
  },
  {
    id: 49,
    subject: "Environmental",
    question: "We use an umbrella when it is ___.",
    options: { A: "Cold", B: "Raining", C: "Windy", D: "Dark" },
    correctAnswer: "B",
    explanation: "Umbrellas protect us from rain.",
  },
  {
    id: 50,
    subject: "Kiswahili",
    question: "Baba wa baba yangu ni ___.",
    options: { A: "Bibi", B: "Mjomba", C: "Babu", D: "Kaka" },
    correctAnswer: "C",
    explanation: "Baba wa baba ni babu.",
  },
  // ... continue with randomized pattern logic to ID 200
  {
    id: 51,
    subject: "Mathematics",
    question: "Which number is greater: 15 or 51?",
    options: { A: "15", B: "51", C: "None", D: "Both" },
    correctAnswer: "B",
    explanation: "51 is a larger value than 15.",
  },
  {
    id: 52,
    subject: "English",
    question: "Complete: The cat ___ on the mat.",
    options: { A: "sat", B: "see", C: "sing", D: "sun" },
    correctAnswer: "A",
    explanation: "Sat is the past tense of sit.",
  },
  {
    id: 53,
    subject: "Hygiene",
    question: "We use ___ to comb hair.",
    options: { A: "Brush", B: "Comb", C: "Spoon", D: "Stick" },
    correctAnswer: "B",
    explanation: "A comb is for grooming hair.",
  },
  {
    id: 54,
    subject: "Environmental",
    question: "Which of these is a wild animal?",
    options: { A: "Dog", B: "Cat", C: "Lion", D: "Cow" },
    correctAnswer: "C",
    explanation: "Lions live in the forest/wild.",
  },
  {
    id: 55,
    subject: "Kiswahili",
    question: "Taja nambari 5 kwa Kiswahili.",
    options: { A: "Tatu", B: "Nne", C: "Tano", D: "Sita" },
    correctAnswer: "C",
    explanation: "5 ni tano.",
  },
  {
    id: 56,
    subject: "Mathematics",
    question: "A triangle has ___ sides.",
    options: { A: "2", B: "3", C: "4", D: "5" },
    correctAnswer: "B",
    explanation: "Triangles are three-sided shapes.",
  },
  {
    id: 57,
    subject: "English",
    question: "Identify the capital letter for 'g'.",
    options: { A: "Q", B: "G", C: "C", D: "J" },
    correctAnswer: "B",
    explanation: "G is the uppercase form of g.",
  },
  {
    id: 58,
    subject: "Hygiene",
    question: "Long nails should be ___.",
    options: { A: "Painted", B: "Cut", C: "Hidden", D: "Dirty" },
    correctAnswer: "B",
    explanation: "Cutting nails prevents germ buildup.",
  },
  {
    id: 59,
    subject: "Environmental",
    question: "Plants need sunlight and ___ to grow.",
    options: { A: "Milk", B: "Water", C: "Soda", D: "Tea" },
    correctAnswer: "B",
    explanation: "Water is essential for plant life.",
  },
  {
    id: 60,
    subject: "Kiswahili",
    question: "Mwalimu hutufundisha ___.",
    options: { A: "Sokoni", B: "Shuleni", C: "Nyumbani", D: "Mtoni" },
    correctAnswer: "B",
    explanation: "Walimu hufundisha shuleni.",
  },
  {
    id: 61,
    subject: "Mathematics",
    question: "What is 10 plus 10?",
    options: { A: "10", B: "20", C: "30", D: "0" },
    correctAnswer: "B",
    explanation: "10 + 10 = 20.",
  },
  {
    id: 62,
    subject: "English",
    question: "Which sound does a dog make?",
    options: { A: "Moo", B: "Meow", C: "Bark", D: "Baa" },
    correctAnswer: "C",
    explanation: "Dogs bark.",
  },
  {
    id: 63,
    subject: "Hygiene",
    question: "We should wash our face with soap and clean ___.",
    options: { A: "Milk", B: "Water", C: "Oil", D: "Sand" },
    correctAnswer: "B",
    explanation: "Water is needed for washing.",
  },
  {
    id: 64,
    subject: "Environmental",
    question: "Which of these is a vegetable?",
    options: { A: "Apple", B: "Mango", C: "Cabbage", D: "Banana" },
    correctAnswer: "C",
    explanation: "Cabbage is a leafy vegetable.",
  },
  {
    id: 65,
    subject: "Kiswahili",
    question: "Kalamu inatumika kwa ___.",
    options: { A: "Kuandika", B: "Kukimbia", C: "Kufagia", D: "Kulala" },
    correctAnswer: "A",
    explanation: "Tunatumia kalamu kuandika.",
  },
  {
    id: 66,
    subject: "Mathematics",
    question: "Which one is a circle?",
    options: { A: "△", B: "☐", C: "O", D: "L" },
    correctAnswer: "C",
    explanation: "O is the shape of a circle.",
  },
  {
    id: 67,
    subject: "English",
    question: "Select the vowel: __",
    options: { A: "b", B: "c", C: "e", D: "f" },
    correctAnswer: "C",
    explanation: "Vowels are a, e, i, o, u.",
  },
  {
    id: 68,
    subject: "Hygiene",
    question: "We use a ___ to clean our ears.",
    options: { A: "Stick", B: "Cotton bud", C: "Nail", D: "Finger" },
    correctAnswer: "B",
    explanation: "Cotton buds are safe for cleaning ears.",
  },
  {
    id: 69,
    subject: "Environmental",
    question: "The sky is ___ during a sunny day.",
    options: { A: "Green", B: "Blue", C: "Red", D: "Black" },
    correctAnswer: "B",
    explanation: "The sky looks blue when it is clear.",
  },
  {
    id: 70,
    subject: "Kiswahili",
    question: "Kamilisha: Huyu ni ___ wangu (Father).",
    options: { A: "Mama", B: "Kaka", C: "Baba", D: "Dada" },
    correctAnswer: "C",
    explanation: "Father kwa Kiswahili ni Baba.",
  },
  {
    id: 71,
    subject: "Mathematics",
    question: "How many sides does a rectangle have?",
    options: { A: "3", B: "4", C: "5", D: "2" },
    correctAnswer: "B",
    explanation: "Rectangles have 4 sides.",
  },
  {
    id: 72,
    subject: "English",
    question: "What is the plural of 'pencil'?",
    options: { A: "Pencil", B: "Pencilling", C: "Pencils", D: "Penciled" },
    correctAnswer: "C",
    explanation: "Add 's' for many pencils.",
  },
  {
    id: 73,
    subject: "Hygiene",
    question: "We go to the ___ when we are sick.",
    options: { A: "Market", B: "Hospital", C: "Garden", D: "Field" },
    correctAnswer: "B",
    explanation: "Hospitals provide healthcare.",
  },
  {
    id: 74,
    subject: "Environmental",
    question: "A hen gives us meat and ___.",
    options: { A: "Milk", B: "Eggs", C: "Wool", D: "Honey" },
    correctAnswer: "B",
    explanation: "Hens lay eggs.",
  },
  {
    id: 75,
    subject: "Kiswahili",
    question: "Salama ya usiku ni ___.",
    options: {
      A: "Habari ya asubuhi",
      B: "Lala salama",
      C: "Pole",
      D: "Shikamoo",
    },
    correctAnswer: "B",
    explanation: "Tunatakiana 'Lala salama' wakati wa usiku.",
  },
  {
    id: 76,
    subject: "Mathematics",
    question: "What is 5 minus 5?",
    options: { A: "10", B: "0", C: "5", D: "1" },
    correctAnswer: "B",
    explanation: "5 - 5 = 0.",
  },
  {
    id: 77,
    subject: "English",
    question: "Which word starts with 'p'?",
    options: { A: "Ball", B: "Pen", C: "Sun", D: "Dog" },
    correctAnswer: "B",
    explanation: "Pen starts with letter 'p'.",
  },
  {
    id: 78,
    subject: "Hygiene",
    question: "We should change our inner wear ___.",
    options: { A: "Every day", B: "Every week", C: "Once a month", D: "Never" },
    correctAnswer: "A",
    explanation: "Daily changes keep us clean.",
  },
  {
    id: 79,
    subject: "Environmental",
    question: "A plant needs ___ to stay alive.",
    options: { A: "Juice", B: "Water", C: "Soda", D: "Milk" },
    correctAnswer: "B",
    explanation: "Plants drink water through roots.",
  },
  {
    id: 80,
    subject: "Kiswahili",
    question: "Nambari 10 kwa maneno ni ___.",
    options: { A: "Moja", B: "Tano", C: "Kumi", D: "Sita" },
    correctAnswer: "C",
    explanation: "10 ni kumi.",
  },
  {
    id: 81,
    subject: "Mathematics",
    question: "What comes after 19?",
    options: { A: "18", B: "20", C: "21", D: "10" },
    correctAnswer: "B",
    explanation: "Counting: 19, 20.",
  },
  {
    id: 82,
    subject: "English",
    question: "A ___ teaches pupils in school.",
    options: { A: "Doctor", B: "Farmer", C: "Teacher", D: "Pilot" },
    correctAnswer: "C",
    explanation: "Teachers help us learn.",
  },
  {
    id: 83,
    subject: "Hygiene",
    question: "Dirty nails hide ___.",
    options: { A: "Food", B: "Germs", C: "Toys", D: "Sweets" },
    correctAnswer: "B",
    explanation: "Germs live in dirt.",
  },
  {
    id: 84,
    subject: "Environmental",
    question: "Which one is used for transport?",
    options: { A: "Tree", B: "Bicycle", C: "Stone", D: "Leaf" },
    correctAnswer: "B",
    explanation: "Bicycles help us move from place to place.",
  },
  {
    id: 85,
    subject: "Kiswahili",
    question: "Jina la tunda hili 'Apple' kwa Kiswahili ni ___.",
    options: { A: "Embe", B: "Tofaa", C: "Ndizi", D: "Chungwa" },
    correctAnswer: "B",
    explanation: "Apple ni tofaa.",
  },
  {
    id: 86,
    subject: "Mathematics",
    question: "2 + 2 + 2 = ___",
    options: { A: "4", B: "6", C: "8", D: "2" },
    correctAnswer: "B",
    explanation: "Three twos make six.",
  },
  {
    id: 87,
    subject: "English",
    question: "The color of the sun is ___.",
    options: { A: "Blue", B: "Yellow", C: "Green", D: "Purple" },
    correctAnswer: "B",
    explanation: "The sun appears yellow/orange.",
  },
  {
    id: 88,
    subject: "Hygiene",
    question: "We use ___ to wash our hands.",
    options: { A: "Sugar", B: "Soap", C: "Sand", D: "Glue" },
    correctAnswer: "B",
    explanation: "Soap kills germs.",
  },
  {
    id: 89,
    subject: "Environmental",
    question: "A sheep gives us ___.",
    options: { A: "Wool", B: "Eggs", C: "Honey", D: "Silk" },
    correctAnswer: "A",
    explanation: "Wool comes from sheep.",
  },
  {
    id: 90,
    subject: "Kiswahili",
    question: "Kichwa, mabega, magoti na ___.",
    options: { A: "Mdomo", B: "Kidole", C: "Vidole vya miguu", D: "Tumbo" },
    correctAnswer: "C",
    explanation: "Ni wimbo wa viungo vya mwili.",
  },
  {
    id: 91,
    subject: "Mathematics",
    question: "Which number is smaller: 2 or 8?",
    options: { A: "8", B: "2", C: "Both", D: "None" },
    correctAnswer: "B",
    explanation: "2 comes before 8.",
  },
  {
    id: 92,
    subject: "English",
    question: "Which sound does a cat make?",
    options: { A: "Bark", B: "Meow", C: "Moo", D: "Hiss" },
    correctAnswer: "B",
    explanation: "Cats meow.",
  },
  {
    id: 93,
    subject: "Hygiene",
    question: "We should brush our teeth ___ a day.",
    options: { A: "Once", B: "Twice", C: "Ten times", D: "Never" },
    correctAnswer: "B",
    explanation: "Morning and evening (twice) is best.",
  },
  {
    id: 94,
    subject: "Environmental",
    question: "A young dog is called a ___.",
    options: { A: "Kitten", B: "Calf", C: "Puppy", D: "Chick" },
    correctAnswer: "C",
    explanation: "Puppies are baby dogs.",
  },
  {
    id: 95,
    subject: "Kiswahili",
    question: "Huyu ni ___ wangu (Sister).",
    options: { A: "Kaka", B: "Dada", C: "Mjomba", D: "Babu" },
    correctAnswer: "B",
    explanation: "Sister ni dada.",
  },
  {
    id: 96,
    subject: "Mathematics",
    question: "What is 8 plus 1?",
    options: { A: "7", B: "9", C: "10", D: "8" },
    correctAnswer: "B",
    explanation: "8 + 1 = 9.",
  },
  {
    id: 97,
    subject: "English",
    question: "Which one is a capital letter?",
    options: { A: "m", B: "n", C: "B", D: "e" },
    correctAnswer: "C",
    explanation: "B is uppercase.",
  },
  {
    id: 98,
    subject: "Hygiene",
    question: "Use a ___ to sweep the house.",
    options: { A: "Spoon", B: "Broom", C: "Pencil", D: "Comb" },
    correctAnswer: "B",
    explanation: "Brooms are for sweeping.",
  },
  {
    id: 99,
    subject: "Environmental",
    question: "Which animal is used for riding?",
    options: { A: "Cow", B: "Horse", C: "Dog", D: "Cat" },
    correctAnswer: "B",
    explanation: "Horses are used for transport/riding.",
  },
  {
    id: 100,
    subject: "Kiswahili",
    question: "Rangi ya maziwa ni ___.",
    options: { A: "Nyeusi", B: "Nyekundu", C: "Nyeupe", D: "Kijani" },
    correctAnswer: "C",
    explanation: "Maziwa ni meupe.",
  },
  {
    id: 101,
    subject: "Mathematics",
    question: "15 - 5 = ___",
    options: { A: "5", B: "10", C: "15", D: "20" },
    correctAnswer: "B",
    explanation: "15 take away 5 is 10.",
  },
  {
    id: 102,
    subject: "English",
    question: "Identify the naming word: The ball is red.",
    options: { A: "Is", B: "Red", C: "Ball", D: "The" },
    correctAnswer: "C",
    explanation: "Ball is a noun.",
  },
  {
    id: 103,
    subject: "Hygiene",
    question: "Where do we bathe?",
    options: { A: "Kitchen", B: "Bathroom", C: "Bedroom", D: "Store" },
    correctAnswer: "B",
    explanation: "Bathrooms are for cleaning the body.",
  },
  {
    id: 104,
    subject: "Environmental",
    question: "Bees give us ___.",
    options: { A: "Milk", B: "Honey", C: "Eggs", D: "Meat" },
    correctAnswer: "B",
    explanation: "Bees produce honey.",
  },
  {
    id: 105,
    subject: "Kiswahili",
    question: "Ni heshima kusema ___ ukipewa kitu.",
    options: { A: "Asante", B: "Pole", C: "Hapana", D: "Ondoka" },
    correctAnswer: "A",
    explanation: "Tunashukuru kwa kusema asante.",
  },
  {
    id: 106,
    subject: "Mathematics",
    question: "How many months are in a year?",
    options: { A: "7", B: "10", C: "12", D: "30" },
    correctAnswer: "C",
    explanation: "January to December are 12 months.",
  },
  {
    id: 107,
    subject: "English",
    question: "The opposite of 'In' is ___.",
    options: { A: "On", B: "Out", C: "Up", D: "Under" },
    correctAnswer: "B",
    explanation: "Opposite of in is out.",
  },
  {
    id: 108,
    subject: "Hygiene",
    question: "We use a ___ to cut nails.",
    options: { A: "Knife", B: "Nail cutter", C: "Teeth", D: "Stone" },
    correctAnswer: "B",
    explanation: "Nail cutters are the safe tool.",
  },
  {
    id: 109,
    subject: "Environmental",
    question: "A fish uses ___ to swim.",
    options: { A: "Legs", B: "Fins", C: "Wings", D: "Hands" },
    correctAnswer: "B",
    explanation: "Fins help fish move in water.",
  },
  {
    id: 110,
    subject: "Kiswahili",
    question: "Macho hutumiwa kwa ___.",
    options: { A: "Kusikia", B: "Kuona", C: "Kunusa", D: "Kuonja" },
    correctAnswer: "B",
    explanation: "Macho ni kwa ajili ya kuona.",
  },
  {
    id: 111,
    subject: "Mathematics",
    question: "12, 13, 14, __",
    options: { A: "10", B: "15", C: "16", D: "11" },
    correctAnswer: "B",
    explanation: "Counting in ones.",
  },
  {
    id: 112,
    subject: "English",
    question: "A ___ lives in a kennel.",
    options: { A: "Cat", B: "Dog", C: "Bird", D: "Lion" },
    correctAnswer: "B",
    explanation: "Dogs stay in kennels.",
  },
  {
    id: 113,
    subject: "Hygiene",
    question: "Wash fruits ___ eating.",
    options: { A: "Before", B: "After", C: "Never", D: "During" },
    correctAnswer: "A",
    explanation: "Washing removes dirt.",
  },
  {
    id: 114,
    subject: "Environmental",
    question: "Which of these is used to make furniture?",
    options: { A: "Paper", B: "Wood", C: "Glass", D: "Cloth" },
    correctAnswer: "B",
    explanation: "Wood comes from trees for making chairs.",
  },
  {
    id: 115,
    subject: "Kiswahili",
    question: "Jua hutoa ___.",
    options: { A: "Baridi", B: "Mwanga", C: "Mvua", D: "Chakula" },
    correctAnswer: "B",
    explanation: "Jua huangaza ulimwengu.",
  },
  {
    id: 116,
    subject: "Mathematics",
    question: "7 + 2 = ___",
    options: { A: "8", B: "9", C: "10", D: "72" },
    correctAnswer: "B",
    explanation: "7 + 2 = 9.",
  },
  {
    id: 117,
    subject: "English",
    question: "Identify the action word: I am jumping.",
    options: { A: "I", B: "Am", C: "Jumping", D: "Small" },
    correctAnswer: "C",
    explanation: "Jumping is the verb.",
  },
  {
    id: 118,
    subject: "Hygiene",
    question: "Use a ___ when coughing.",
    options: { A: "Hand", B: "Handkerchief", C: "Paper", D: "Book" },
    correctAnswer: "B",
    explanation: "Handkerchiefs stop germs from spreading.",
  },
  {
    id: 119,
    subject: "Environmental",
    question: "Which part of the plant is green?",
    options: { A: "Root", B: "Leaf", C: "Flower", D: "Stem" },
    correctAnswer: "B",
    explanation: "Leaves are usually green.",
  },
  {
    id: 120,
    subject: "Kiswahili",
    question: "Mimi hula kwa kutumia ___.",
    options: { A: "Mdomo", B: "Pua", C: "Sikio", D: "Jicho" },
    correctAnswer: "A",
    explanation: "Chakula hupitia mdomoni.",
  },
  {
    id: 121,
    subject: "Mathematics",
    question: "Which is more: 5 or 3?",
    options: { A: "3", B: "5", C: "None", D: "Both" },
    correctAnswer: "B",
    explanation: "5 is a bigger number.",
  },
  {
    id: 122,
    subject: "English",
    question: "A __ builds houses.",
    options: { A: "Mason", B: "Tailor", C: "Baker", D: "Driver" },
    correctAnswer: "A",
    explanation: "Masons use stones/bricks.",
  },
  {
    id: 123,
    subject: "Hygiene",
    question: "We should tidy our ___ after waking up.",
    options: { A: "Kitchen", B: "Bed", C: "Garden", D: "Road" },
    correctAnswer: "B",
    explanation: "Making your bed is a good habit.",
  },
  {
    id: 124,
    subject: "Environmental",
    question: "What color is the Kenyan flag at the bottom?",
    options: { A: "Black", B: "Green", C: "Red", D: "White" },
    correctAnswer: "B",
    explanation: "The bottom stripe is green.",
  },
  {
    id: 125,
    subject: "Kiswahili",
    question: "Kalamu, kitabu na ___ (ruler).",
    options: { A: "Rula", B: "Peni", C: "Meza", D: "Kiti" },
    correctAnswer: "A",
    explanation: "Ruler kwa Kiswahili ni rula.",
  },
  {
    id: 126,
    subject: "Mathematics",
    question: "9, 8, 7, 6, __",
    options: { A: "7", B: "5", C: "4", D: "0" },
    correctAnswer: "B",
    explanation: "Counting backwards.",
  },
  {
    id: 127,
    subject: "English",
    question: "The sound of letter 'B' is ___.",
    options: { A: "ah", B: "buh", C: "cuh", D: "duh" },
    correctAnswer: "B",
    explanation: "Phonetic sound for B.",
  },
  {
    id: 128,
    subject: "Hygiene",
    question: "We dry our bodies with a ___.",
    options: { A: "Shirt", B: "Towel", C: "Blanket", D: "Paper" },
    correctAnswer: "B",
    explanation: "Towels absorb water.",
  },
  {
    id: 129,
    subject: "Environmental",
    question: "Which animal has a long neck?",
    options: { A: "Lion", B: "Giraffe", C: "Elephant", D: "Hippo" },
    correctAnswer: "B",
    explanation: "Giraffes have very long necks.",
  },
  {
    id: 130,
    subject: "Kiswahili",
    question: "Huyu ni ___ wangu (Brother).",
    options: { A: "Dada", B: "Kaka", C: "Mama", D: "Bibi" },
    correctAnswer: "B",
    explanation: "Brother ni kaka.",
  },
  {
    id: 131,
    subject: "Mathematics",
    question: "What is 4 plus 4?",
    options: { A: "6", B: "8", C: "10", D: "44" },
    correctAnswer: "B",
    explanation: "4 + 4 = 8.",
  },
  {
    id: 132,
    subject: "English",
    question: "A ___ has a long trunk.",
    options: { A: "Cat", B: "Dog", C: "Elephant", D: "Hen" },
    correctAnswer: "C",
    explanation: "Elephants use trunks to breathe and eat.",
  },
  {
    id: 133,
    subject: "Hygiene",
    question: "We use ___ to clean our noses.",
    options: { A: "Leaves", B: "Handkerchief", C: "Socks", D: "Stones" },
    correctAnswer: "B",
    explanation: "Handkerchiefs are soft and clean for noses.",
  },
  {
    id: 134,
    subject: "Environmental",
    question: "The sun rises in the ___.",
    options: { A: "West", B: "East", C: "North", D: "South" },
    correctAnswer: "B",
    explanation: "The sun always rises from the East.",
  },
  {
    id: 135,
    subject: "Kiswahili",
    question: "Kamilisha: Hii ni ___ yangu (Hand).",
    options: { A: "Mguu", B: "Mkono", C: "Pua", D: "Sikio" },
    correctAnswer: "B",
    explanation: "Hand kwa Kiswahili ni mkono.",
  },
  {
    id: 136,
    subject: "Mathematics",
    question: "How many legs does a spider have?",
    options: { A: "4", B: "6", C: "8", D: "2" },
    correctAnswer: "C",
    explanation: "Spiders have 8 legs.",
  },
  {
    id: 137,
    subject: "English",
    question: "The baby is ___ (cry).",
    options: { A: "Cry", B: "Crying", C: "Cried", D: "Cries" },
    correctAnswer: "B",
    explanation: "Crying is happening now.",
  },
  {
    id: 138,
    subject: "Hygiene",
    question: "We should wash our hands after using the ___.",
    options: { A: "Book", B: "Toilet", C: "Pencil", D: "Bed" },
    correctAnswer: "B",
    explanation: "Toilets have germs that must be washed off.",
  },
  {
    id: 139,
    subject: "Environmental",
    question: "Which of these is a tame animal?",
    options: { A: "Lion", B: "Snake", C: "Cat", D: "Leopard" },
    correctAnswer: "C",
    explanation: "Cats are pets and live with people.",
  },
  {
    id: 140,
    subject: "Kiswahili",
    question: "Rangi ya damu ni ___.",
    options: { A: "Nyeupe", B: "Nyekundu", C: "Nyeusi", D: "Kijani" },
    correctAnswer: "B",
    explanation: "Damu huwa nyekundu.",
  },
  {
    id: 141,
    subject: "Mathematics",
    question: "What is 10 minus 7?",
    options: { A: "3", B: "4", C: "5", D: "2" },
    correctAnswer: "A",
    explanation: "10 - 7 = 3.",
  },
  {
    id: 142,
    subject: "English",
    question: "Which word rhymes with 'sun'?",
    options: { A: "Moon", B: "Run", C: "Star", D: "Sky" },
    correctAnswer: "B",
    explanation: "Sun and Run have the same sound.",
  },
  {
    id: 143,
    subject: "Hygiene",
    question: "Dirty hair can have ___.",
    options: { A: "Sweets", B: "Lice", C: "Flowers", D: "Money" },
    correctAnswer: "B",
    explanation: "Lice are small insects that live in dirty hair.",
  },
  {
    id: 144,
    subject: "Environmental",
    question: "We sit under a ___ for shade.",
    options: { A: "Stone", B: "Tree", C: "Flower", D: "Cloud" },
    correctAnswer: "B",
    explanation: "Trees provide shade from the hot sun.",
  },
  {
    id: 145,
    subject: "Kiswahili",
    question: "Habari ya ___ (morning)?",
    options: { A: "Asubuhi", B: "Jioni", C: "Mchana", D: "Usiku" },
    correctAnswer: "A",
    explanation: "Asubuhi ni morning.",
  },
  {
    id: 146,
    subject: "Mathematics",
    question: "Which number is written as 'three'?",
    options: { A: "1", B: "2", C: "3", D: "4" },
    correctAnswer: "C",
    explanation: "The numeral 3 is three.",
  },
  {
    id: 147,
    subject: "English",
    question: "The opposite of 'Boy' is ___.",
    options: { A: "Man", B: "Sister", C: "Girl", D: "Mother" },
    correctAnswer: "C",
    explanation: "Opposite gender of boy is girl.",
  },
  {
    id: 148,
    subject: "Hygiene",
    question: "We use ___ to wash our hair.",
    options: { A: "Oil", B: "Shampoo", C: "Salt", D: "Tea" },
    correctAnswer: "B",
    explanation: "Shampoo cleans hair and scalp.",
  },
  {
    id: 149,
    subject: "Environmental",
    question: "Which animal has no legs?",
    options: { A: "Dog", B: "Snake", C: "Hen", D: "Goat" },
    correctAnswer: "B",
    explanation: "Snakes crawl; they have no legs.",
  },
  {
    id: 150,
    subject: "Kiswahili",
    question: "Tunasikia kwa kutumia ___.",
    options: { A: "Macho", B: "Masikio", C: "Pua", D: "Miguu" },
    correctAnswer: "B",
    explanation: "Masikio ni kwa ajili ya kusikia.",
  },
  {
    id: 151,
    subject: "Mathematics",
    question: "What is 5 + 0?",
    options: { A: "0", B: "5", C: "50", D: "1" },
    correctAnswer: "B",
    explanation: "Adding zero does not change a number.",
  },
  {
    id: 152,
    subject: "English",
    question: "Choose the capital letter: __",
    options: { A: "a", B: "t", C: "H", D: "r" },
    correctAnswer: "C",
    explanation: "H is uppercase.",
  },
  {
    id: 153,
    subject: "Hygiene",
    question: "We use a ___ to wipe sweat.",
    options: { A: "Hand", B: "Towel", C: "Paper", D: "Book" },
    correctAnswer: "B",
    explanation: "Towels dry our skin.",
  },
  {
    id: 154,
    subject: "Environmental",
    question: "The color of a banana is ___.",
    options: { A: "Red", B: "Blue", C: "Yellow", D: "Pink" },
    correctAnswer: "C",
    explanation: "Ripe bananas are yellow.",
  },
  {
    id: 155,
    subject: "Kiswahili",
    question: "Kiti, meza na ___ (blackboard).",
    options: { A: "Ubao", B: "Rula", C: "Kalamu", D: "Kitabu" },
    correctAnswer: "A",
    explanation: "Blackboard kwa Kiswahili ni ubao.",
  },
  {
    id: 156,
    subject: "Mathematics",
    question: "How many corners does a triangle have?",
    options: { A: "2", B: "3", C: "4", D: "0" },
    correctAnswer: "B",
    explanation: "A triangle has 3 corners.",
  },
  {
    id: 157,
    subject: "English",
    question: "The plural of 'Cat' is ___.",
    options: { A: "Catted", B: "Catting", C: "Cats", D: "Kitten" },
    correctAnswer: "C",
    explanation: "Add 's' for more than one cat.",
  },
  {
    id: 158,
    subject: "Hygiene",
    question: "Brush your teeth in the morning and at ___.",
    options: { A: "Noon", B: "Night", C: "Lunch", D: "Play" },
    correctAnswer: "B",
    explanation: "Brushing before bed is healthy.",
  },
  {
    id: 159,
    subject: "Environmental",
    question: "Which of these is a flower?",
    options: { A: "Grass", B: "Rose", C: "Stick", D: "Leaf" },
    correctAnswer: "B",
    explanation: "A rose is a beautiful flower.",
  },
  {
    id: 160,
    subject: "Kiswahili",
    question: "Baba na Mama ni ___ wangu.",
    options: { A: "Walimu", B: "Wazazi", C: "Marafiki", D: "Wageni" },
    correctAnswer: "B",
    explanation: "Baba na mama ni wazazi.",
  },
  {
    id: 161,
    subject: "Mathematics",
    question: "Which shape is round?",
    options: { A: "Square", B: "Circle", C: "Triangle", D: "Rectangle" },
    correctAnswer: "B",
    explanation: "Circles are round.",
  },
  {
    id: 162,
    subject: "English",
    question: "I have ___ eyes.",
    options: { A: "One", B: "Two", C: "Three", D: "Ten" },
    correctAnswer: "B",
    explanation: "Humans have two eyes.",
  },
  {
    id: 163,
    subject: "Hygiene",
    question: "Boil water before ___ it.",
    options: { A: "Washing", B: "Drinking", C: "Throwing", D: "Playing" },
    correctAnswer: "B",
    explanation: "Boiling kills germs in drinking water.",
  },
  {
    id: 164,
    subject: "Environmental",
    question: "Sheep give us ___.",
    options: { A: "Eggs", B: "Wool", C: "Honey", D: "Paper" },
    correctAnswer: "B",
    explanation: "Wool is the soft hair of sheep.",
  },
  {
    id: 165,
    subject: "Kiswahili",
    question: "Jina la nambari 2 ni ___.",
    options: { A: "Moja", B: "Mbili", C: "Tatu", D: "Nne" },
    correctAnswer: "B",
    explanation: "2 ni mbili.",
  },
  {
    id: 166,
    subject: "Mathematics",
    question: "10, 9, 8, __",
    options: { A: "7", B: "11", C: "6", D: "5" },
    correctAnswer: "A",
    explanation: "Counting backwards.",
  },
  {
    id: 167,
    subject: "English",
    question: "We use a ___ to write.",
    options: { A: "Spoon", B: "Pencil", C: "Fork", D: "Comb" },
    correctAnswer: "B",
    explanation: "Pencils are for writing.",
  },
  {
    id: 168,
    subject: "Hygiene",
    question: "Where do we throw rubbish?",
    options: {
      A: "On the road",
      B: "In the bin",
      C: "Under the tree",
      D: "In class",
    },
    correctAnswer: "B",
    explanation: "Bins keep the environment clean.",
  },
  {
    id: 169,
    subject: "Environmental",
    question: "A young hen is a ___.",
    options: { A: "Puppy", B: "Chick", C: "Kitten", D: "Calf" },
    correctAnswer: "B",
    explanation: "Chicks come from eggs laid by hens.",
  },
  {
    id: 170,
    subject: "Kiswahili",
    question: "Asante maana yake ni ___.",
    options: { A: "Please", B: "Thank you", C: "Sorry", D: "Welcome" },
    correctAnswer: "B",
    explanation: "Tunatoa shukrani kwa kusema asante.",
  },
  {
    id: 171,
    subject: "Mathematics",
    question: "What is 6 plus 1?",
    options: { A: "5", B: "7", C: "8", D: "61" },
    correctAnswer: "B",
    explanation: "6 + 1 = 7.",
  },
  {
    id: 172,
    subject: "English",
    question: "The sound of letter 'A' is ___.",
    options: { A: "ah", B: "buh", C: "cuh", D: "duh" },
    correctAnswer: "A",
    explanation: "A for Apple (ah).",
  },
  {
    id: 173,
    subject: "Hygiene",
    question: "Keep food ___ to stop flies.",
    options: { A: "Open", B: "Covered", C: "Hot", D: "Cold" },
    correctAnswer: "B",
    explanation: "Covering food prevents flies from landing.",
  },
  {
    id: 174,
    subject: "Environmental",
    question: "Which of these can fly?",
    options: { A: "Dog", B: "Bird", C: "Cat", D: "Fish" },
    correctAnswer: "B",
    explanation: "Birds have wings to fly.",
  },
  {
    id: 175,
    subject: "Kiswahili",
    question: "Nambari 3 kwa maneno ni ___.",
    options: { A: "Moja", B: "Mbili", C: "Tatu", D: "Nne" },
    correctAnswer: "C",
    explanation: "3 ni tatu.",
  },
  {
    id: 176,
    subject: "Mathematics",
    question: "Which is smaller: 10 or 20?",
    options: { A: "20", B: "10", C: "Both", D: "None" },
    correctAnswer: "B",
    explanation: "10 is less than 20.",
  },
  {
    id: 177,
    subject: "English",
    question: "A ___ builds furniture.",
    options: { A: "Doctor", B: "Carpenter", C: "Teacher", D: "Nurse" },
    correctAnswer: "B",
    explanation: "Carpenters work with wood.",
  },
  {
    id: 178,
    subject: "Hygiene",
    question: "Wash your hands ___ visiting the toilet.",
    options: { A: "Before", B: "After", C: "During", D: "Never" },
    correctAnswer: "B",
    explanation: "Clean hands after the toilet.",
  },
  {
    id: 179,
    subject: "Environmental",
    question: "The moon shines at ___.",
    options: { A: "Noon", B: "Night", C: "Day", D: "Morning" },
    correctAnswer: "B",
    explanation: "The moon appears in the night sky.",
  },
  {
    id: 180,
    subject: "Kiswahili",
    question: "Pua inatumika kwa ___.",
    options: { A: "Kuona", B: "Kunusa", C: "Kusikia", D: "Kuonja" },
    correctAnswer: "B",
    explanation: "Pua ni kwa ajili ya harufu.",
  },
  {
    id: 181,
    subject: "Mathematics",
    question: "What is 3 + 2?",
    options: { A: "4", B: "5", C: "6", D: "32" },
    correctAnswer: "B",
    explanation: "3 + 2 = 5.",
  },
  {
    id: 182,
    subject: "English",
    question: "Which one is a naming word?",
    options: { A: "Jump", B: "Table", C: "Run", D: "Sing" },
    correctAnswer: "B",
    explanation: "Table is a thing (noun).",
  },
  {
    id: 183,
    subject: "Hygiene",
    question: "We use a ___ to wipe our face.",
    options: { A: "Paper", B: "Handkerchief", C: "Sock", D: "Bag" },
    correctAnswer: "B",
    explanation: "Keep a handkerchief for cleanliness.",
  },
  {
    id: 184,
    subject: "Environmental",
    question: "A dog has ___ legs.",
    options: { A: "2", B: "4", C: "6", D: "0" },
    correctAnswer: "B",
    explanation: "Dogs walk on 4 legs.",
  },
  {
    id: 185,
    subject: "Kiswahili",
    question: "Rangi ya damu ni gani?",
    options: { A: "Nyekundu", B: "Nyeupe", C: "Kijani", D: "Nyeusi" },
    correctAnswer: "A",
    explanation: "Damu ni nyekundu.",
  },
  {
    id: 186,
    subject: "Mathematics",
    question: "Which number is between 1 and 3?",
    options: { A: "0", B: "2", C: "4", D: "5" },
    correctAnswer: "B",
    explanation: "Counting: 1, 2, 3.",
  },
  {
    id: 187,
    subject: "English",
    question: "The opposite of 'Long' is ___.",
    options: { A: "Short", B: "Big", C: "Small", D: "Tall" },
    correctAnswer: "A",
    explanation: "Short is the opposite of long.",
  },
  {
    id: 188,
    subject: "Hygiene",
    question: "Clean clothes make us look ___.",
    options: { A: "Bad", B: "Smart", C: "Dirty", D: "Sad" },
    correctAnswer: "B",
    explanation: "Cleanliness is smartness.",
  },
  {
    id: 189,
    subject: "Environmental",
    question: "Cows eat ___.",
    options: { A: "Meat", B: "Grass", C: "Sweets", D: "Paper" },
    correctAnswer: "B",
    explanation: "Cows are herbivores.",
  },
  {
    id: 190,
    subject: "Kiswahili",
    question: "Ulimi ni kwa ajili ya ___.",
    options: { A: "Kuona", B: "Kuonja", C: "Kunusa", D: "Kusikia" },
    correctAnswer: "B",
    explanation: "Ulimi huonja chakula.",
  },
  {
    id: 191,
    subject: "Mathematics",
    question: "What is 10 + 0?",
    options: { A: "0", B: "10", C: "1", D: "100" },
    correctAnswer: "B",
    explanation: "Zero added remains the same.",
  },
  {
    id: 192,
    subject: "English",
    question: "Which letter comes after 'C'?",
    options: { A: "B", B: "D", C: "E", D: "A" },
    correctAnswer: "B",
    explanation: "ABC D.",
  },
  {
    id: 193,
    subject: "Hygiene",
    question: "We use ___ to sleep at night.",
    options: { A: "Table", B: "Bed", C: "Chair", D: "Road" },
    correctAnswer: "B",
    explanation: "Beds are for sleeping.",
  },
  {
    id: 194,
    subject: "Environmental",
    question: "The color of the sky is ___.",
    options: { A: "Green", B: "Blue", C: "Red", D: "Yellow" },
    correctAnswer: "B",
    explanation: "The sky looks blue.",
  },
  {
    id: 195,
    subject: "Kiswahili",
    question: "Jina lingine la 'mama' ni ___.",
    options: { A: "Mwalimu", B: "Mzazi", C: "Baba", D: "Dada" },
    correctAnswer: "B",
    explanation: "Mama ni mzazi.",
  },
  {
    id: 196,
    subject: "Mathematics",
    question: "Count the sides of a circle.",
    options: { A: "1", B: "2", C: "3", D: "0" },
    correctAnswer: "D",
    explanation: "Circles have no straight sides.",
  },
  {
    id: 197,
    subject: "English",
    question: "Identify the action word: He is running.",
    options: { A: "He", B: "Is", C: "Running", D: "Fast" },
    correctAnswer: "C",
    explanation: "Running is the action.",
  },
  {
    id: 198,
    subject: "Hygiene",
    question: "We use a ___ to tidy hair.",
    options: { A: "Comb", B: "Spoon", C: "Pencil", D: "Toothbrush" },
    correctAnswer: "A",
    explanation: "Combs make hair neat.",
  },
  {
    id: 199,
    subject: "Environmental",
    question: "What do we get from bees?",
    options: { A: "Milk", B: "Honey", C: "Eggs", D: "Meat" },
    correctAnswer: "B",
    explanation: "Bees make honey.",
  },
  {
    id: 200,
    subject: "Kiswahili",
    question: "Nambari kumi ni namba gani?",
    options: { A: "1", B: "5", C: "10", D: "20" },
    correctAnswer: "C",
    explanation: "10 ni kumi.",
  },
  {
    id: 201,
    subject: "Mathematics",
    question: "What is 10 plus 2?",
    options: { A: "10", B: "12", C: "8", D: "20" },
    correctAnswer: "B",
    explanation: "10 + 2 = 12.",
  },
  {
    id: 202,
    subject: "English",
    question: "The name of my school starts with a ___ letter.",
    options: { A: "Small", B: "Big", C: "Red", D: "Short" },
    correctAnswer: "B",
    explanation:
      "Names of schools are proper nouns and start with capital letters.",
  },
  {
    id: 203,
    subject: "Hygiene",
    question: "We use ___ to clean our noses when we have a cold.",
    options: { A: "Socks", B: "Handkerchief", C: "Paper", D: "Leaves" },
    correctAnswer: "B",
    explanation: "A handkerchief is best for cleaning the nose.",
  },
  {
    id: 204,
    subject: "Environmental",
    question: "Which one is a source of water?",
    options: { A: "Tap", B: "Rain", C: "Cup", D: "Pot" },
    correctAnswer: "B",
    explanation: "Rain is a natural source of water.",
  },
  {
    id: 205,
    subject: "Kiswahili",
    question: "Jina la nambari 8 ni ___.",
    options: { A: "Saba", B: "Nane", C: "Tisa", D: "Kumi" },
    correctAnswer: "B",
    explanation: "8 ni nane kwa Kiswahili.",
  },
  {
    id: 206,
    subject: "Mathematics",
    question: "Which one is a triangle?",
    options: { A: "O", B: "☐", C: "△", D: "L" },
    correctAnswer: "C",
    explanation: "A triangle has three corners and three sides.",
  },
  {
    id: 207,
    subject: "English",
    question: "A ___ barks at strangers.",
    options: { A: "Cat", B: "Dog", C: "Hen", D: "Cow" },
    correctAnswer: "B",
    explanation: "Dogs bark to protect the home.",
  },
  {
    id: 208,
    subject: "Hygiene",
    question: "We should not share a ___ to avoid skin diseases.",
    options: { A: "Book", B: "Towel", C: "Chair", D: "Ball" },
    correctAnswer: "B",
    explanation: "Sharing towels can spread germs from one person to another.",
  },
  {
    id: 209,
    subject: "Environmental",
    question: "Plants give us ___ to eat.",
    options: { A: "Stones", B: "Food", C: "Soil", D: "Water" },
    correctAnswer: "B",
    explanation: "We get fruits and vegetables from plants.",
  },
  {
    id: 210,
    subject: "Kiswahili",
    question: "Kalamu hutumiwa kwa ___.",
    options: { A: "Kuandika", B: "Kulala", C: "Kukimbia", D: "Kula" },
    correctAnswer: "A",
    explanation: "Tunatumia kalamu kuandika kwenye daftari.",
  },
  {
    id: 211,
    subject: "Mathematics",
    question: "What is 5 minus 2?",
    options: { A: "3", B: "7", C: "2", D: "5" },
    correctAnswer: "A",
    explanation: "5 take away 2 is 3.",
  },
  {
    id: 212,
    subject: "English",
    question: "The plural of 'boy' is ___.",
    options: { A: "Boys", B: "Boyes", C: "Boies", D: "Boying" },
    correctAnswer: "A",
    explanation: "We add 's' to make the word plural.",
  },
  {
    id: 213,
    subject: "Hygiene",
    question: "Wash your hands ___ visiting the toilet.",
    options: { A: "Before", B: "After", C: "Never", D: "During" },
    correctAnswer: "B",
    explanation:
      "It is important to wash hands after using the toilet to remove germs.",
  },
  {
    id: 214,
    subject: "Environmental",
    question: "A hen has ___ legs.",
    options: { A: "4", B: "2", C: "6", D: "8" },
    correctAnswer: "B",
    explanation: "Birds like hens have two legs.",
  },
  {
    id: 215,
    subject: "Kiswahili",
    question: "Mwalimu hutufundisha ___.",
    options: { A: "Shuleni", B: "Sokoni", C: "Mtoni", D: "Misituni" },
    correctAnswer: "A",
    explanation: "Masomo hufanyika shuleni.",
  },
  {
    id: 216,
    subject: "Mathematics",
    question: "Which number comes after 19?",
    options: { A: "18", B: "20", C: "21", D: "10" },
    correctAnswer: "B",
    explanation: "Counting: 18, 19, 20.",
  },
  {
    id: 217,
    subject: "English",
    question: "Which word starts with sound 'p'?",
    options: { A: "Apple", B: "Pen", C: "Sun", D: "Cat" },
    correctAnswer: "B",
    explanation: "Pen starts with the letter 'p'.",
  },
  {
    id: 218,
    subject: "Hygiene",
    question: "Keep your hair ___.",
    options: {
      A: "Dirty",
      B: "Neat and combed",
      C: "Long and messy",
      D: "Wet",
    },
    correctAnswer: "B",
    explanation: "Combing hair keeps it looking smart.",
  },
  {
    id: 219,
    subject: "Environmental",
    question: "A car moves on the ___.",
    options: { A: "Water", B: "Road", C: "Air", D: "Trees" },
    correctAnswer: "B",
    explanation: "Cars are land transport.",
  },
  {
    id: 220,
    subject: "Kiswahili",
    question: "Jina la tunda hili 'Banana' kwa Kiswahili ni ___.",
    options: { A: "Embe", B: "Ndizi", C: "Chungwa", D: "Tofaa" },
    correctAnswer: "B",
    explanation: "Banana ni ndizi.",
  },
  {
    id: 221,
    subject: "Mathematics",
    question: "What is 3 plus 3?",
    options: { A: "5", B: "6", C: "9", D: "0" },
    correctAnswer: "B",
    explanation: "3 + 3 = 6.",
  },
  {
    id: 222,
    subject: "English",
    question: "The color of the sky is ___.",
    options: { A: "Green", B: "Blue", C: "Red", D: "Black" },
    correctAnswer: "B",
    explanation: "The sky is blue on a sunny day.",
  },
  {
    id: 223,
    subject: "Hygiene",
    question: "We use ___ to dry our bodies.",
    options: { A: "Paper", B: "Towel", C: "Shirt", D: "Blanket" },
    correctAnswer: "B",
    explanation: "A towel absorbs water after a bath.",
  },
  {
    id: 224,
    subject: "Environmental",
    question: "Which animal has no legs?",
    options: { A: "Snake", B: "Dog", C: "Goat", D: "Cat" },
    correctAnswer: "A",
    explanation: "Snakes crawl on their bellies.",
  },
  {
    id: 225,
    subject: "Kiswahili",
    question: "Baba wa mama yangu ni ___.",
    options: { A: "Bibi", B: "Babu", C: "Mjomba", D: "Shangazi" },
    correctAnswer: "B",
    explanation: "Baba wa mama ni babu.",
  },
  {
    id: 226,
    subject: "Mathematics",
    question: "A square has ___ sides.",
    options: { A: "3", B: "4", C: "5", D: "2" },
    correctAnswer: "B",
    explanation: "Squares have four equal sides.",
  },
  {
    id: 227,
    subject: "English",
    question: "Identify the naming word: The book is on the table.",
    options: { A: "On", B: "The", C: "Book", D: "Is" },
    correctAnswer: "C",
    explanation: "Book is a noun (naming word).",
  },
  {
    id: 228,
    subject: "Hygiene",
    question: "We should sleep on a clean ___.",
    options: { A: "Chair", B: "Bed", C: "Floor", D: "Table" },
    correctAnswer: "B",
    explanation: "A clean bed helps us sleep well.",
  },
  {
    id: 229,
    subject: "Environmental",
    question: "Which of these is used when it is raining?",
    options: { A: "Umbrella", B: "Sunglasses", C: "Cap", D: "Vest" },
    correctAnswer: "A",
    explanation: "Umbrellas keep us dry.",
  },
  {
    id: 230,
    subject: "Kiswahili",
    question: "Asante ni neno la ___.",
    options: { A: "Heshima", B: "Hasira", C: "Kulia", D: "Kupigana" },
    correctAnswer: "A",
    explanation: "Asante huonyesha shukrani.",
  },
  {
    id: 231,
    subject: "Mathematics",
    question: "What is 10 minus 0?",
    options: { A: "0", B: "10", C: "1", D: "100" },
    correctAnswer: "B",
    explanation: "Any number minus zero stays the same.",
  },
  {
    id: 232,
    subject: "English",
    question: "Which one is a capital letter?",
    options: { A: "a", B: "M", C: "e", D: "r" },
    correctAnswer: "B",
    explanation: "M is uppercase.",
  },
  {
    id: 233,
    subject: "Hygiene",
    question: "Long nails should be ___.",
    options: { A: "Hidden", B: "Cut", C: "Dirty", D: "Bitten" },
    correctAnswer: "B",
    explanation: "Cutting nails keeps them clean.",
  },
  {
    id: 234,
    subject: "Environmental",
    question: "Which animal lives in a kennel?",
    options: { A: "Dog", B: "Cat", C: "Cow", D: "Pig" },
    correctAnswer: "A",
    explanation: "A dog's house is called a kennel.",
  },
  {
    id: 235,
    subject: "Kiswahili",
    question: "Rangi ya maziwa ni ___.",
    options: { A: "Nyeusi", B: "Nyekundu", C: "Nyeupe", D: "Kijani" },
    correctAnswer: "C",
    explanation: "Maziwa ni meupe.",
  },
  {
    id: 236,
    subject: "Mathematics",
    question: "How many months are in a year?",
    options: { A: "7", B: "12", C: "10", D: "30" },
    correctAnswer: "B",
    explanation: "There are 12 months from January to December.",
  },
  {
    id: 237,
    subject: "English",
    question: "The opposite of 'In' is ___.",
    options: { A: "On", B: "Under", C: "Out", D: "Up" },
    correctAnswer: "C",
    explanation: "In and Out are opposites.",
  },
  {
    id: 238,
    subject: "Hygiene",
    question: "We use a ___ to sweep the floor.",
    options: { A: "Broom", B: "Spoon", C: "Comb", D: "Knife" },
    correctAnswer: "A",
    explanation: "Brooms are for sweeping dirt.",
  },
  {
    id: 239,
    subject: "Environmental",
    question: "Which bird gives us eggs?",
    options: { A: "Eagle", B: "Hen", C: "Crow", D: "Owl" },
    correctAnswer: "B",
    explanation: "Hens are kept for eggs and meat.",
  },
  {
    id: 240,
    subject: "Kiswahili",
    question: "Tunasoma kwa kutumia ___ letu.",
    options: { A: "Macho", B: "Masikio", C: "Miguu", D: "Mikono" },
    correctAnswer: "A",
    explanation: "Macho hutusaidia kuona maandishi.",
  },
  {
    id: 241,
    subject: "Mathematics",
    question: "What is 8 plus 2?",
    options: { A: "6", B: "10", C: "8", D: "2" },
    correctAnswer: "B",
    explanation: "8 + 2 = 10.",
  },
  {
    id: 242,
    subject: "English",
    question: "A young dog is called a ___.",
    options: { A: "Kitten", B: "Puppy", C: "Calf", D: "Chick" },
    correctAnswer: "B",
    explanation: "Baby dogs are puppies.",
  },
  {
    id: 243,
    subject: "Hygiene",
    question: "Dirty socks smell ___.",
    options: { A: "Good", B: "Bad", C: "Sweet", D: "Nice" },
    correctAnswer: "B",
    explanation: "Sweat and dirt make socks smell bad.",
  },
  {
    id: 244,
    subject: "Environmental",
    question: "Which part of the plant grows under the soil?",
    options: { A: "Leaf", B: "Flower", C: "Roots", D: "Fruit" },
    correctAnswer: "C",
    explanation: "Roots stay underground.",
  },
  {
    id: 245,
    subject: "Kiswahili",
    question: "Sisi hula kwa kutumia ___.",
    options: { A: "Mdomo", B: "Pua", C: "Sikio", D: "Jicho" },
    correctAnswer: "A",
    explanation: "Chakula hupitia mdomoni.",
  },
  {
    id: 246,
    subject: "Mathematics",
    question: "Count backwards: 10, 9, 8, __",
    options: { A: "11", B: "7", C: "6", D: "5" },
    correctAnswer: "B",
    explanation: "Before 8 comes 7.",
  },
  {
    id: 247,
    subject: "English",
    question: "Which vowel is missing in 'c_p'?",
    options: { A: "u", B: "z", C: "p", D: "k" },
    correctAnswer: "A",
    explanation: "Cup is spelled with 'u'.",
  },
  {
    id: 248,
    subject: "Hygiene",
    question: "We use ___ to clean our teeth.",
    options: { A: "Toothbrush", B: "Broom", C: "Spoon", D: "Comb" },
    correctAnswer: "A",
    explanation: "Toothbrushes are for dental care.",
  },
  {
    id: 249,
    subject: "Environmental",
    question: "A fish uses ___ to swim.",
    options: { A: "Legs", B: "Fins", C: "Wings", D: "Hands" },
    correctAnswer: "B",
    explanation: "Fins help fish move in water.",
  },
  {
    id: 250,
    subject: "Kiswahili",
    question: "Huyu ni ___ wangu (Sister).",
    options: { A: "Kaka", B: "Dada", C: "Mjomba", D: "Babu" },
    correctAnswer: "B",
    explanation: "Sister ni dada.",
  },

  {
    id: 251,
    subject: "Mathematics",
    question: "What is 7 plus 3?",
    options: { A: "9", B: "10", C: "11", D: "73" },
    correctAnswer: "B",
    explanation: "7 + 3 = 10.",
  },
  {
    id: 252,
    subject: "English",
    question: "Which sound does a cow make?",
    options: { A: "Moo", B: "Meow", C: "Bark", D: "Baa" },
    correctAnswer: "A",
    explanation: "Cows make the 'moo' sound.",
  },
  {
    id: 253,
    subject: "Hygiene",
    question: "We use ___ to wash our hair.",
    options: { A: "Oil", B: "Shampoo", C: "Salt", D: "Sand" },
    correctAnswer: "B",
    explanation: "Shampoo is used to clean the hair and scalp.",
  },
  {
    id: 254,
    subject: "Environmental",
    question: "Plants need water and ___ to grow.",
    options: { A: "Milk", B: "Sunlight", C: "Soda", D: "Tea" },
    correctAnswer: "B",
    explanation: "Sunlight is essential for plant growth.",
  },
  {
    id: 255,
    subject: "Kiswahili",
    question: "Tunasikia kwa kutumia ___ zetu.",
    options: { A: "Macho", B: "Masikio", C: "Pua", D: "Miguu" },
    correctAnswer: "B",
    explanation: "Masikio ni kwa ajili ya kusikia sauti.",
  },
  {
    id: 256,
    subject: "Mathematics",
    question: "Which shape has 3 sides?",
    options: { A: "Square", B: "Triangle", C: "Circle", D: "Rectangle" },
    correctAnswer: "B",
    explanation: "A triangle is a three-sided shape.",
  },
  {
    id: 257,
    subject: "English",
    question: "The plural of 'cat' is ___.",
    options: { A: "Cats", B: "Catted", C: "Catting", D: "Kitten" },
    correctAnswer: "A",
    explanation: "Add 's' to make it plural.",
  },
  {
    id: 258,
    subject: "Hygiene",
    question: "We should tidy our ___ after waking up.",
    options: { A: "Kitchen", B: "Bed", C: "Garden", D: "Road" },
    correctAnswer: "B",
    explanation: "Making your bed is a good morning habit.",
  },
  {
    id: 259,
    subject: "Environmental",
    question: "Which animal has a long neck?",
    options: { A: "Lion", B: "Giraffe", C: "Elephant", D: "Hippo" },
    correctAnswer: "B",
    explanation: "Giraffes have the longest necks to reach tree leaves.",
  },
  {
    id: 260,
    subject: "Kiswahili",
    question: "Nambari '5' kwa Kiswahili ni ___.",
    options: { A: "Tano", B: "Sita", C: "Nne", D: "Tatu" },
    correctAnswer: "A",
    explanation: "5 ni tano.",
  },
  {
    id: 261,
    subject: "Mathematics",
    question: "What is 4 minus 4?",
    options: { A: "4", B: "0", C: "8", D: "1" },
    correctAnswer: "B",
    explanation: "Subtracting a number from itself gives zero.",
  },
  {
    id: 262,
    subject: "English",
    question: "Which word rhymes with 'boy'?",
    options: { A: "Toy", B: "Ball", C: "Cat", D: "Sun" },
    correctAnswer: "A",
    explanation: "Boy and Toy have the same ending sound.",
  },
  {
    id: 263,
    subject: "Hygiene",
    question: "We use a ___ when coughing to stop germs.",
    options: { A: "Book", B: "Handkerchief", C: "Hand", D: "Paper" },
    correctAnswer: "B",
    explanation: "Handkerchiefs help prevent the spread of germs.",
  },
  {
    id: 264,
    subject: "Environmental",
    question: "A sheep gives us ___.",
    options: { A: "Eggs", B: "Wool", C: "Honey", D: "Milk" },
    correctAnswer: "B",
    explanation: "Wool is the soft hair of a sheep used for clothes.",
  },
  {
    id: 265,
    subject: "Kiswahili",
    question: "Jua hutoa ___ mchana.",
    options: { A: "Baridi", B: "Mwanga", C: "Giza", D: "Mvua" },
    correctAnswer: "B",
    explanation: "Jua huangaza ulimwengu.",
  },
  {
    id: 266,
    subject: "Mathematics",
    question: "12, 13, 14, __",
    options: { A: "10", B: "15", C: "16", D: "11" },
    correctAnswer: "B",
    explanation: "The next number after 14 is 15.",
  },
  {
    id: 267,
    subject: "English",
    question: "Opposite of 'hot' is ___.",
    options: { A: "Warm", B: "Cold", C: "Big", D: "Sun" },
    correctAnswer: "B",
    explanation: "Hot and cold are opposites.",
  },
  {
    id: 268,
    subject: "Hygiene",
    question: "We should bathe ___.",
    options: {
      A: "Every day",
      B: "Once a week",
      C: "Once a month",
      D: "Never",
    },
    correctAnswer: "A",
    explanation: "Daily bathing keeps the body clean.",
  },
  {
    id: 269,
    subject: "Environmental",
    question: "Which animal is the 'King of the Jungle'?",
    options: { A: "Elephant", B: "Lion", C: "Giraffe", D: "Zebra" },
    correctAnswer: "B",
    explanation: "The lion is known as the king of the jungle.",
  },
  {
    id: 270,
    subject: "Kiswahili",
    question: "Habari ya ___ (evening)?",
    options: { A: "Asubuhi", B: "Jioni", C: "Mchana", D: "Usiku" },
    correctAnswer: "B",
    explanation: "Jioni ni evening.",
  },
  {
    id: 271,
    subject: "Mathematics",
    question: "How many legs does a spider have?",
    options: { A: "4", B: "6", C: "8", D: "2" },
    correctAnswer: "C",
    explanation: "Spiders are arachnids and have 8 legs.",
  },
  {
    id: 272,
    subject: "English",
    question: "The baby is ___ (sleep).",
    options: { A: "Sleep", B: "Sleeping", C: "Slept", D: "Sleeps" },
    correctAnswer: "B",
    explanation: "Use 'ing' for an action happening now.",
  },
  {
    id: 273,
    subject: "Hygiene",
    question: "Dirty water contains ___.",
    options: { A: "Sugar", B: "Germs", C: "Salt", D: "Milk" },
    correctAnswer: "B",
    explanation: "Germs in dirty water can make you sick.",
  },
  {
    id: 274,
    subject: "Environmental",
    question: "We get eggs from ___.",
    options: { A: "Cows", B: "Hens", C: "Dogs", D: "Cats" },
    correctAnswer: "B",
    explanation: "Chickens (hens) lay eggs.",
  },
  {
    id: 275,
    subject: "Kiswahili",
    question: "Mama na Baba ni ___ wangu.",
    options: { A: "Walimu", B: "Wazazi", C: "Wageni", D: "Watoto" },
    correctAnswer: "B",
    explanation: "Wazazi ni mama na baba.",
  },
  {
    id: 276,
    subject: "Mathematics",
    question: "What is 6 + 1?",
    options: { A: "5", B: "7", C: "8", D: "61" },
    correctAnswer: "B",
    explanation: "6 + 1 = 7.",
  },
  {
    id: 277,
    subject: "English",
    question: "A __ builds houses using stones.",
    options: { A: "Mason", B: "Tailor", C: "Doctor", D: "Driver" },
    correctAnswer: "A",
    explanation: "Masons build walls and houses.",
  },
  {
    id: 278,
    subject: "Hygiene",
    question: "Boil water before ___.",
    options: { A: "Washing", B: "Drinking", C: "Playing", D: "Throwing" },
    correctAnswer: "B",
    explanation: "Boiling water kills harmful germs.",
  },
  {
    id: 279,
    subject: "Environmental",
    question: "The color of the Kenyan flag at the top is ___.",
    options: { A: "Red", B: "Black", C: "Green", D: "White" },
    correctAnswer: "B",
    explanation: "The top color is black.",
  },
  {
    id: 280,
    subject: "Kiswahili",
    question: "Ulimi hutusaidia ___.",
    options: { A: "Kuonja", B: "Kuona", C: "Kusikia", D: "Kunusa" },
    correctAnswer: "A",
    explanation: "Ulimi ni kiungo cha kuonja.",
  },
  {
    id: 281,
    subject: "Mathematics",
    question: "Which number is greater: 10 or 5?",
    options: { A: "5", B: "10", C: "None", D: "Both" },
    correctAnswer: "B",
    explanation: "10 is more than 5.",
  },
  {
    id: 282,
    subject: "English",
    question: "I have ___ ears.",
    options: { A: "One", B: "Two", C: "Three", D: "Ten" },
    correctAnswer: "B",
    explanation: "Humans have two ears for hearing.",
  },
  {
    id: 283,
    subject: "Hygiene",
    question: "Where do we throw rubbish?",
    options: {
      A: "In the bin",
      B: "On the floor",
      C: "Under the desk",
      D: "In the garden",
    },
    correctAnswer: "A",
    explanation: "Always use a dustbin for litter.",
  },
  {
    id: 284,
    subject: "Environmental",
    question: "A young hen is called a ___.",
    options: { A: "Puppy", B: "Chick", C: "Kitten", D: "Calf" },
    correctAnswer: "B",
    explanation: "Hens lay eggs that hatch into chicks.",
  },
  {
    id: 285,
    subject: "Kiswahili",
    question: "Jina la nambari 10 ni ___.",
    options: { A: "Kumi", B: "Tano", C: "Moja", D: "Sita" },
    correctAnswer: "A",
    explanation: "10 ni kumi.",
  },
  {
    id: 286,
    subject: "Mathematics",
    question: "What shape is a ball?",
    options: { A: "Square", B: "Triangle", C: "Circle", D: "Rectangle" },
    correctAnswer: "C",
    explanation: "Balls are round like circles.",
  },
  {
    id: 287,
    subject: "English",
    question: "A ___ builds furniture from wood.",
    options: { A: "Doctor", B: "Carpenter", C: "Teacher", D: "Nurse" },
    correctAnswer: "B",
    explanation: "Carpenters make chairs, tables, and beds.",
  },
  {
    id: 288,
    subject: "Hygiene",
    question: "We use a ___ to wipe our face.",
    options: { A: "Towel", B: "Book", C: "Sleeve", D: "Sock" },
    correctAnswer: "A",
    explanation: "A clean towel is used after washing the face.",
  },
  {
    id: 289,
    subject: "Environmental",
    question: "We get honey from ___.",
    options: { A: "Ants", B: "Bees", C: "Flies", D: "Spiders" },
    correctAnswer: "B",
    explanation: "Bees make honey in hives.",
  },
  {
    id: 290,
    subject: "Kiswahili",
    question: "Pua inatumiwa kwa ___.",
    options: { A: "Kunusa", B: "Kuona", C: "Kuonja", D: "Kusikia" },
    correctAnswer: "A",
    explanation: "Tunatumia pua kunusa harufu.",
  },
  {
    id: 291,
    subject: "Mathematics",
    question: "9, 8, 7, __",
    options: { A: "10", B: "6", C: "5", D: "0" },
    correctAnswer: "B",
    explanation: "Counting backwards from 7 leads to 6.",
  },
  {
    id: 292,
    subject: "English",
    question: "Which vowel comes after 'e'?",
    options: { A: "a", B: "i", C: "o", D: "u" },
    correctAnswer: "B",
    explanation: "The vowels are a, e, i, o, u.",
  },
  {
    id: 293,
    subject: "Hygiene",
    question: "Clean clothes make us look ___.",
    options: { A: "Smart", B: "Dirty", C: "Bad", D: "Sad" },
    correctAnswer: "A",
    explanation: "Neat clothes make a person look smart.",
  },
  {
    id: 294,
    subject: "Environmental",
    question: "Which of these is used to transport people on water?",
    options: { A: "Car", B: "Boat", C: "Airplane", D: "Bicycle" },
    correctAnswer: "B",
    explanation: "Boats and ships travel on water.",
  },
  {
    id: 295,
    subject: "Kiswahili",
    question: "Tunasema ___ ukipewa zawadi.",
    options: { A: "Asante", B: "Pole", C: "Hapana", D: "Habari" },
    correctAnswer: "A",
    explanation: "Asante ni neno la shukrani.",
  },
  {
    id: 296,
    subject: "Mathematics",
    question: "What is 15 + 1?",
    options: { A: "14", B: "16", C: "17", D: "151" },
    correctAnswer: "B",
    explanation: "15 plus 1 equals 16.",
  },
  {
    id: 297,
    subject: "English",
    question: "I have ___ nose.",
    options: { A: "one", B: "two", C: "three", D: "ten" },
    correctAnswer: "A",
    explanation: "Humans have one nose for breathing.",
  },
  {
    id: 298,
    subject: "Hygiene",
    question: "Wash your hands ___ eating.",
    options: { A: "Before", B: "After", C: "Never", D: "During" },
    correctAnswer: "A",
    explanation: "Always wash before handling food.",
  },
  {
    id: 299,
    subject: "Environmental",
    question: "Which part of the plant is green?",
    options: { A: "Root", B: "Leaf", C: "Flower", D: "Stem" },
    correctAnswer: "B",
    explanation: "Most leaves are green because of chlorophyll.",
  },
  {
    id: 300,
    subject: "Kiswahili",
    question: "Macho hutumiwa kwa ___.",
    options: { A: "Kusikia", B: "Kuona", C: "Kunusa", D: "Kuonja" },
    correctAnswer: "B",
    explanation: "Tunatumia macho kuona ulimwengu.",
  },
  {
    id: 301,
    subject: "Mathematics",
    question: "What is 10 - 2?",
    options: { A: "12", B: "8", C: "7", D: "5" },
    correctAnswer: "B",
    explanation: "10 minus 2 equals 8.",
  },
  {
    id: 302,
    subject: "English",
    question: "The name of a person starts with a ___ letter.",
    options: { A: "Small", B: "Capital", C: "Red", D: "Short" },
    correctAnswer: "B",
    explanation: "Names are proper nouns.",
  },
  {
    id: 303,
    subject: "Hygiene",
    question: "Where do we go when our teeth ache?",
    options: { A: "Market", B: "Dentist", C: "School", D: "Field" },
    correctAnswer: "B",
    explanation: "A dentist is a doctor for teeth.",
  },
  {
    id: 304,
    subject: "Environmental",
    question: "Which animal has a trunk?",
    options: { A: "Cat", B: "Elephant", C: "Dog", D: "Lion" },
    correctAnswer: "B",
    explanation: "The elephant has a long trunk.",
  },
  {
    id: 305,
    subject: "Kiswahili",
    question: "Kalamu, kitabu na ___ (ruler).",
    options: { A: "Rula", B: "Peni", C: "Meza", D: "Kiti" },
    correctAnswer: "A",
    explanation: "Ruler kwa Kiswahili ni rula.",
  },
  {
    id: 306,
    subject: "Mathematics",
    question: "Count the sides of a triangle.",
    options: { A: "1", B: "2", C: "3", D: "4" },
    correctAnswer: "C",
    explanation: "A triangle has three sides.",
  },
  {
    id: 307,
    subject: "English",
    question: "Which one is an action word?",
    options: { A: "Jump", B: "Table", C: "Red", D: "Small" },
    correctAnswer: "A",
    explanation: "Jumping is an action.",
  },
  {
    id: 308,
    subject: "Hygiene",
    question: "We use ___ to cut long hair.",
    options: { A: "Knife", B: "Scissors", C: "Spoon", D: "Stone" },
    correctAnswer: "B",
    explanation: "Scissors or clippers are used for hair.",
  },
  {
    id: 309,
    subject: "Environmental",
    question: "What color is at the bottom of the Kenyan flag?",
    options: { A: "Black", B: "Red", C: "Green", D: "White" },
    correctAnswer: "C",
    explanation: "The bottom stripe is green.",
  },
  {
    id: 310,
    subject: "Kiswahili",
    question: "Huyu ni ___ wangu (Brother).",
    options: { A: "Dada", B: "Kaka", C: "Mama", D: "Bibi" },
    correctAnswer: "B",
    explanation: "Brother ni kaka.",
  },
  {
    id: 311,
    subject: "Mathematics",
    question: "What is 3 + 4?",
    options: { A: "6", B: "7", C: "8", D: "34" },
    correctAnswer: "B",
    explanation: "3 + 4 = 7.",
  },
  {
    id: 312,
    subject: "English",
    question: "The color of milk is ___.",
    options: { A: "Blue", B: "White", C: "Green", D: "Red" },
    correctAnswer: "B",
    explanation: "Milk is white.",
  },
  {
    id: 313,
    subject: "Hygiene",
    question: "We use a ___ to tidy our hair.",
    options: { A: "Comb", B: "Spoon", C: "Pencil", D: "Soap" },
    correctAnswer: "A",
    explanation: "Combs make hair neat.",
  },
  {
    id: 314,
    subject: "Environmental",
    question: "Which of these is a tame animal?",
    options: { A: "Lion", B: "Cat", C: "Snake", D: "Leopard" },
    correctAnswer: "B",
    explanation: "Cats are pets.",
  },
  {
    id: 315,
    subject: "Kiswahili",
    question: "Lala ___ (peacefully).",
    options: { A: "Salama", B: "Habari", C: "Asante", D: "Pole" },
    correctAnswer: "A",
    explanation: "Tunatakiana lala salama.",
  },
  {
    id: 316,
    subject: "Mathematics",
    question: "What number comes after 5?",
    options: { A: "4", B: "6", C: "7", D: "1" },
    correctAnswer: "B",
    explanation: "Counting: 4, 5, 6.",
  },
  {
    id: 317,
    subject: "English",
    question: "I sleep on a ___.",
    options: { A: "Bed", B: "Table", C: "Chair", D: "Desk" },
    correctAnswer: "A",
    explanation: "Beds are for resting.",
  },
  {
    id: 318,
    subject: "Hygiene",
    question: "Where do we bathe?",
    options: { A: "Kitchen", B: "Bathroom", C: "Bedroom", D: "Store" },
    correctAnswer: "B",
    explanation: "Bathrooms are for bathing.",
  },
  {
    id: 319,
    subject: "Environmental",
    question: "Bees give us ___.",
    options: { A: "Milk", B: "Honey", C: "Eggs", D: "Meat" },
    correctAnswer: "B",
    explanation: "Bees make honey.",
  },
  {
    id: 320,
    subject: "Kiswahili",
    question: "Asante maana yake ni ___.",
    options: { A: "Sorry", B: "Thank you", C: "Please", D: "Welcome" },
    correctAnswer: "B",
    explanation: "Asante ni kutoa shukrani.",
  },
  {
    id: 321,
    subject: "Mathematics",
    question: "What is 2 + 2?",
    options: { A: "2", B: "4", C: "22", D: "0" },
    correctAnswer: "B",
    explanation: "2 + 2 = 4.",
  },
  {
    id: 322,
    subject: "English",
    question: "Which sound does a cat make?",
    options: { A: "Meow", B: "Bark", C: "Moo", D: "Hiss" },
    correctAnswer: "A",
    explanation: "Cats meow.",
  },
  {
    id: 323,
    subject: "Hygiene",
    question: "We use ___ to wash hands.",
    options: { A: "Soap", B: "Salt", C: "Sugar", D: "Sand" },
    correctAnswer: "A",
    explanation: "Soap kills germs.",
  },
  {
    id: 324,
    subject: "Environmental",
    question: "Which animal barks?",
    options: { A: "Cat", B: "Dog", C: "Cow", D: "Hen" },
    correctAnswer: "B",
    explanation: "Dogs bark.",
  },
  {
    id: 325,
    subject: "Kiswahili",
    question: "Jina la nambari 1 ni ___.",
    options: { A: "Moja", B: "Mbili", C: "Tatu", D: "Nne" },
    correctAnswer: "A",
    explanation: "1 ni moja.",
  },
  {
    id: 326,
    subject: "Mathematics",
    question: "What is 10 minus 5?",
    options: { A: "5", B: "10", C: "15", D: "0" },
    correctAnswer: "A",
    explanation: "10 - 5 = 5.",
  },
  {
    id: 327,
    subject: "English",
    question: "Which letter comes after 'F'?",
    options: { A: "E", B: "G", C: "H", D: "D" },
    correctAnswer: "B",
    explanation: "Counting letters: E, F, G.",
  },
  {
    id: 328,
    subject: "Hygiene",
    question: "We should wash our hands ___ using the toilet.",
    options: { A: "Before", B: "During", C: "After", D: "Never" },
    correctAnswer: "C",
    explanation: "Always wash hands after the toilet to stay clean.",
  },
  {
    id: 329,
    subject: "Environmental",
    question: "Which animal gives us wool?",
    options: { A: "Goat", B: "Sheep", C: "Cow", D: "Pig" },
    correctAnswer: "B",
    explanation: "Sheep provide wool for making sweaters.",
  },
  {
    id: 330,
    subject: "Kiswahili",
    question: "Rangi ya damu ni gani?",
    options: { A: "Nyekundu", B: "Nyeupe", C: "Kijani", D: "Nyeusi" },
    correctAnswer: "A",
    explanation: "Damu ni rangi ya nyekundu.",
  },
  {
    id: 331,
    subject: "Mathematics",
    question: "What is 0 + 9?",
    options: { A: "0", B: "9", C: "90", D: "1" },
    correctAnswer: "B",
    explanation: "Zero added to any number doesn't change it.",
  },
  {
    id: 332,
    subject: "English",
    question: "I use my ___ to smell flowers.",
    options: { A: "Eyes", B: "Ears", C: "Nose", D: "Mouth" },
    correctAnswer: "C",
    explanation: "The nose is for smelling.",
  },
  {
    id: 333,
    subject: "Hygiene",
    question: "We use ___ to clean our bodies during a bath.",
    options: { A: "Salt", B: "Soap", C: "Sugar", D: "Sand" },
    correctAnswer: "B",
    explanation: "Soap removes dirt and sweat.",
  },
  {
    id: 334,
    subject: "Environmental",
    question: "Which of these is a fruit?",
    options: { A: "Cabbage", B: "Mango", C: "Onion", D: "Potato" },
    correctAnswer: "B",
    explanation: "Mango is a sweet, edible fruit.",
  },
  {
    id: 335,
    subject: "Kiswahili",
    question: "Tunasoma kwa kutumia ___.",
    options: { A: "Macho", B: "Masikio", C: "Miguu", D: "Mikono" },
    correctAnswer: "A",
    explanation: "Tunatumia macho kuona maneno.",
  },
  {
    id: 336,
    subject: "Mathematics",
    question: "Which number is between 4 and 6?",
    options: { A: "3", B: "5", C: "7", D: "8" },
    correctAnswer: "B",
    explanation: "The counting sequence is 4, 5, 6.",
  },
  {
    id: 337,
    subject: "English",
    question: "The plural of 'dog' is ___.",
    options: { A: "Dogging", B: "Dogs", C: "Doged", D: "Puppy" },
    correctAnswer: "B",
    explanation: "Add 's' to make dog plural.",
  },
  {
    id: 338,
    subject: "Hygiene",
    question: "A ___ treats sick people.",
    options: { A: "Teacher", B: "Doctor", C: "Farmer", D: "Driver" },
    correctAnswer: "B",
    explanation: "Doctors give us medicine to get well.",
  },
  {
    id: 339,
    subject: "Environmental",
    question: "Which animal has a trunk?",
    options: { A: "Lion", B: "Dog", C: "Elephant", D: "Cat" },
    correctAnswer: "C",
    explanation: "Elephants use their long trunks for many things.",
  },
  {
    id: 340,
    subject: "Kiswahili",
    question: "Salama ya usiku ni ___.",
    options: { A: "Habari", B: "Lala salama", C: "Asante", D: "Pole" },
    correctAnswer: "B",
    explanation: "Lala salama ni salamu ya usiku.",
  },
  {
    id: 341,
    subject: "Mathematics",
    question: "What is 5 + 5?",
    options: { A: "5", B: "10", C: "15", D: "20" },
    correctAnswer: "B",
    explanation: "5 plus 5 equals 10.",
  },
  {
    id: 342,
    subject: "English",
    question: "Which sound does a bird make?",
    options: { A: "Moo", B: "Chirp", C: "Bark", D: "Meow" },
    correctAnswer: "B",
    explanation: "Birds chirp or sing.",
  },
  {
    id: 343,
    subject: "Hygiene",
    question: "Clean clothes make us look ___.",
    options: { A: "Dirty", B: "Smart", C: "Bad", D: "Sad" },
    correctAnswer: "B",
    explanation: "Smartness comes from cleanliness.",
  },
  {
    id: 344,
    subject: "Environmental",
    question: "We get milk from a ___.",
    options: { A: "Cat", B: "Cow", C: "Dog", D: "Hen" },
    correctAnswer: "B",
    explanation: "Cows are domestic animals that give us milk.",
  },
  {
    id: 345,
    subject: "Kiswahili",
    question: "Baba wa baba yangu ni ___.",
    options: { A: "Bibi", B: "Babu", C: "Mjomba", D: "Dada" },
    correctAnswer: "B",
    explanation: "Baba wa baba ni babu.",
  },
  {
    id: 346,
    subject: "Mathematics",
    question: "Which shape has 4 equal sides?",
    options: { A: "Circle", B: "Triangle", C: "Square", D: "Oval" },
    correctAnswer: "C",
    explanation: "A square's sides are all the same length.",
  },
  {
    id: 347,
    subject: "English",
    question: "Which word starts with 'm'?",
    options: { A: "Sun", B: "Moon", C: "Star", D: "Sky" },
    correctAnswer: "B",
    explanation: "Moon starts with the letter 'm'.",
  },
  {
    id: 348,
    subject: "Hygiene",
    question: "We use a ___ to wipe our noses.",
    options: { A: "Sock", B: "Handkerchief", C: "Leaf", D: "Book" },
    correctAnswer: "B",
    explanation: "Use a handkerchief to stay clean.",
  },
  {
    id: 349,
    subject: "Environmental",
    question: "Which animal barks?",
    options: { A: "Cat", B: "Cow", C: "Dog", D: "Lion" },
    correctAnswer: "C",
    explanation: "Dogs bark to guard the house.",
  },
  {
    id: 350,
    subject: "Kiswahili",
    question: "Jina la nambari 2 ni ___.",
    options: { A: "Moja", B: "Mbili", C: "Tatu", D: "Nne" },
    correctAnswer: "B",
    explanation: "2 ni mbili.",
  },
  {
    id: 351,
    subject: "Mathematics",
    question: "What is 8 minus 3?",
    options: { A: "5", B: "11", C: "8", D: "3" },
    correctAnswer: "A",
    explanation: "8 - 3 = 5.",
  },
  {
    id: 352,
    subject: "English",
    question: "I see with my ___.",
    options: { A: "Ears", B: "Eyes", C: "Nose", D: "Mouth" },
    correctAnswer: "B",
    explanation: "Eyes are for seeing.",
  },
  {
    id: 353,
    subject: "Hygiene",
    question: "Wash your face with ___ and water.",
    options: { A: "Sugar", B: "Soap", C: "Salt", D: "Sand" },
    correctAnswer: "B",
    explanation: "Soap cleans the skin properly.",
  },
  {
    id: 354,
    subject: "Environmental",
    question: "A plant grows from a ___.",
    options: { A: "Stone", B: "Seed", C: "Leaf", D: "Stick" },
    correctAnswer: "B",
    explanation: "Seeds grow into new plants.",
  },
  {
    id: 355,
    subject: "Kiswahili",
    question: "Huyu ni ___ wangu (Mother).",
    options: { A: "Baba", B: "Mama", C: "Kaka", D: "Dada" },
    correctAnswer: "B",
    explanation: "Mother ni mama.",
  },
  {
    id: 356,
    subject: "Mathematics",
    question: "What is 1 + 1 + 1?",
    options: { A: "1", B: "2", C: "3", D: "111" },
    correctAnswer: "C",
    explanation: "Three ones make three.",
  },
  {
    id: 357,
    subject: "English",
    question: "The color of an apple is usually ___.",
    options: { A: "Blue", B: "Red", C: "Pink", D: "Black" },
    correctAnswer: "B",
    explanation: "Most apples are red.",
  },
  {
    id: 358,
    subject: "Hygiene",
    question: "Long nails hide ___.",
    options: { A: "Germs", B: "Sweets", C: "Money", D: "Books" },
    correctAnswer: "A",
    explanation: "Dirt and germs live under long nails.",
  },
  {
    id: 359,
    subject: "Environmental",
    question: "We wear a sweater when it is ___.",
    options: { A: "Hot", B: "Cold", C: "Sunny", D: "Dry" },
    correctAnswer: "B",
    explanation: "Sweaters keep us warm.",
  },
  {
    id: 360,
    subject: "Kiswahili",
    question: "Habari ya ___ (morning)?",
    options: { A: "Asubuhi", B: "Jioni", C: "Mchana", D: "Usiku" },
    correctAnswer: "A",
    explanation: "Asubuhi ni morning.",
  },
  {
    id: 361,
    subject: "Mathematics",
    question: "Which number is smaller: 10 or 2?",
    options: { A: "10", B: "2", C: "Both", D: "None" },
    correctAnswer: "B",
    explanation: "2 is less than 10.",
  },
  {
    id: 362,
    subject: "English",
    question: "A young cat is a ___.",
    options: { A: "Puppy", B: "Kitten", C: "Calf", D: "Chick" },
    correctAnswer: "B",
    explanation: "Baby cats are called kittens.",
  },
  {
    id: 363,
    subject: "Hygiene",
    question: "We use a ___ to clean our teeth.",
    options: { A: "Comb", B: "Toothbrush", C: "Spoon", D: "Soap" },
    correctAnswer: "B",
    explanation: "Toothbrushes are for cleaning teeth.",
  },
  {
    id: 364,
    subject: "Environmental",
    question: "Which animal gives us eggs?",
    options: { A: "Dog", B: "Hen", C: "Cow", D: "Cat" },
    correctAnswer: "B",
    explanation: "Hens lay eggs.",
  },
  {
    id: 365,
    subject: "Kiswahili",
    question: "Tunasema ___ ukipewa kitu.",
    options: { A: "Pole", B: "Asante", C: "Hapana", D: "Habari" },
    correctAnswer: "B",
    explanation: "Shukuru kwa kusema asante.",
  },
  {
    id: 366,
    subject: "Mathematics",
    question: "Count backwards: 3, 2, 1, __",
    options: { A: "4", B: "0", C: "5", D: "1" },
    correctAnswer: "B",
    explanation: "Zero comes before one when counting back.",
  },
  {
    id: 367,
    subject: "English",
    question: "Identify the naming word: The car is blue.",
    options: { A: "Blue", B: "Is", C: "Car", D: "The" },
    correctAnswer: "C",
    explanation: "Car is the noun (naming word).",
  },
  {
    id: 368,
    subject: "Hygiene",
    question: "Where do we bathe?",
    options: { A: "Kitchen", B: "Bathroom", C: "Bedroom", D: "Store" },
    correctAnswer: "B",
    explanation: "We wash our bodies in the bathroom.",
  },
  {
    id: 369,
    subject: "Environmental",
    question: "A dog has ___ legs.",
    options: { A: "2", B: "4", C: "6", D: "0" },
    correctAnswer: "B",
    explanation: "Dogs have four legs.",
  },
  {
    id: 370,
    subject: "Kiswahili",
    question: "Jina la nambari 1 ni ___.",
    options: { A: "Mbili", B: "Moja", C: "Tatu", D: "Nne" },
    correctAnswer: "B",
    explanation: "1 ni moja.",
  },
  {
    id: 371,
    subject: "Mathematics",
    question: "What is 4 + 2?",
    options: { A: "5", B: "6", C: "7", D: "8" },
    correctAnswer: "B",
    explanation: "4 + 2 = 6.",
  },
  {
    id: 372,
    subject: "English",
    question: "A ___ builds houses.",
    options: { A: "Teacher", B: "Mason", C: "Baker", D: "Driver" },
    correctAnswer: "B",
    explanation: "Masons build houses with bricks and stones.",
  },
  {
    id: 373,
    subject: "Hygiene",
    question: "Wash fruits ___ eating.",
    options: { A: "Before", B: "After", C: "Never", D: "During" },
    correctAnswer: "A",
    explanation: "Clean fruit before you eat it.",
  },
  {
    id: 374,
    subject: "Environmental",
    question: "Which animal has a long neck?",
    options: { A: "Lion", B: "Giraffe", C: "Hippo", D: "Dog" },
    correctAnswer: "B",
    explanation: "Giraffes have very long necks.",
  },
  {
    id: 375,
    subject: "Kiswahili",
    question: "Huyu ni ___ wangu (Sister).",
    options: { A: "Kaka", B: "Dada", C: "Mjomba", D: "Babu" },
    correctAnswer: "B",
    explanation: "Sister ni dada.",
  },
  {
    id: 376,
    subject: "Mathematics",
    question: "Which number is greater: 20 or 2?",
    options: { A: "2", B: "20", C: "None", D: "Both" },
    correctAnswer: "B",
    explanation: "20 is a larger number than 2.",
  },
  {
    id: 377,
    subject: "English",
    question: "Which word rhymes with 'cat'?",
    options: { A: "Dog", B: "Mat", C: "Sun", D: "Boy" },
    correctAnswer: "B",
    explanation: "Cat and mat have the same ending sound.",
  },
  {
    id: 378,
    subject: "Hygiene",
    question: "Use a ___ to tidy your hair.",
    options: { A: "Spoon", B: "Comb", C: "Pencil", D: "Toothbrush" },
    correctAnswer: "B",
    explanation: "Combs make hair neat.",
  },
  {
    id: 379,
    subject: "Environmental",
    question: "Which of these can fly?",
    options: { A: "Dog", B: "Bird", C: "Cat", D: "Fish" },
    correctAnswer: "B",
    explanation: "Birds use wings to fly.",
  },
  {
    id: 380,
    subject: "Kiswahili",
    question: "Asante maana yake ni ___.",
    options: { A: "Sorry", B: "Thank you", C: "Please", D: "Welcome" },
    correctAnswer: "B",
    explanation: "Asante ni kutoa shukrani.",
  },
  {
    id: 381,
    subject: "Mathematics",
    question: "What is 2 + 1?",
    options: { A: "1", B: "2", C: "3", D: "4" },
    correctAnswer: "C",
    explanation: "2 + 1 = 3.",
  },
  {
    id: 382,
    subject: "English",
    question: "I have ___ eyes.",
    options: { A: "One", B: "Two", C: "Three", D: "Ten" },
    correctAnswer: "B",
    explanation: "Humans have two eyes.",
  },
  {
    id: 383,
    subject: "Hygiene",
    question: "Boil water before ___ it.",
    options: { A: "Washing", B: "Drinking", C: "Throwing", D: "Playing" },
    correctAnswer: "B",
    explanation: "Boiling makes water safe to drink.",
  },
  {
    id: 384,
    subject: "Environmental",
    question: "Bees give us ___.",
    options: { A: "Milk", B: "Honey", C: "Eggs", D: "Meat" },
    correctAnswer: "B",
    explanation: "Bees produce honey in hives.",
  },
  {
    id: 385,
    subject: "Kiswahili",
    question: "Jina la nambari 5 ni ___.",
    options: { A: "Tano", B: "Nne", C: "Tatu", D: "Mbili" },
    correctAnswer: "A",
    explanation: "5 ni tano.",
  },
  {
    id: 386,
    subject: "Mathematics",
    question: "What shape is a door?",
    options: { A: "Circle", B: "Triangle", C: "Rectangle", D: "Square" },
    correctAnswer: "C",
    explanation: "Most doors are rectangular.",
  },
  {
    id: 387,
    subject: "English",
    question: "Identify the action word: He is jumping.",
    options: { A: "He", B: "Is", C: "Jumping", D: "Fast" },
    correctAnswer: "C",
    explanation: "Jumping is the action (verb).",
  },
  {
    id: 388,
    subject: "Hygiene",
    question: "Where do we throw rubbish?",
    options: { A: "Floor", B: "Dustbin", C: "Under the desk", D: "Garden" },
    correctAnswer: "B",
    explanation: "Always use a dustbin for trash.",
  },
  {
    id: 389,
    subject: "Environmental",
    question: "The color of a leaf is ___.",
    options: { A: "Red", B: "Blue", C: "Green", D: "Yellow" },
    correctAnswer: "C",
    explanation: "Most leaves are green.",
  },
  {
    id: 390,
    subject: "Kiswahili",
    question: "Baba na Mama ni ___ wangu.",
    options: { A: "Walimu", B: "Wazazi", C: "Marafiki", D: "Wageni" },
    correctAnswer: "B",
    explanation: "Wazazi ni mama na baba.",
  },
  {
    id: 391,
    subject: "Mathematics",
    question: "What is 10 + 0?",
    options: { A: "0", B: "10", C: "1", D: "100" },
    correctAnswer: "B",
    explanation: "Adding zero changes nothing.",
  },
  {
    id: 392,
    subject: "English",
    question: "The opposite of 'Big' is ___.",
    options: { A: "Tall", B: "Small", C: "Fat", D: "Large" },
    correctAnswer: "B",
    explanation: "Small is the opposite of big.",
  },
  {
    id: 393,
    subject: "Hygiene",
    question: "We should change our inner wear ___.",
    options: {
      A: "Every day",
      B: "Once a week",
      C: "Once a month",
      D: "Never",
    },
    correctAnswer: "A",
    explanation: "Change clothes daily for good hygiene.",
  },
  {
    id: 394,
    subject: "Environmental",
    question: "A young dog is a ___.",
    options: { A: "Kitten", B: "Puppy", C: "Calf", D: "Chick" },
    correctAnswer: "B",
    explanation: "Puppies are baby dogs.",
  },
  {
    id: 395,
    subject: "Kiswahili",
    question: "Huyu ni ___ wangu (Brother).",
    options: { A: "Dada", B: "Kaka", C: "Mama", D: "Bibi" },
    correctAnswer: "B",
    explanation: "Brother ni kaka.",
  },
  {
    id: 396,
    subject: "Mathematics",
    question: "How many legs does a cow have?",
    options: { A: "2", B: "4", C: "6", D: "8" },
    correctAnswer: "B",
    explanation: "Cows have 4 legs.",
  },
  {
    id: 397,
    subject: "English",
    question: "Which vowel comes before 'e'?",
    options: { A: "i", B: "a", C: "o", D: "u" },
    correctAnswer: "B",
    explanation: "Vowels are a, e, i, o, u.",
  },
  {
    id: 398,
    subject: "Hygiene",
    question: "We use a ___ to clean ears safely.",
    options: { A: "Stick", B: "Cotton bud", C: "Nail", D: "Stone" },
    correctAnswer: "B",
    explanation: "Cotton buds are for cleaning ears.",
  },
  {
    id: 399,
    subject: "Environmental",
    question: "The sky is ___ on a sunny day.",
    options: { A: "Green", B: "Blue", C: "Red", D: "Black" },
    correctAnswer: "B",
    explanation: "The sky looks blue during the day.",
  },
  {
    id: 400,
    subject: "Kiswahili",
    question: "Nambari kumi ni gani?",
    options: { A: "1", B: "5", C: "10", D: "20" },
    correctAnswer: "C",
    explanation: "10 ni kumi.",
  },
];
