import type { Twister } from "@/types";

export const twisters: Twister[] = [
  {
    id: 1,
    text: "She sells seashells by the seashore.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["s", "sh", "l"],
  },
  {
    id: 2,
    text: "Peter Piper picked a peck of pickled peppers.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["p", "k"],
  },
  {
    id: 3,
    text: "How much wood would a woodchuck chuck if a woodchuck could chuck wood?",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["w", "ch", "k"],
  },
  {
    id: 4,
    text: "Which witch is which?",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["w", "ch"],
  },
  {
    id: 5,
    text: "A proper copper coffee pot.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["p", "k", "t"],
  },
  {
    id: 6,
    text: "The sixth sick sheik's sixth sheep's sick.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["s", "k", "sh"],
  },
  {
    id: 7,
    text: "Betty Botter bought some butter but she said the butter’s bitter.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["b", "t", "r"],
  },
  {
    id: 8,
    text: "Fuzzy Wuzzy was a bear, Fuzzy Wuzzy had no hair.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["f", "z", "w"],
  },
  {
    id: 9,
    text: "Red lorry, yellow lorry.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["r", "l"],
  },
  {
    id: 10,
    text: "I scream, you scream, we all scream for ice cream.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["s", "k", "r", "m"],
  },
  {
    id: 11,
    text: "A big black bug bit a big black dog on his big black nose.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["b", "g"],
  },
  {
    id: 12,
    text: "Pad kid poured curd pulled cod.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["p", "k", "d"],
  },
  {
    id: 13,
    text: "Unique New York, you need unique New York.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["n", "y", "k"],
  },
  {
    id: 14,
    text: "Four fine fresh fish for you.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["f", "r", "sh"],
  },
  {
    id: 15,
    text: "I saw Susie sitting in a shoeshine shop.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["s", "sh"],
  },
  {
    id: 16,
    text: "Lesser leather never weathered wetter weather better.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["l", "th", "w", "r"],
  },
  {
    id: 17,
    text: "Can you can a can as a canner can can a can?",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["k", "n"],
  },
  {
    id: 18,
    text: "Eleven benevolent elephants.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["e", "l", "v", "n"],
  },
  {
    id: 19,
    text: "He threw three free throws.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["th", "r"],
  },
  {
    id: 20,
    text: "Six slippery snails, slid slowly seaward.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["s", "l"],
  },
  {
    id: 21,
    text: "Green glass globes glow greenly.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["g", "l", "r"],
  },
  {
    id: 22,
    text: "If a dog chews shoes, whose shoes does he choose?",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["ch", "sh", "z"],
  },
  {
    id: 23,
    text: "A skunk sat on a stump and thunk the stump stunk.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["s", "k", "t", "th"],
  },
  {
    id: 24,
    text: "Freshly fried flying fish.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["f", "r", "sh"],
  },
  {
    id: 25,
    text: "The thirty-three thieves thought that they thrilled the throne throughout Thursday.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["th", "r"],
  },
  {
    id: 26,
    text: "A loyal warrior will rarely worry why we rule.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["l", "r", "w"],
  },
  {
    id: 27,
    text: "Double bubble gum, bubbles double.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["d", "b", "l"],
  },
  {
    id: 28,
    text: "She sees cheese.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["s", "sh", "ch", "z"],
  },
  {
    id: 29,
    text: "Fred fed Ted bread, and Ted fed Fred bread.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["f", "r", "d", "t"],
  },
  {
    id: 30,
    text: "I wish to wash my Irish wristwatch.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["w", "sh", "r"],
  },
  {
    id: 31,
    text: "Good blood, bad blood.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["g", "d", "b", "l"],
  },
  {
    id: 32,
    text: "Round the rugged rocks the ragged rascal ran.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["r", "g", "d"],
  },
  {
    id: 33,
    text: "Silly Sally swiftly shooed seven silly sheep.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["s", "l", "sh"],
  },
  {
    id: 34,
    text: "Toy boat. Toy boat. Toy boat.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["t", "b"],
  },
  {
    id: 35,
    text: "We surely shall see the sun shine soon.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["s", "sh", "n"],
  },
  {
    id: 36,
    text: "World Wide Web.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["w", "r", "d"],
  },
  {
    id: 37,
    text: "How can a clam cram in a clean cream can?",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["k", "l", "m", "r"],
  },
  {
    id: 38,
    text: "Any noise annoys an oyster, but a noisy noise annoys an oyster more.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["n", "z", "s", "r"],
  },
  {
    id: 39,
    text: "Really leery, rarely Larry.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["r", "l"],
  },
  {
    id: 40,
    text: "A tiny timid turtle.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["t", "r", "l"],
  },
  {
    id: 41,
    text: "Six sticky skeletons.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["s", "t", "k"],
  },
  {
    id: 42,
    text: "Which wristwatches are Swiss wristwatches?",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["w", "r", "s", "ch"],
  },
  {
    id: 43,
    text: "Denise sees the fleece, Denise sees the fleas. At least Denise could sneeze and feed and freeze the fleas.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["d", "n", "s", "z"],
  },
  {
    id: 44,
    text: "Of all the felt I ever felt, I never felt a piece of felt which felt as fine as that felt felt.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["f", "l", "t"],
  },
  {
    id: 45,
    text: "Black back bat.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["b", "k", "t"],
  },
  {
    id: 46,
    text: "She stood on the balcony, inexplicably mimicking him hiccupping, and amicably welcoming him in.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["k", "m", "l"],
  },
  {
    id: 47,
    text: "Twelve twins twirled twelve twigs.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["t", "w", "l", "g"],
  },
  {
    id: 48,
    text: "Quick kiss, quicker kiss.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["k", "s"],
  },
  {
    id: 49,
    text: "A pessimistic pest exists amidst us.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["p", "s", "t"],
  },
  {
    id: 50,
    text: "Pirates' private property.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["p", "r", "t"],
  },
  {
    id: 51,
    text: "If you understand, say 'understand'. If you don't understand, say 'don't understand'.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["d", "n", "s", "t"],
  },
  {
    id: 52,
    text: "I thought a thought, but the thought I thought wasn't the thought I thought I thought.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["th", "t"],
  },
  {
    id: 53,
    text: "The great Greek grape growers grow great Greek grapes.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["g", "r", "p", "s"],
  },
  {
    id: 54,
    text: "Eddie edited it.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["e", "d", "t"],
  },
  {
    id: 55,
    text: "I slit the sheet, the sheet I slit, and on the slitted sheet I sit.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["s", "l", "t", "sh"],
  },
  {
    id: 56,
    text: "Rolling red wagons.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["r", "l", "g", "n"],
  },
  {
    id: 57,
    text: "Six sleek swans swam swiftly southwards.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["s", "w"],
  },
  {
    id: 58,
    text: "Imagine an imaginary menagerie manager imagining managing an imaginary menagerie.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["m", "n", "j", "g"],
  },
  {
    id: 59,
    text: "Kindly kittens knitting mittens.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["k", "n", "t"],
  },
  {
    id: 60,
    text: "There those thousand thinkers were thinking how did the other three thieves go through.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["th", "r"],
  },
  {
    id: 61,
    text: "One-one was a race horse; two-two was one too.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["w", "n", "t", "r"],
  },
  {
    id: 62,
    text: "Funny frogs flying fast.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["f", "r", "g"],
  },
  {
    id: 63,
    text: "I saw a kitten eating chicken in the kitchen.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["k", "t", "ch", "n"],
  },
  {
    id: 64,
    text: "If you notice this notice, you will notice that this notice is not worth noticing.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["n", "t", "s"],
  },
  {
    id: 65,
    text: "Kris Kringle craftily crunched on candy canes.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["k", "r", "l", "s"],
  },
  {
    id: 66,
    text: "Crisp crusts crackle and crunch.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["k", "r", "s", "ch"],
  },
  {
    id: 67,
    text: "Gobbling gargoyles gobbled gobbling goblins.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["g", "b", "l", "n"],
  },
  {
    id: 68,
    text: "Rubber baby buggy bumpers.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["r", "b", "g", "m"],
  },
  {
    id: 69,
    text: "Blue glue gun, green glue gun.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["b", "l", "g", "n"],
  },
  {
    id: 70,
    text: "Seventy-seven benevolent elephants.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["s", "v", "n", "l"],
  },
  {
    id: 71,
    text: "How many cookies could a good cook cook if a good cook could cook cookies?",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["k", "g", "d"],
  },
  {
    id: 72,
    text: "Surely the sun shall shine soon.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["sh", "s", "n"],
  },
  {
    id: 73,
    text: "So, this is the sushi chef.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["s", "sh", "ch", "f"],
  },
  {
    id: 74,
    text: "The bottom of the butter bucket is the buttered bucket bottom.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["b", "t", "m", "d"],
  },
  {
    id: 75,
    text: "Flash message.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["f", "l", "sh", "m"],
  },
  {
    id: 76,
    text: "A noisy noise annoys an oyster.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["n", "z", "s", "r"],
  },
  {
    id: 77,
    text: "Peter's pa painted Peter's pantry pink.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["p", "n", "t", "k"],
  },
  {
    id: 78,
    text: "Many an anemone sees an enemy anemone.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["m", "n", "s"],
  },
  {
    id: 79,
    text: "He seems to see the sea's serene scenes.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["s", "n", "r"],
  },
  {
    id: 80,
    text: "Fresh French fried fly fritters.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["f", "r", "t", "s"],
  },
  {
    id: 81,
    text: "Send toast to ten tense stout saints' ten tall tents.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["s", "t", "n"],
  },
  {
    id: 82,
    text: "Purple paper people.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["p", "r", "l"],
  },
  {
    id: 83,
    text: "What a terrible tongue twister.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["w", "t", "r", "s"],
  },
  {
    id: 84,
    text: "The blue bluebird blinks.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["b", "l", "k", "s"],
  },
  {
    id: 85,
    text: "Pick a partner and practice passing, perfect passing pleases the coach.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["p", "r", "k", "s"],
  },
  {
    id: 86,
    text: "Truly rural.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["t", "r", "l"],
  },
  {
    id: 87,
    text: "Wayne went to Wales to watch walruses.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["w", "l", "s", "ch"],
  },
  {
    id: 88,
    text: "Zithers slither slowly south.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["z", "th", "s", "l"],
  },
  {
    id: 89,
    text: "Thin sticks, thick bricks.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["th", "s", "k", "b"],
  },
  {
    id: 90,
    text: "A quick-witted cricket critic.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["k", "w", "t", "r"],
  },
  {
    id: 91,
    text: "Rory the warrior and Roger the worrier were reared wrongly in a rural brewery.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["r", "w", "l"],
  },
  {
    id: 92,
    text: "Tommy Tickle tickled his teacher.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["t", "k", "l", "ch"],
  },
  {
    id: 93,
    text: "Which witch wished which wicked wish?",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["w", "ch", "sh", "k"],
  },
  {
    id: 94,
    text: "She threw three balls.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["sh", "th", "r", "l"],
  },
  {
    id: 95,
    text: "I was born on a pirate ship.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["r", "p", "t", "sh"],
  },
  {
    id: 96,
    text: "The shrewd shrew sold Sarah seven silver salvers.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["s", "sh", "r", "l"],
  },
  {
    id: 97,
    text: "A clumsy crushing chore.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["k", "r", "sh", "ch"],
  },
  {
    id: 98,
    text: "Strange strategic statistics.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["s", "t", "r", "j"],
  },
  {
    id: 99,
    text: "Blake's black bike's back brake bracket broke.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["b", "l", "k", "r"],
  },
  {
    id: 100,
    text: "Chester Cheetah chewed a chunk of cheap cheddar cheese.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["ch", "t", "k", "p"],
  },
  {
    id: 101,
    text: "Brave, bleeding boys battle bald, biting babies.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["b", "l", "d"],
  },
  {
    id: 102,
    text: "Coy knows noisy boys' toys.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["k", "n", "z", "b"],
  },
  {
    id: 103,
    text: "If Stu chews shoes, should Stu choose the shoes he chews?",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["s", "t", "ch", "sh"],
  },
  {
    id: 104,
    text: "Drew's dad's dog's dead.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["d", "r", "z", "s"],
  },
  {
    id: 105,
    text: "The cat catchers can't catch caught cats.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["k", "t", "ch", "s"],
  },
  {
    id: 106,
    text: "Elizabeth has eleven elves in her elm tree.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["e", "l", "v", "z"],
  },
  {
    id: 107,
    text: "These sheep shouldn't sleep in a shack.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["sh", "s", "l", "p"],
  },
  {
    id: 108,
    text: "Great gray geese graze gracefully into Greece.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["g", "r", "s", "z"],
  },
  {
    id: 109,
    text: "Friendly Frank flips fine flapjacks.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["f", "r", "l", "p"],
  },
  {
    id: 110,
    text: "Near an ear, a nearer ear, a nearly eerie ear.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["n", "r"],
  },
  {
    id: 111,
    text: "She sells Swiss sweets.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["s", "w", "t"],
  },
  {
    id: 112,
    text: "Willie's really weary.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["w", "r", "l"],
  },
  {
    id: 113,
    text: "A slimy snake slithered down the sandy Sahara.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["s", "l", "n", "d"],
  },
  {
    id: 114,
    text: "Mix a box of mixed biscuits with a boxed biscuit mixer.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["m", "k", "s", "b"],
  },
  {
    id: 115,
    text: "Plain bun, plum bun.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["p", "l", "n", "b"],
  },
  {
    id: 116,
    text: "Where's the peck of pickled peppers Peter Piper picked?",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["p", "k", "r", "s"],
  },
  {
    id: 117,
    text: "I can think of six thin things, but I can think of six thick things too.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["th", "s", "k"],
  },
  {
    id: 118,
    text: "Clean clams crammed in clean cans.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["k", "l", "m", "n"],
  },
  {
    id: 119,
    text: "The winkle-pickers were wicker-workers.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["w", "k", "p", "r"],
  },
  {
    id: 120,
    text: "Six sharp smart sharks.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["s", "sh", "r", "k"],
  },
  {
    id: 121,
    text: "Thirty thirsty thieves.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["th", "r", "s", "t"],
  },
  {
    id: 122,
    text: "She sees the sea, she shells the shells.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["s", "sh", "l"],
  },
  {
    id: 123,
    text: "He eagerly eats eastern eggs.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["e", "g", "r", "l"],
  },
  {
    id: 124,
    text: "The myth of Miss Muffet.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["m", "th", "s", "f"],
  },
  {
    id: 125,
    text: "Seth at Sainsbury's sells thick socks.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["s", "th", "k", "l"],
  },
  {
    id: 126,
    text: "Quick, quiet, quaint queens quizzed quarreling quails.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["q", "k", "w", "l"],
  },
  {
    id: 127,
    text: "The seething sea ceaseth and thus the seething sea sufficeth us.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["s", "th", "f"],
  },
  {
    id: 128,
    text: "Jolly juggling jesters jauntily juggled jack-o-lanterns.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["j", "g", "l", "n"],
  },
  {
    id: 129,
    text: "Vivid vipers valuing valuable vases.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["v", "l", "b", "s"],
  },
  {
    id: 130,
    text: "Yonder yellow yachtsman yawns yesterday.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["y", "s", "t", "d"],
  },
  {
    id: 131,
    text: "Are our oars oak?",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["r", "k", "s"],
  },
  {
    id: 132,
    text: "A fat fish faces a fat frog.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["f", "t", "s", "r"],
  },
  {
    id: 133,
    text: "How many yaks could a yak pack pack if a yak pack could pack yaks?",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["y", "k", "p"],
  },
  {
    id: 134,
    text: "Listen to the local yokel yodel.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["l", "k", "y", "d"],
  },
  {
    id: 135,
    text: "She shrieks as she stitches sheets.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["sh", "r", "k", "s"],
  },
  {
    id: 136,
    text: "The queen in green screamed.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["q", "n", "g", "r"],
  },
  {
    id: 137,
    text: "Tie a knot, a tight knot, a tiny knot.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["t", "n"],
  },
  {
    id: 138,
    text: "Two tried and true tridents.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["t", "r", "d", "n"],
  },
  {
    id: 139,
    text: "When you write copy you have the right to copyright the copy you write.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["r", "t", "k", "p"],
  },
  {
    id: 140,
    text: "Valiant Vikings voyage viciously.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["v", "l", "n", "s"],
  },
  {
    id: 141,
    text: "The old cold scold sold the school a coal scuttle.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["l", "d", "k", "s"],
  },
  {
    id: 142,
    text: "If two witches were watching two watches, which witch would watch which watch?",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["w", "ch", "t", "s"],
  },
  {
    id: 143,
    text: "A shy she-shark.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["sh", "r", "k"],
  },
  {
    id: 144,
    text: "Give papa a cup of proper coffee in a copper coffee cup.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["p", "k", "f", "r"],
  },
  {
    id: 145,
    text: "Five frantic frogs fled from fifty fierce fishes.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["f", "r", "t", "s"],
  },
  {
    id: 146,
    text: "Zebras zigzag and zoom.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["z", "g", "m"],
  },
  {
    id: 147,
    text: "Rhys watched Ross switch his Irish wristwatch for a Swiss wristwatch.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["r", "s", "w", "ch"],
  },
  {
    id: 148,
    text: "Twelve tiny tigers tickled.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["t", "l", "g", "r"],
  },
  {
    id: 149,
    text: "Preshrunk silk shirts.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["p", "r", "sh", "k"],
  },
  {
    id: 150,
    text: "Seven selfish shellfish.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["s", "v", "n", "sh"],
  },
  {
    id: 151,
    text: "I saw Esau kissing Kate. I saw Esau, he saw me, and she saw I saw Esau.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["s", "k", "t"],
  },
  {
    id: 152,
    text: "Snap crackle pop.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["s", "n", "p", "k"],
  },
  {
    id: 153,
    text: "A tweedle beetle battle.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["t", "w", "d", "l"],
  },
  {
    id: 154,
    text: "The power of the press is a powerful press.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["p", "r", "s", "f"],
  },
  {
    id: 155,
    text: "Little Lucy loves lemons and limes.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["l", "s", "m", "n"],
  },
  {
    id: 156,
    text: "What a to-do to die today, at a minute or two to two.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["t", "d", "w"],
  },
  {
    id: 157,
    text: "A bad black cat sat on a mad black mat.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["b", "d", "k", "t"],
  },
  {
    id: 158,
    text: "Cheap ship trips.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["ch", "p", "sh", "r"],
  },
  {
    id: 159,
    text: "She sells sea shells on the sea shore. But the shells she sells are sea shells, I'm sure.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["s", "sh", "l", "r"],
  },
  {
    id: 160,
    text: "Flee from a free flea.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["f", "l", "r"],
  },
  {
    id: 161,
    text: "A bragging baker baked black bread.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["b", "r", "g", "k"],
  },
  {
    id: 162,
    text: "Top chopstick shops stock top chopsticks.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["t", "p", "ch", "s"],
  },
  {
    id: 163,
    text: "I like to light a night-light on a light night like tonight.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["l", "t", "n", "k"],
  },
  {
    id: 164,
    text: "We're real rear wheels.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["w", "r", "l"],
  },
  {
    id: 165,
    text: "Singing Sammy sung songs on sinking sand.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["s", "ng", "m", "n"],
  },
  {
    id: 166,
    text: "Nine nimble noblemen nibbled nuts.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["n", "m", "b", "l"],
  },
  {
    id: 167,
    text: "These thousand tricky Clear Speech trip thrillingly off the tongue.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["th", "s", "t", "r"],
  },
  {
    id: 168,
    text: "A snow-white swan swam swiftly to catch a slowly-swimming snake.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["s", "w", "n", "k"],
  },
  {
    id: 169,
    text: "Scissors sizzle, thistles sizzle.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["s", "z", "l", "th"],
  },
  {
    id: 170,
    text: "He has a hat in his hand.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["h", "t", "n", "d"],
  },
  {
    id: 171,
    text: "Each Easter, Eddie eats eighty Easter eggs.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["e", "s", "t", "d"],
  },
  {
    id: 172,
    text: "If you want to buy, buy, if you don't want to buy, bye bye!",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["b", "w", "n", "t"],
  },
  {
    id: 173,
    text: "Once a fellow met a fellow in a field of beans.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["f", "l", "m", "t"],
  },
  {
    id: 174,
    text: "Peter pointed proudly to the pretty painted poster.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["p", "r", "t", "d"],
  },
  {
    id: 175,
    text: "The crow flew over the river with a lump of raw liver.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["r", "l", "v", "k"],
  },
  {
    id: 176,
    text: "Did Doug dig Dick's dad's dog?",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["d", "g", "k"],
  },
  {
    id: 177,
    text: "Three short sword sheaths.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["th", "r", "s", "sh"],
  },
  {
    id: 178,
    text: "I'm not the pheasant plucker, I'm the pheasant plucker's son.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["f", "z", "n", "t"],
  },
  {
    id: 179,
    text: "Larry sent the latter letter later.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["l", "r", "t", "d"],
  },
  {
    id: 180,
    text: "Six thick thistle sticks.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["s", "k", "th", "l"],
  },
  {
    id: 181,
    text: "The soldier's shoulder surely hurts.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["s", "sh", "l", "d"],
  },
  {
    id: 182,
    text: "I wish you were a fish in my dish.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["w", "sh", "f", "d"],
  },
  {
    id: 183,
    text: "A mad madman made a mad mad Monday.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["m", "d", "n"],
  },
  {
    id: 184,
    text: "There's a sandwich on the sand which was sent by a sane witch.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["s", "n", "d", "w"],
  },
  {
    id: 185,
    text: "The top cop saw a cop top.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["t", "p", "k", "s"],
  },
  {
    id: 186,
    text: "The owner of the inside of the inn is inside the inside of the inn.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["n", "s", "d"],
  },
  {
    id: 187,
    text: "Can I cook a proper cup of coffee in a copper coffee cup?",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["k", "p", "r", "f"],
  },
  {
    id: 188,
    text: "Fresh fried fish, fish fresh fried.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["f", "r", "sh", "d"],
  },
  {
    id: 189,
    text: "Ann and Andy's anniversary is in April.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["a", "n", "d", "p"],
  },
  {
    id: 190,
    text: "I think I thank you.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["th", "k", "y"],
  },
  {
    id: 191,
    text: "No need to light a night-light on a light night like tonight.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["n", "t", "l"],
  },
  {
    id: 192,
    text: "Roast rabbit and red raspberry.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["r", "s", "t", "b"],
  },
  {
    id: 193,
    text: "A purely rural duel truly plural.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["p", "r", "l", "d"],
  },
  {
    id: 194,
    text: "He eagerly read the literary letter.",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["l", "r", "t", "d"],
  },
  {
    id: 195,
    text: "She saw a fish on the seashore and I'm sure the fish she saw was a swordfish.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["s", "sh", "f", "r"],
  },
  {
    id: 196,
    text: "What noise annoys a noisy oyster?",
    difficulty: "Easy",
    category: "Tongue Twister",
    tags: ["n", "z", "s", "t"],
  },
  {
    id: 197,
    text: "The wild wind whipped whisking willows.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["w", "l", "d", "p"],
  },
  {
    id: 198,
    text: "The chief checked his cheap cherry-red chariot.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["ch", "f", "k", "r"],
  },
  {
    id: 199,
    text: "A three-toed tree toad tied a tow-rope to a tree.",
    difficulty: "Medium",
    category: "Tongue Twister",
    tags: ["t", "r", "d", "p"],
  },
  {
    id: 200,
    text: "The big bug bit the little beetle, but the little beetle bit the big bug back.",
    difficulty: "Hard",
    category: "Tongue Twister",
    tags: ["b", "g", "t", "l"],
  },
];
