export const topics: string[] = [
  "A funny moment from campus life",
  "A leadership lesson you learned the hard way",
  "A time you solved a problem no one else could",
  "Why people overthink simple decisions",
  "A habit that changed your productivity game",
  "The most chaotic group project you ever joined",
  "A conversation that shifted your mindset",
  "Digital minimalism and why it matters",
  "Your worst procrastination moment — and the fallout",
  "When technology failed you at the worst time",
  "A misunderstanding that became hilarious later",
  "A personal rebrand you had to make",
  "Career aspirations vs. reality on the ground",
  "Your boldest decision this year",
  "The psychology of confidence",
  "Your most unexpected win",
  "A time you underestimated yourself",
  "A moment you felt unstoppable",
  "Why people avoid hard conversations",
  "How to build influence from zero",
  "Your most embarrassing tech mistake",
  "The art of bouncing back",
  "A friendship that shaped your outlook",
  "The funniest rumor you ever heard about yourself",
  "A productivity hack that actually works",
  "A challenge that nearly broke you",
  "Kwanini watu hushindwa ku-focus",
  "Your most chaotic travel story",
  "A time you impressed yourself without trying",
  "Handling pressure like a pro",
  "Your biggest campus culture shock",
  "A time you had to lead unexpectedly",
  "The day you almost quit — but didn’t",
  "Why soft skills are underrated",
  "A major L that became a strategic win",
  "A moment you felt misunderstood",
  "Dealing with people who drain your energy",
  "Your best networking moment",
  "A small decision that changed everything",
  "Why consistency beats motivation",
  "The funniest class presentation you ever witnessed",
  "A goal you hit earlier than expected",
  "Kamati ya roho chafu and how to handle them",
  "A mistake that taught you discipline",
  "Campus politics and the drama involved",
  "How you navigate imposter syndrome",
  "An idea you wish you acted on earlier",
  "The chaos of last-minute deadlines",
  "A time you had to fake confidence",
  "Why some people can’t take feedback",
  "The day you realized you were growing up",
  "A moment you handled conflict professionally",
  "The funniest thing your lecturer ever said",
  "Personal branding in the real world",
  "A time your plan collapsed — and you improvised",
  "Why people struggle with change",
  "Your most unexpected mentor",
  "A moment you felt truly appreciated",
  "A risk that paid off big time",
  "The day you realized you were the problem",
  "Why simplicity wins every time",
  "A moment you had to choose peace over ego",
  "How you deal with people who talk too much",
  "Your biggest financial lesson",
  "A win you didn’t celebrate enough",
  "Why communication creates 90% of problems",
  "A time you helped someone without expecting returns",
  "The funniest night out you ever had",
  "Your worst time-management mistake",
  "Why being quiet is a strategic weapon",
  "How you handled a high-stakes moment",
  "A moment you felt out of place",
  "Why people avoid responsibility",
  "A breakthrough you had during a tough season",
  "A time you exceeded expectations",
  "Managing stress when everything is collapsing",
  "Your best idea that came at a random time",
  "Why clarity is power",
  "A campus trend that still makes you laugh",
  "A tough truth you had to accept",
  "The weirdest compliment you ever received",
  "A time you had zero plan but everything worked",
  "Why curiosity drives growth",
  "A moment you had to say 'no'",
  "The funniest misunderstanding with a friend",
  "Personal wins you rarely talk about",
  "A time you navigated a complicated situation",
  "Why urgency creates results",
  "A moment you realized your potential",
  "The funniest mistake you made during an exam",
  "How you deal with distractions",
  "A time someone surprised you positively",
  "Why discipline is a leadership currency",
  "A moment you saw real teamwork",
  "The chaos of moving to a new hostel",
  "A time you handled a crisis calmly",
  "Why some people fear success",
  "A win you worked too hard for",
  "Your most relatable campus struggle",
  "A moment you chose growth over comfort",
  "Morning routines",
  "Your ideal weekend",
  "Your favorite childhood memory",
  "A movie you recently watched",
  "A problem you solved this week",
  "A book you want to read",
  "A food you love or hate",
  "Your dream travel destination",
  "A skill you want to learn",
  "Your most productive time of day",
  "Your biggest pet peeve",
  "A friend who inspires you",
  "A song stuck in your head",
  "A gadget you want to buy",
  "Your favorite app and why",
  "A habit you’re trying to build",
  "Social media you use most",
  "A goal you’re chasing this month",
  "Your favorite holiday",
  "A funny mistake you made",
  "A trend you think is overrated",
  "A moment you felt proud",
  "Your go-to relaxation method",
  "A hobby you want to start",
  "A city you want to live in",
  "A skill you admire in others",
  "Your workout routine (or lack of it)",
  "Something you recently learned",
  "Your relationship with money",
  "Your biggest distraction",
  "What motivates you daily",
  "Something that annoys you",
  "Your favorite tech tool",
  "Your best memory from school",
  "A food you want to try",
  "Your dream job",
  "A funny story from campus",
  "A fear you're overcoming",
  "Your favorite series",
  "Something you bought recently",
  "A moment you felt confident",
  "A person you want to meet",
  "Your favorite quote",
  "A mistake you learned from",
  "Something you want to improve",
  "A place you go to think",
  "A challenge you’re facing now",
  "A habit you dropped",
  "A compliment you received",
  "What success means to you",
  "A moment you proved someone wrong",
  "Why people struggle with long-term thinking",
  "Your most unexpected source of motivation",
  "A time you took a risk without overthinking",
  "How you handle people who doubt your abilities",
  "A moment that exposed your weaknesses",
  "Why accountability accelerates growth",
  "A time you turned frustration into progress",
  "Your most memorable hostel drama",
  "How you reinvent yourself after a setback",
  "A mistake you kept repeating until you learned",
  "Why people fear starting over",
  "A moment that tested your emotional intelligence",
  "The funniest conversation you overheard",
  "A time you had to simplify a complex idea",
  "Why people ignore opportunities around them",
  "A moment you handled something like a leader",
  "Why saying nothing is sometimes the best strategy",
  "A time you faced unexpected consequences",
  "How you navigated a high-pressure deadline",
  "Why people sabotage their progress",
  "A moment you impressed someone unintentionally",
  "A decision you made purely on instinct",
  "Why personal discipline is a competitive advantage",
  "A time you handled a misunderstanding maturely",
  "A moment when things clicked for you",
  "Why people avoid self-reflection",
  "Your funniest experience in a matatu",
  "A time you managed conflict without drama",
  "Why comfort zones are dangerous",
  "A moment you realized your priorities were shifting",
  "How you stayed calm when everything was chaotic",
  "Why some people never finish what they start",
  "A moment you felt seen or understood",
  "The funniest excuse you’ve ever heard",
  "How you deal with passive-aggressive people",
  "A time you made the wrong assumption",
  "Why emotional control is a power skill",
  "A moment you took responsibility like an adult",
  "Your funniest food-related embarrassment",
  "A time you trusted the wrong person",
  "How you bounce back from low-energy days",
  "Why courage is a daily decision",
  "A moment that felt like pure chaos",
  "How you stay consistent when motivation drops",
  "A time you had to negotiate something important",
  "Why being misunderstood is part of growth",
  "A moment you realized you needed to evolve",
  "A time you handled criticism constructively",
];
